{
 "title": "Health Dashboard (V2 Test)",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "options": {
    "content": "<a href=\"https://community.logrhythm.com/\" target=\"_blank\">\n  <div style=\"display: flex; flex-direction: column; justify-content: center; align-items: center; height: 100%; cursor: pointer;\">\n    <img src=\"https://logrhythm.com/wp-content/uploads/2023/05/LogRhythm_R_Logo_ForLightBackgrounds_RGB.png\" style=\"display: block; margin: auto;\">\n    <p style=\"margin-top: 10px;\">Visit Community</p>\n  </div>\n</a>\n\n\n"
   },
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "normalDate"
    }
   ]
  },
  {
   "title": "Diagnostics Alarms (Last 1 Day)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "rawSql": "SELECT A.[AlarmID]\r\n      ,AR.[Name] AS [Diagnostic Alarm Name]\r\n      ,A.[AlarmDate]\r\n\t  ,AR.[AlarmRuleGroup] AS [Type]\r\nFROM [LogRhythm_Alarms].[dbo].[Alarm] A\r\nJOIN [LogRhythmEMDB].[dbo].[AlarmRule] AR ON A.[AlarmRuleID] = AR.[AlarmRuleID]\r\nWHERE AR.[AlarmRuleGroup] = 'LogRhythm Diagnostics'\r\n      AND A.[AlarmDate] >= DATEADD(DAY, -1, GETDATE());"
    }
   ]
  },
  {
   "title": "Diagnostics Alarms (Last 7 Days)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "rawSql": "SELECT A.[AlarmID]\r\n      ,AR.[Name] AS [Diagnostic Alarm Name]\r\n      ,A.[AlarmDate]\r\n\t  ,AR.[AlarmRuleGroup] AS [Type]\r\nFROM [LogRhythm_Alarms].[dbo].[Alarm] A\r\nJOIN [LogRhythmEMDB].[dbo].[AlarmRule] AR ON A.[AlarmRuleID] = AR.[AlarmRuleID]\r\nWHERE AR.[AlarmRuleGroup] = 'LogRhythm Diagnostics'\r\n      AND A.[AlarmDate] >= DATEADD(DAY, -7, GETDATE());"
    }
   ]
  },
  {
   "title": "Average MPS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "USE [LogRhythm_LogMart];\r\nSELECT\r\n  [Avg MPS] = CAST(SUM(CAST(CountProcessedLogs as BIGINT)) AS real) / CAST(DATEDIFF(ss,$__timeFrom(),$__timeTo()) as BIGINT),\r\n\t[Max MPS] = CAST(MAX(CountProcessedLogs) AS float) / 60.0\r\nFROM\r\n\t[dbo].StatsDeploymentCountsMinute with (NOLOCK)\r\nWHERE  $__timeFilter(StatDate);"
    }
   ]
  },
  {
   "title": "Max MPS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "USE [LogRhythm_LogMart];\r\nSELECT\r\n  [Avg MPS] = CAST(SUM(CAST(CountProcessedLogs as BIGINT)) AS real) / CAST(DATEDIFF(ss,$__timeFrom(),$__timeTo()) as BIGINT),\r\n\t[Max MPS] = CAST(MAX(CountProcessedLogs) AS float) / 60.0\r\nFROM\r\n\t[dbo].StatsDeploymentCountsMinute with (NOLOCK)\r\nWHERE  $__timeFilter(StatDate);"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    CONCAT([Minor], '.', [Patch], '.', [Revision]) AS Version\r\nFROM \r\n    [LogRhythmEMDB].[dbo].[SCDBVersion]\r\n"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 4 },
   "options": {
    "content": "- [Go To Support](https://logrhythm.my.site.com/support/s/)\n- [Go To LR Documentation](https://docs.logrhythm.com/?l=en)\n- [Go To Community](https://community.logrhythm.com/)\n- [Go To Grafana Documentation](https://grafana.com/docs/)\n\n"
   }
  },
  {
   "title": "Number Of AIE Backlog Files",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "aie",
     "select": [
      [
       { "params": [ "Current_#_of_Data_Files" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Number Of DXRP Backlog Files",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Number Of DXRP (Backlog) Files",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "messaging.messages",
     "select": [
      [
       { "params": [ "#_Messages_Written_to_Disk" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^LRS-ENG-CM$/" }
     ]
    }
   ]
  },
  {
   "title": "Elasticsearch Health",
   "type": "table",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 4 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "limit": "1",
     "measurement": "elasticsearch_cluster_health",
     "select": [
      [
       { "params": [ "status" ], "type": "field" },
       {
        "params": [],
        "type": "mode"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Weekly Alarms Status",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    CONVERT(VARCHAR(10), AlarmDate, 101) AS [Date],\r\n    ISNULL(New, 0) + ISNULL(OpenAlarm, 0) + ISNULL(Working, 0) + ISNULL(Escalated, 0) + ISNULL(AutoClosed, 0) +\r\n    ISNULL(FalsePositive, 0) + ISNULL(Resolved, 0) + ISNULL(UnResolved, 0) + ISNULL(Reported, 0) + ISNULL(Monitor, 0) AS Total,\r\n    ISNULL(AutoClosed, 0) + ISNULL(FalsePositive, 0) + ISNULL(Resolved, 0) + ISNULL(UnResolved, 0) +\r\n    ISNULL(Reported, 0) + ISNULL(Monitor, 0) AS Closed\r\nFROM\r\n    (\r\n        SELECT\r\n            CONVERT(DATE, AlarmDate) AS AlarmDate,\r\n            COUNT(AlarmName.Name) AS AlarmCount,\r\n            (CONVERT(NVARCHAR, CASE\r\n                WHEN AlarmStatus = 0 THEN 'New'\r\n                WHEN AlarmStatus = 1 THEN 'OpenAlarm'\r\n                WHEN AlarmStatus = 2 THEN 'Working'\r\n                WHEN AlarmStatus = 3 THEN 'Escalated'\r\n                WHEN AlarmStatus = 4 THEN 'AutoClosed'\r\n                WHEN AlarmStatus = 5 THEN 'FalsePositive'\r\n                WHEN AlarmStatus = 6 THEN 'Resolved'\r\n                WHEN AlarmStatus = 7 THEN 'UnResolved'\r\n                WHEN AlarmStatus = 8 THEN 'Reported'\r\n                WHEN AlarmStatus = 9 THEN 'Monitor' END)\r\n            ) AS AlarmStatus\r\n        FROM\r\n            [LogRhythm_Alarms].[dbo].[Alarm] AS Alarm\r\n            JOIN LogRhythmEMDB.dbo.AlarmRule AS AlarmName ON Alarm.AlarmRuleID = AlarmName.AlarmRuleID\r\n        WHERE\r\n            Alarm.AlarmDate BETWEEN GETDATE() - 6 AND GETDATE()\r\n        GROUP BY\r\n            AlarmDate, AlarmStatus\r\n    ) d\r\nPIVOT\r\n    (\r\n        SUM(AlarmCount)\r\n        FOR AlarmStatus IN (New, OpenAlarm, Working, Escalated, AutoClosed, FalsePositive, Resolved, UnResolved, Reported, Monitor)\r\n    ) piv;\r\n"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "select \r\n  $__timeGroup(StatDate, '1d') AS time,\r\n  [Logs Processed] = SUM(cast(CountProcessedLogs as bigint)),\r\n  [Actual Logs Processed By AIEs] = SUM(cast(CountAnalyzedLogs as bigint)),\r\n  [Logs Processed By AIEs] = \r\n    case \r\n      when SUM(cast(CountAnalyzedLogs as bigint)) = 0 THEN 0\r\n      when SUM(cast(CountAnalyzedLogs as bigint)) <= SUM(cast(CountProcessedLogs as bigint)) THEN SUM(cast(CountAnalyzedLogs as bigint))\r\n      else SUM(cast(CountProcessedLogs as bigint))\r\n    end,\r\n  [Events Forwarded By LMs] = SUM(cast(CountEventsForwarded as bigint)),\r\n  [Events Forwarded By AIEs] = SUM(cast(CountEventsAIEngine as bigint)),\r\n  [Alarms] = SUM(cast(CountAlarms as bigint))\r\nfrom \r\n  LogRhythm_LogMart.dbo.StatsDeploymentCountsHour with (NOLOCK)\r\nWHERE \r\n  $__timeFilter(StatDate)\r\ngroup by \r\n   $__timeGroup(StatDate, '1d');"
    }
   ]
  },
  {
   "title": "Spooled DXRP On DP (Backlog Files)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
   "targets": [
    {
     "alias": "Number Of DXRP (Backlog) Files",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "messaging.messages",
     "select": [
      [
       { "params": [ "#_Messages_Written_to_Disk" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^LRS-ENG-CM$/" }
     ]
    }
   ]
  },
  {
   "title": "Indexing Rates",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 15 },
   "targets": [
    {
     "alias": "Indexed",
     "fields": [
      { "func": "mean", "name": "value" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "transporter.logs.indexed",
     "query": "SELECT mean(value) FROM \"Transporter.LogsIndexed\" WHERE \"host\" =~ /LRS-ENG-CM/ AND \"service\" = 'transporter' AND $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/LRS-ENG-CM/" }
     ]
    }
   ]
  },
  {
   "title": "Failed SQL Jobs",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 22 },
   "targets": [
    {
     "rawSql": "USE msdb;\r\n\r\nSELECT\r\n    job.name AS [Job Name],\r\n    run.run_status AS [Run Status],\r\n    run.run_date AS [Run Date],\r\n    run.run_duration AS [Run Duration (HH:MM:SS)],\r\n    run.message AS [Run Message]\r\nFROM\r\n    msdb.dbo.sysjobs job\r\n    JOIN msdb.dbo.sysjobhistory run ON job.job_id = run.job_id\r\nWHERE\r\n    run.run_status = 0 -- 0 represents failure\r\nORDER BY\r\n    run.run_date DESC, job.name, run.run_duration;\r\n"
    }
   ]
  },
  {
   "title": " LogRhythm Diagnostics Alarms",
   "type": "table",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 22 },
   "targets": [
    {
     "rawSql": "SELECT A.[AlarmID]\r\n      ,AR.[Name] AS [Diagnostic Alarm Name]\r\n      ,A.[AlarmDate]\r\n\t  ,AR.[AlarmRuleGroup] AS [Type]\r\nFROM [LogRhythm_Alarms].[dbo].[Alarm] A\r\nJOIN [LogRhythmEMDB].[dbo].[AlarmRule] AR ON A.[AlarmRuleID] = AR.[AlarmRuleID]\r\nWHERE AR.[AlarmRuleGroup] = 'LogRhythm Diagnostics';"
    }
   ]
  },
  {
   "title": "SQL Maintenance Jobs",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "rawSql": "USE [msdb];\r\n\r\n SELECT \r\n case j.[enabled] \r\n\t\twhen 0 then 'Disabled'\r\n\t\twhen 1 then 'Enabled'\r\n\t\tend as [Job Status],\r\n     j.[name] AS [Job Name],\r\n     s.[last_outcome_message] AS [Last Message],\r\n\t    \r\n\tCONVERT(int,s.last_run_date,101) as [Last Run Date], --(Issues with Conversion of date which is stored as INT)\r\n\tcase s.last_run_outcome\r\n\t\twhen 0 then 'Failed'\r\n\t\twhen 1 then 'Successful'\r\n\t\tend as [Last Run Status]\r\n\r\n  --    s.last_run_time as [Last Run Time]\r\n FROM [dbo].[sysjobs] AS j\r\n INNER JOIN [dbo].[sysjobservers] AS s ON s.[job_id] = j.[job_id]\r\n WHERE j.[enabled] = 1\r\n ORDER BY s.[last_run_date];\r\n\r\n--select * from [dbo].[sysjobservers]\r\n"
    }
   ]
  }
 ]
}