{
 "title": "2025: Compare Cases",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Cases Last Day",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n count(*) as Count\nFROM\n  \t[LogRhythm_CMDB].[dbo].[Case] with (NOLOCK)\nWHERE\n  $__timeFilter([DateCreated])"
    }
   ]
  },
  {
   "title": "Cases Last Month",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n count(*) as Count\nFROM\n  \t[LogRhythm_CMDB].[dbo].[Case] with (NOLOCK)\nWHERE\n  $__timeFilter([DateCreated])"
    }
   ]
  },
  {
   "title": "All Cases KPI Last Day",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 5, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT TOP 100 [Owner], [Case Collaborators],  (SELECT DATEDIFF_BIG (ss, CAST([Date Earliest Evidence] as datetime), CAST([Date Created]as datetime))) TTD,  (SELECT DATEDIFF_BIG(ss, CAST([Date Incident] as datetime), CAST([Date Mitigated] as datetime))) TTR,  (SELECT DATEDIFF(minute, CAST([Date Earliest Evidence] as datetime),CAST([Date Created] as datetime))) TTQ,  (SELECT DATEDIFF(minute, CAST([Date Created] as datetime),CAST([Date Incident] as datetime))) TTI,  (SELECT DATEDIFF(minute, CAST([Date Incident] as datetime),CAST([Date Mitigated] as datetime))) TTM,  (SELECT DATEDIFF(minute, CAST([Date Created] as datetime),CAST([Date Mitigated] as datetime))) TTV FROM [LogRhythm_CMDB].[dbo].[vw_Cases] WHERE\n  $__timeFilter([Date Created])"
    }
   ]
  },
  {
   "title": "Cases Last Day",
   "type": "table",
   "gridPos": { "h": 7, "w": 7, "x": 5, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT\n  cs.Name as [Case Status],\n  (CASE cs.IsClosedStatus when 1 then 'Closed' ELSE 'Open' END) as [Open_Closed],\n  COUNT(*) as Count\n FROM \n\tLogRhythm_CMDB.dbo.[Case] c with (NOLOCK) \n\t  join \n  LogRhythm_CMDB.dbo.CaseStatus cs\n\t\tON c.CaseStatusID = cs.CaseStatusID\nWHERE  $__timeFilter(c.DateCreated)\nGROUP BY\n  cs.Name,\n  cs.IsClosedStatus\nORDER BY\n  [Open_Closed] ASC"
    }
   ]
  },
  {
   "title": "All Cases KPI Last Month",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 5, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT TOP 1000 [Owner], [Case Collaborators],  (SELECT DATEDIFF_BIG (ss, CAST([Date Earliest Evidence] as datetime), CAST([Date Created]as datetime))) TTD,  (SELECT DATEDIFF_BIG(ss, CAST([Date Incident] as datetime), CAST([Date Mitigated] as datetime))) TTR,  (SELECT DATEDIFF(minute, CAST([Date Earliest Evidence] as datetime),CAST([Date Created] as datetime))) TTQ,  (SELECT DATEDIFF(minute, CAST([Date Created] as datetime),CAST([Date Incident] as datetime))) TTI,  (SELECT DATEDIFF(minute, CAST([Date Incident] as datetime),CAST([Date Mitigated] as datetime))) TTM,  (SELECT DATEDIFF(minute, CAST([Date Created] as datetime),CAST([Date Mitigated] as datetime))) TTV FROM [LogRhythm_CMDB].[dbo].[vw_Cases] WHERE\n  $__timeFilter([Date Created])"
    }
   ]
  },
  {
   "title": "Cases Last Month",
   "type": "table",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT\n  cs.Name as [Case Status],\n  (CASE cs.IsClosedStatus when 1 then 'Closed' ELSE 'Open' END) as [Open_Closed],\n  COUNT(*) as Count\n FROM \n\tLogRhythm_CMDB.dbo.[Case] c with (NOLOCK) \n\t  join \n  LogRhythm_CMDB.dbo.CaseStatus cs\n\t\tON c.CaseStatusID = cs.CaseStatusID\nWHERE  $__timeFilter(c.DateCreated)\nGROUP BY\n  cs.Name,\n  cs.IsClosedStatus\nORDER BY\n  [Open_Closed] ASC"
    }
   ]
  },
  {
   "title": "Cases Last Day",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 7, "x": 5, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT\n  [Priority],\n  AVG(DATEDIFF(MiNute,[DateEarliestEvidence],[DateCreated])) avgTTD,\n\tAVG(DATEDIFF(MiNute,[DateCreated],[DateClosed])) avgTTR,\n  COUNT(*) as Count\n FROM \n\tLogRhythm_CMDB.dbo.[Case] with (NOLOCK)\nWHERE  $__timeFilter([DateCreated])\nGROUP BY\n  [Priority]\nORDER BY\n  [Priority] ASC"
    }
   ]
  },
  {
   "title": "Cases Last Month",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT\n  [Priority],\n  AVG(DATEDIFF(MiNute,[DateEarliestEvidence],[DateCreated])) avgTTD,\n\tAVG(DATEDIFF(MiNute,[DateCreated],[DateClosed])) avgTTR,\n  COUNT(*) as Count\n FROM \n\tLogRhythm_CMDB.dbo.[Case] with (NOLOCK)\nWHERE  $__timeFilter([DateCreated])\nGROUP BY\n  [Priority]\nORDER BY\n  [Priority] ASC"
    }
   ]
  },
  {
   "title": "Cases Last Day",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "rawSql": "SELECT\n  [Priority],\n  AVG(DATEDIFF(MiNute,alm.[GeneratedOn],alm.[OpenedOn])) avgTTT,\n  AVG(DATEDIFF(MiNute,alm.[GeneratedOn],c.[DateCreated])) avgTTQ,\n  AVG(DATEDIFF(minute,c.[DateCreated],c.[DateIncident])) avgTTI,\n  AVG(DATEDIFF(minute,c.[DateIncident],c.[DateMitigated])) avgTTM,\n  AVG(DATEDIFF(MiNute,c.[DateMitigated],c.[DateClosed])) avgTTV,\n  AVG(DATEDIFF(MiNute,c.[DateEarliestEvidence],c.[DateCreated])) avgTTD,\n\tAVG(DATEDIFF(minute,c.[DateCreated],c.[DateMitigated])) avgTTR,\n  COUNT(*) as Count\n FROM \n\tLogRhythm_CMDB.dbo.[Case] c with (NOLOCK)\n\tJOIN\n  (SELECT atc.CaseID,am.GeneratedOn,am.OpenedOn,am.InvestigatedOn,am.ClosedOn FROM [LogRhythm_Alarms].[dbo].[AlarmToCase] atc JOIN [LogRhythm_Alarms].[dbo].[AlarmMetrics] am ON atc.AlarmID = am.AlarmID) alm\n    ON c.[CaseID] = alm.[CaseID]\nWHERE  $__timeFilter([DateCreated])\nGROUP BY\n  [Priority]\nORDER BY\n  [Priority] ASC"
    }
   ]
  },
  {
   "title": "Cases Last Month",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "rawSql": "SELECT\n  [Priority],\n  AVG(DATEDIFF(MiNute,alm.[GeneratedOn],alm.[OpenedOn])) avgTTT,\n  AVG(DATEDIFF(MiNute,alm.[GeneratedOn],c.[DateCreated])) avgTTQ,\n  AVG(DATEDIFF(minute,c.[DateCreated],c.[DateIncident])) avgTTI,\n  AVG(DATEDIFF(minute,c.[DateIncident],c.[DateMitigated])) avgTTM,\n  AVG(DATEDIFF(MiNute,c.[DateMitigated],c.[DateClosed])) avgTTV,\n  AVG(DATEDIFF(MiNute,c.[DateEarliestEvidence],c.[DateCreated])) avgTTD,\n\tAVG(DATEDIFF(minute,c.[DateCreated],c.[DateMitigated])) avgTTR,\n  COUNT(*) as Count\n FROM \n\tLogRhythm_CMDB.dbo.[Case] c with (NOLOCK)\n\tJOIN\n  (SELECT atc.CaseID,am.GeneratedOn,am.OpenedOn,am.InvestigatedOn,am.ClosedOn FROM [LogRhythm_Alarms].[dbo].[AlarmToCase] atc JOIN [LogRhythm_Alarms].[dbo].[AlarmMetrics] am ON atc.AlarmID = am.AlarmID) alm\n    ON c.[CaseID] = alm.[CaseID]\nWHERE  $__timeFilter([DateCreated])\nGROUP BY\n  [Priority]\nORDER BY\n  [Priority] ASC"
    }
   ]
  }
 ]
}