{
 "title": "2025: Performance - Monthly",
 "time": { "from": "now-14d", "to": "now" },
 "panels": [
  {
   "title": "SOC KPI",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "AVG TTR (15 Min)",
     "type": "stat",
     "gridPos": { "h": 6, "w": 9, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT $__timeEpoch(A.AlarmDate) \r\n\t\t, DateDIFF(MI,A.AlarmDate,AC.DateCreated) AS 'Average Time To Response'\r\nFROM LogRhythm_Alarms.dbo.Alarm A, LogRhythm_Alarms.dbo.AlarmToCase AC, LogRhythm_CMDB.dbo.\"Case\" C\r\n\t\t, LogRhythmEMDB.dbo.AlarmRule AR\r\nWHERE A.AlarmID = AC.AlarmID\r\nAND A.AlarmRuleID = AR.AlarmRuleID\r\nAND AC.CaseID = C.CaseID\r\nAND $__timeFilter(A.AlarmDate)"
      },
      {
       "rawSql": "SELECT $__timeEpoch(A.AlarmDate) \r\n\t\t, DateDIFF(MI,A.AlarmDate,AC.DateCreated) AS 'Average Time To Response Last Month'\r\nFROM LogRhythm_Alarms.dbo.Alarm A, LogRhythm_Alarms.dbo.AlarmToCase AC, LogRhythm_CMDB.dbo.\"Case\" C\r\n\t\t, LogRhythmEMDB.dbo.AlarmRule AR\r\nWHERE A.AlarmID = AC.AlarmID\r\nAND A.AlarmRuleID = AR.AlarmRuleID\r\nAND AC.CaseID = C.CaseID\r\nAND  [AlarmDate] BETWEEN (dateadd(month, -1, $__timeFrom())) and (dateadd(month, -1, $__timeTo()))"
      }
     ]
    },
    {
     "title": "AVG Time To Close (60 Min)",
     "type": "stat",
     "gridPos": { "h": 6, "w": 10, "x": 9, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "rawSql": "SELECT $__timeEpoch(A.AlarmDate) \r\n\t\t, (SELECT DateDIFF(MI,A.AlarmDate,IC.DateClosed) FROM LogRhythm_CMDB.dbo.\"Case\" IC WHERE IC.CaseID=AC.CaseID) AS 'Average Time To Close'\r\nFROM LogRhythm_Alarms.dbo.Alarm A, LogRhythm_Alarms.dbo.AlarmToCase AC, LogRhythm_CMDB.dbo.\"Case\" C, LogRhythmEMDB.dbo.Person P\r\n\t\t, LogRhythmEMDB.dbo.AlarmRule AR\r\nWHERE A.AlarmID = AC.AlarmID\r\nAND A.AlarmRuleID = AR.AlarmRuleID\r\nAND AC.CaseID = C.CaseID\r\nAND $__timeFilter(A.AlarmDate)"
      },
      {
       "rawSql": "SELECT $__timeEpoch(A.AlarmDate) \r\n\t\t, (SELECT DateDIFF(MI,A.AlarmDate,IC.DateClosed) FROM LogRhythm_CMDB.dbo.\"Case\" IC WHERE IC.CaseID=AC.CaseID) AS 'Average Time To Close Last Month'\r\nFROM LogRhythm_Alarms.dbo.Alarm A, LogRhythm_Alarms.dbo.AlarmToCase AC, LogRhythm_CMDB.dbo.\"Case\" C, LogRhythmEMDB.dbo.Person P\r\n\t\t, LogRhythmEMDB.dbo.AlarmRule AR\r\nWHERE A.AlarmID = AC.AlarmID\r\nAND A.AlarmRuleID = AR.AlarmRuleID\r\nAND AC.CaseID = C.CaseID\r\nAND [AlarmDate] BETWEEN (dateadd(month, -1, $__timeFrom())) and (dateadd(month, -1, $__timeTo()))"
      }
     ]
    },
    {
     "title": "SOC KPI Explanation ",
     "type": "text",
     "gridPos": { "h": 6, "w": 5, "x": 19, "y": 1 },
     "options": {
      "content": "# SOC KPI \n___\n1. The analyst should response to Alarm with **15 minute**.\n2. The analyst should close the Alarm after investigation within **60 minute**."
     },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Total Average Time To Response (15 Min)",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 9, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "rawSql": "SELECT $__timeEpoch(A.AlarmDate) \r\n\t\t, DateDIFF(MI,A.AlarmDate,AC.DateCreated) AS 'Average Time To Response'\r\nFROM LogRhythm_Alarms.dbo.Alarm A, LogRhythm_Alarms.dbo.AlarmToCase AC, LogRhythm_CMDB.dbo.\"Case\" C\r\n\t\t, LogRhythmEMDB.dbo.AlarmRule AR\r\nWHERE A.AlarmID = AC.AlarmID\r\nAND A.AlarmRuleID = AR.AlarmRuleID\r\nAND AC.CaseID = C.CaseID\r\nAND $__timeFilter(A.AlarmDate)"
      },
      {
       "rawSql": "SELECT $__timeEpoch(A.AlarmDate) \r\n\t\t, DateDIFF(MI,A.AlarmDate,AC.DateCreated) AS 'Average Time To Response Last Month'\r\nFROM LogRhythm_Alarms.dbo.Alarm A, LogRhythm_Alarms.dbo.AlarmToCase AC, LogRhythm_CMDB.dbo.\"Case\" C\r\n\t\t, LogRhythmEMDB.dbo.AlarmRule AR\r\nWHERE A.AlarmID = AC.AlarmID\r\nAND A.AlarmRuleID = AR.AlarmRuleID\r\nAND AC.CaseID = C.CaseID\r\nAND  [AlarmDate] BETWEEN (dateadd(month, -1, $__timeFrom())) and (dateadd(month, -1, $__timeTo()))"
      }
     ]
    },
    {
     "title": "Total Average Time To Close (60 Min)",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 10, "x": 9, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "rawSql": "SELECT $__timeEpoch(A.AlarmDate) \r\n\t\t, (SELECT DateDIFF(MI,A.AlarmDate,IC.DateClosed) FROM LogRhythm_CMDB.dbo.\"Case\" IC WHERE IC.CaseID=AC.CaseID) AS 'Average Time To Close'\r\nFROM LogRhythm_Alarms.dbo.Alarm A, LogRhythm_Alarms.dbo.AlarmToCase AC, LogRhythm_CMDB.dbo.\"Case\" C, LogRhythmEMDB.dbo.Person P\r\n\t\t, LogRhythmEMDB.dbo.AlarmRule AR\r\nWHERE A.AlarmID = AC.AlarmID\r\nAND A.AlarmRuleID = AR.AlarmRuleID\r\nAND AC.CaseID = C.CaseID\r\nAND $__timeFilter(A.AlarmDate)"
      },
      {
       "rawSql": "SELECT $__timeEpoch(A.AlarmDate) \r\n\t\t, (SELECT DateDIFF(MI,A.AlarmDate,IC.DateClosed) FROM LogRhythm_CMDB.dbo.\"Case\" IC WHERE IC.CaseID=AC.CaseID) AS 'Average Time To Close Last Month'\r\nFROM LogRhythm_Alarms.dbo.Alarm A, LogRhythm_Alarms.dbo.AlarmToCase AC, LogRhythm_CMDB.dbo.\"Case\" C, LogRhythmEMDB.dbo.Person P\r\n\t\t, LogRhythmEMDB.dbo.AlarmRule AR\r\nWHERE A.AlarmID = AC.AlarmID\r\nAND A.AlarmRuleID = AR.AlarmRuleID\r\nAND AC.CaseID = C.CaseID\r\nAND [AlarmDate] BETWEEN (dateadd(month, -1, $__timeFrom())) and (dateadd(month, -1, $__timeTo()))"
      }
     ]
    },
    {
     "title": "SOC KPI",
     "type": "stat",
     "gridPos": { "h": 7, "w": 9, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "rawSql": "SELECT\r\n       DateDIFF(MI,A.AlarmDate,AC.DateCreated) AS 'Average Time To Response'\r\n\t\t , (SELECT DateDIFF(MI,A.AlarmDate,IC.DateClosed) FROM LogRhythm_CMDB.dbo.\"Case\" IC WHERE IC.CaseID=AC.CaseID) AS 'Average Time To Close'\r\n\t\t , (SELECT COUNT(*) from LogRhythm_Alarms.dbo.Alarm a with (NOLOCK) JOIN LogRhythmEMDB.dbo.AlarmRule ar ON a.AlarmRuleID = ar.AlarmRuleID Where ar.AlarmType = 5 AND $__timeFilter(A.AlarmDate)) AS 'Count of Alerts'\r\nFROM LogRhythm_Alarms.dbo.Alarm A, LogRhythm_Alarms.dbo.AlarmToCase AC, LogRhythm_CMDB.dbo.\"Case\" C, LogRhythmEMDB.dbo.Person P\r\n\t\t, LogRhythmEMDB.dbo.AlarmRule AR\r\nWHERE A.AlarmID = AC.AlarmID\r\nAND A.AlarmRuleID = AR.AlarmRuleID\r\nAND AC.CaseID = C.CaseID\r\nAND $__timeFilter(A.AlarmDate)"
      }
     ]
    },
    {
     "title": "SOC KPI Last Month",
     "type": "stat",
     "gridPos": { "h": 7, "w": 10, "x": 9, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "rawSql": "SELECT\r\n       DateDIFF(MI,A.AlarmDate,AC.DateCreated) AS 'Average Time To Response'\r\n\t\t , (SELECT DateDIFF(MI,A.AlarmDate,IC.DateClosed) FROM LogRhythm_CMDB.dbo.\"Case\" IC WHERE IC.CaseID=AC.CaseID) AS 'Average Time To Close'\r\n\t\t , (SELECT COUNT(*) from LogRhythm_Alarms.dbo.Alarm a with (NOLOCK) JOIN LogRhythmEMDB.dbo.AlarmRule ar ON a.AlarmRuleID = ar.AlarmRuleID Where ar.AlarmType = 5 AND A.AlarmDate BETWEEN (dateadd(month, -1, $__timeFrom())) and (dateadd(month, -1, $__timeTo()))) AS 'Count of Alerts'\r\nFROM LogRhythm_Alarms.dbo.Alarm A, LogRhythm_Alarms.dbo.AlarmToCase AC, LogRhythm_CMDB.dbo.\"Case\" C, LogRhythmEMDB.dbo.Person P\r\n\t\t, LogRhythmEMDB.dbo.AlarmRule AR\r\nWHERE A.AlarmID = AC.AlarmID\r\nAND A.AlarmRuleID = AR.AlarmRuleID\r\nAND AC.CaseID = C.CaseID\r\nAND A.AlarmDate BETWEEN (dateadd(month, -1, $__timeFrom())) and (dateadd(month, -1, $__timeTo()))"
      }
     ]
    }
   ]
  },
  {
   "title": "Incidents Overall",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Incidents Number",
     "type": "stat",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "rawSql": "SELECT DISTINCT\r\n\tcount(DISTINCT C.CaseNumber) as Count\r\nFROM\r\n  \tLogRhythm_CMDB.dbo.[Case] C\r\nWhere C.CaseStatusID IN (3,4,5)\r\n    --AND CT.TagID <> 28\r\n    AND $__timeFilter(C.DateCreated)"
      }
     ]
    },
    {
     "title": "Incidents Number Last Month",
     "type": "stat",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "rawSql": "SELECT DISTINCT\r\n\tcount(DISTINCT C.CaseNumber) as Count\r\nFROM\r\n  \tLogRhythm_CMDB.dbo.[Case] C\r\nWhere C.CaseStatusID IN (3,4,5)\r\n    --AND CT.TagID <> 28\r\n    AND C.DateCreated BETWEEN (dateadd(month, -1, $__timeFrom())) and (dateadd(month, -1, $__timeTo()))"
      }
     ]
    },
    {
     "title": "Incident Status",
     "type": "piechart",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "count" ] } },
     "targets": [
      {
       "rawSql": "SELECT\r\n  $__timeEpoch(LogRhythm_CMDB.dbo.[Case].DateCreated),\r\n  COUNT(LogRhythm_CMDB.dbo.[Case].[CaseStatusID]) as value,\r\n  'Open(Created)' as metric\r\nFROM\r\n  LogRhythm_CMDB.dbo.[Case]\r\nWHERE\r\n  $__timeFilter(LogRhythm_CMDB.dbo.[Case].DateCreated)\r\n    AND LogRhythm_CMDB.dbo.[Case].CaseStatusID = 3\r\n  GROUP BY LogRhythm_CMDB.dbo.[Case].[Name], LogRhythm_CMDB.dbo.[Case].DateCreated\r\nORDER BY\r\n  LogRhythm_CMDB.dbo.[Case].DateCreated ASC"
      },
      {
       "rawSql": "SELECT\r\n  $__timeEpoch(LogRhythm_CMDB.dbo.[Case].DateCreated),\r\n  COUNT(LogRhythm_CMDB.dbo.[Case].[CaseStatusID]) as value,\r\n  'Resolved' as metric\r\nFROM\r\n  LogRhythm_CMDB.dbo.[Case]\r\nWHERE\r\n  $__timeFilter(LogRhythm_CMDB.dbo.[Case].DateCreated)\r\n    AND LogRhythm_CMDB.dbo.[Case].CaseStatusID = 5\r\n  GROUP BY LogRhythm_CMDB.dbo.[Case].[Name], LogRhythm_CMDB.dbo.[Case].DateCreated\r\nORDER BY\r\n  LogRhythm_CMDB.dbo.[Case].DateCreated ASC"
      },
      {
       "rawSql": "SELECT\r\n  $__timeEpoch(LogRhythm_CMDB.dbo.[Case].DateCreated),\r\n  COUNT(LogRhythm_CMDB.dbo.[Case].[CaseStatusID]) as value,\r\n  'Mitigated' as metric\r\nFROM\r\n  LogRhythm_CMDB.dbo.[Case]\r\nWHERE\r\n  $__timeFilter(LogRhythm_CMDB.dbo.[Case].DateCreated)\r\n    AND LogRhythm_CMDB.dbo.[Case].CaseStatusID = 4\r\n  GROUP BY LogRhythm_CMDB.dbo.[Case].[Name], LogRhythm_CMDB.dbo.[Case].DateCreated\r\nORDER BY\r\n  LogRhythm_CMDB.dbo.[Case].DateCreated ASC"
      }
     ]
    },
    {
     "title": "Incident Status Last Month",
     "type": "piechart",
     "gridPos": { "h": 11, "w": 11, "x": 13, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "count" ] } },
     "targets": [
      {
       "rawSql": "SELECT\r\n  $__timeEpoch(LogRhythm_CMDB.dbo.[Case].DateCreated),\r\n  COUNT(LogRhythm_CMDB.dbo.[Case].[CaseStatusID]) as value,\r\n  'Open(Created)' as metric\r\nFROM\r\n  LogRhythm_CMDB.dbo.[Case]\r\nWHERE\r\n    LogRhythm_CMDB.dbo.[Case].DateCreated BETWEEN (dateadd(month, -1, $__timeFrom())) and (dateadd(month, -1, $__timeTo()))\r\n    AND LogRhythm_CMDB.dbo.[Case].CaseStatusID = 3\r\n  GROUP BY LogRhythm_CMDB.dbo.[Case].[Name], LogRhythm_CMDB.dbo.[Case].DateCreated\r\nORDER BY\r\n  LogRhythm_CMDB.dbo.[Case].DateCreated ASC"
      },
      {
       "rawSql": "SELECT\r\n  $__timeEpoch(LogRhythm_CMDB.dbo.[Case].DateCreated),\r\n  COUNT(LogRhythm_CMDB.dbo.[Case].[CaseStatusID]) as value,\r\n  'Resolved' as metric\r\nFROM\r\n  LogRhythm_CMDB.dbo.[Case]\r\nWHERE\r\n  LogRhythm_CMDB.dbo.[Case].DateCreated BETWEEN (dateadd(month, -1, $__timeFrom())) and (dateadd(month, -1, $__timeTo()))\r\n    AND LogRhythm_CMDB.dbo.[Case].CaseStatusID = 5\r\n  GROUP BY LogRhythm_CMDB.dbo.[Case].[Name], LogRhythm_CMDB.dbo.[Case].DateCreated\r\nORDER BY\r\n  LogRhythm_CMDB.dbo.[Case].DateCreated ASC"
      },
      {
       "rawSql": "SELECT\r\n  $__timeEpoch(LogRhythm_CMDB.dbo.[Case].DateCreated),\r\n  COUNT(LogRhythm_CMDB.dbo.[Case].[CaseStatusID]) as value,\r\n  'Mitigated' as metric\r\nFROM\r\n  LogRhythm_CMDB.dbo.[Case]\r\nWHERE\r\n  LogRhythm_CMDB.dbo.[Case].DateCreated BETWEEN (dateadd(month, -1, $__timeFrom())) and (dateadd(month, -1, $__timeTo()))\r\n    AND LogRhythm_CMDB.dbo.[Case].CaseStatusID = 4\r\n  GROUP BY LogRhythm_CMDB.dbo.[Case].[Name], LogRhythm_CMDB.dbo.[Case].DateCreated\r\nORDER BY\r\n  LogRhythm_CMDB.dbo.[Case].DateCreated ASC"
      }
     ]
    }
   ]
  },
  {
   "title": "Alarms Overall",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Current Alarms Status Percentage",
     "type": "piechart",
     "gridPos": { "h": 9, "w": 10, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT Count(*) As 'Cloased Alarms'\r\n  FROM [LogRhythm_Alarms].[dbo].[Alarm]\r\nWHERE\r\n  $__timeFilter([DateInserted]) and AlarmStatus >= 4\r\n  "
      },
      {
       "rawSql": "SELECT Count(*) As 'Open Alarms'\r\n  FROM [LogRhythm_Alarms].[dbo].[Alarm]\r\nWHERE\r\n $__timeFilter([DateInserted]) and AlarmStatus < 4"
      }
     ]
    },
    {
     "title": "Last Month Alarms Status Percentage",
     "type": "piechart",
     "gridPos": { "h": 9, "w": 11, "x": 10, "y": 3 },
     "targets": [
      {
       "rawSql": "SELECT Count(*) As 'Open Alarms'\r\n  FROM [LogRhythm_Alarms].[dbo].[Alarm]\r\nWHERE\r\n [DateInserted] BETWEEN (dateadd(month, -1, $__timeFrom())) and (dateadd(month, -1, $__timeTo())) and AlarmStatus < 4\r\n  "
      },
      {
       "rawSql": "SELECT Count(*) As 'Closed Alarms'\r\n  FROM [LogRhythm_Alarms].[dbo].[Alarm]\r\nWHERE\r\n  [DateInserted] BETWEEN (dateadd(month, -1, $__timeFrom())) and (dateadd(month, -1, $__timeTo())) and AlarmStatus >= 4"
      }
     ]
    },
    {
     "title": "Alarms Count",
     "type": "stat",
     "gridPos": { "h": 7, "w": 10, "x": 0, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT Count(*) As 'Total of Alarms'\r\n  FROM [LogRhythm_Alarms].[dbo].[Alarm]\r\nWHERE\r\n  $__timeFilter([DateInserted])"
      },
      {
       "rawSql": "SELECT Count(*) As 'Count of Closed Alarms'\r\n  FROM [LogRhythm_Alarms].[dbo].[Alarm]\r\nWHERE\r\n  $__timeFilter([DateInserted]) and AlarmStatus >= 4"
      }
     ]
    },
    {
     "title": "Alarms Count for last month",
     "type": "stat",
     "gridPos": { "h": 7, "w": 11, "x": 10, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT Count(*) As 'Total of Alarms'\r\n  FROM [LogRhythm_Alarms].[dbo].[Alarm]\r\nWHERE\r\n  [DateInserted] BETWEEN (dateadd(month, -1, $__timeFrom())) and (dateadd(month, -1, $__timeTo()))"
      },
      {
       "rawSql": "SELECT Count(*) As 'Count of Closed Alarms'\r\n  FROM [LogRhythm_Alarms].[dbo].[Alarm]\r\nWHERE\r\n  [DateInserted] BETWEEN (dateadd(month, -1, $__timeFrom())) and (dateadd(month, -1, $__timeTo())) and AlarmStatus >= 4"
      }
     ]
    }
   ]
  },
  {
   "title": "SIEM Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Messages Per Second",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 21, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "USE [LogRhythm_LogMart];\r\nSELECT\r\n  [Avg MPS] = CAST(SUM(CAST(CountProcessedLogs as BIGINT)) AS real) / CAST(DATEDIFF(ss,$__timeFrom(),$__timeTo()) as BIGINT),\r\n\t[Max MPS] = CAST(MAX(CountProcessedLogs) AS float) / 60.0\r\nFROM\r\n\t[dbo].StatsDeploymentCountsMinute with (NOLOCK)\r\nWHERE  $__timeFilter(StatDate);"
    }
   ]
  },
  {
   "title": "Log Processing Rate",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select \r\n  [Logs Processed] = SUM(cast(CountProcessedLogs as bigint)),\r\n  [Events Forwarded By LMs] = SUM(cast(CountEventsForwarded as bigint))\r\n  --[Alarms] = SUM(cast(CountAlarms as bigint))\r\nfrom \r\n  LogRhythm_LogMart.dbo.StatsDeploymentCountsHour with (NOLOCK)\r\nWHERE \r\n  $__timeFilter(StatDate)"
    }
   ]
  },
  {
   "title": "Log Processing Rate",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 11, "x": 10, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select\r\n  [Logs Processed] = SUM(cast(CountProcessedLogs as bigint)),\r\n  [Events Forwarded By LMs] = SUM(cast(CountEventsForwarded as bigint))\r\n  --[Alarms] = SUM(cast(CountAlarms as bigint))\r\nfrom \r\n  LogRhythm_LogMart.dbo.StatsDeploymentCountsHour with (NOLOCK)\r\nWHERE \r\n  $__timeFilter(StatDate)"
    }
   ]
  },
  {
   "title": "Total Log Sources",
   "type": "stat",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(*) as Count\nFROM\n  LogRhythmEMDB.dbo.MsgSource with (NOLOCK)\nWHERE\n  RecordStatus = 1 AND Name NOT LIKE 'AI Engine%'"
    }
   ]
  },
  {
   "title": "Total Assets",
   "type": "stat",
   "gridPos": { "h": 5, "w": 11, "x": 10, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(*) as Count\nFROM\n  LogRhythmEMDB.dbo.HOST with (NOLOCK)\nWHERE\n  RecordStatus = 1 AND Name NOT LIKE 'AI Engine%'"
    }
   ]
  }
 ]
}