{
 "title": "2025: Cases Reports CISO",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "title": "Cases Count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n count(*) as Count\nFROM\n  \t[LogRhythm_CMDB].[dbo].[Case] with (NOLOCK)\nWHERE\n  $__timeFilter([DateCreated])"
    }
   ]
  },
  {
   "title": "Cases by Prioirty",
   "type": "table",
   "gridPos": { "h": 9, "w": 9, "x": 6, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  [Priority],\n  AVG(DATEDIFF(MiNute,[DateEarliestEvidence],[DateCreated])) avgTTD,\n\tAVG(DATEDIFF(MiNute,[DateCreated],[DateClosed])) avgTTR,\n  COUNT(*) as Count\n FROM \n\tLogRhythm_CMDB.dbo.[Case] with (NOLOCK)\nWHERE  $__timeFilter([DateCreated])\nGROUP BY\n  [Priority]\nORDER BY\n  [Priority] ASC"
    }
   ]
  },
  {
   "title": "Cases KPI",
   "type": "stat",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT [Owner], [Case Collaborators],  (SELECT DATEDIFF_BIG (ss, CAST([Date Earliest Evidence] as datetime), CAST([Date Created]as datetime))) TTD,  (SELECT DATEDIFF_BIG(ss, CAST([Date Incident] as datetime), CAST([Date Mitigated] as datetime))) TTR,  (SELECT DATEDIFF(minute, CAST([Date Earliest Evidence] as datetime),CAST([Date Created] as datetime))) TTQ,  (SELECT DATEDIFF(minute, CAST([Date Created] as datetime),CAST([Date Incident] as datetime))) TTI,  (SELECT DATEDIFF(minute, CAST([Date Incident] as datetime),CAST([Date Mitigated] as datetime))) TTM,  (SELECT DATEDIFF(minute, CAST([Date Created] as datetime),CAST([Date Mitigated] as datetime))) TTV FROM [LogRhythm_CMDB].[dbo].[vw_Cases]\nWHERE $__timeFilter([Date Created]) "
    }
   ]
  },
  {
   "title": "Closed ",
   "type": "stat",
   "gridPos": { "h": 13, "w": 2, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n count(*) as Count\r\nFROM\r\n  \t[LogRhythm_CMDB].[dbo].[Case] c with (NOLOCK)\r\n  \tjoin \r\n  \tLogRhythm_CMDB.dbo.CaseStatus cs\r\n  \tON c.CaseStatusID = cs.CaseStatusID\r\nWHERE\r\n  $__timeFilter([DateCreated]) AND cs.IsClosedStatus = 1"
    }
   ]
  },
  {
   "title": "Incidents",
   "type": "stat",
   "gridPos": { "h": 13, "w": 2, "x": 2, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n count(*) as Count\r\nFROM\r\n  \t[LogRhythm_CMDB].[dbo].[Case] c with (NOLOCK)\r\n  \tjoin \r\n  \tLogRhythm_CMDB.dbo.CaseStatus cs\r\n  \tON c.CaseStatusID = cs.CaseStatusID\r\nWHERE\r\n  $__timeFilter([DateCreated]) AND cs.IsClosedStatus = 0 AND cs.Name = 'Incident'"
    }
   ]
  },
  {
   "title": "Opened",
   "type": "stat",
   "gridPos": { "h": 13, "w": 2, "x": 4, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "\r\nSELECT\r\n count(*) as Count\r\nFROM\r\n  \t[LogRhythm_CMDB].[dbo].[Case] c with (NOLOCK)\r\n  \tjoin \r\n  \tLogRhythm_CMDB.dbo.CaseStatus cs\r\n  \tON c.CaseStatusID = cs.CaseStatusID\r\nWHERE\r\n  $__timeFilter([DateCreated]) AND cs.IsClosedStatus = 0 "
    }
   ]
  },
  {
   "title": "Cases Status By Analyst",
   "type": "table",
   "gridPos": { "h": 13, "w": 9, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "select * from\r\n \r\n(\r\nSELECT p.FullName as \"Case Owner\",count(c.Name) as CaseCount,\r\n(Convert(nvarchar, Case\r\nWhen CaseStatusID = 1 Then 'Created'\r\nWhen CaseStatusID = 2 Then 'Completed'\r\nWhen CaseStatusID = 3 Then 'Incident'\r\nWhen CaseStatusID = 4 Then 'Mitigated'\r\nWhen CaseStatusID = 5 Then 'Resolved' End)) as CaseStatusID\r\n  FROM [LogRhythm_CMDB].[dbo].[Case] as c\r\n  left join [LogRhythmEMDB].[dbo].[Person] as p on p.PersonID=c.PersonID\r\nWHERE  $__timeFilter(c.DateCreated)\r\ngroup by p.FullName,CaseStatusID\r\n \r\n) d\r\npivot\r\n(\r\nsum(CaseCount)\r\nfor CaseStatusID in (Created,Completed,Incident,Mitigated,Resolved)\r\n) piv"
    }
   ]
  },
  {
   "title": "Cases by Categories",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 12 },
   "targets": [
    {
     "rawSql": "select Tag,count(ct.CaseID) as Count FROM [LogRhythm_CMDB].[dbo].[CaseToTag] as ct\r\n\r\njoin  [LogRhythm_CMDB].[dbo].[Tag] as t on ct.TagID=t.TagID\r\n\r\njoin [LogRhythm_CMDB].[dbo].[Case] as c on c.caseID=ct.caseid\r\n\r\nwhere c.DateCreated between getdate()-30 and getdate()\r\n\r\nGroup By Tag"
    }
   ]
  },
  {
   "title": "Cases by Owner & Collaborators",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "rawSql": "SELECT [Owner], [Case Collaborators],  (SELECT DATEDIFF_BIG (ss, CAST([Date Earliest Evidence] as datetime), CAST([Date Created]as datetime))) TTD,  (SELECT DATEDIFF_BIG(ss, CAST([Date Incident] as datetime), CAST([Date Mitigated] as datetime))) TTR,  (SELECT DATEDIFF(minute, CAST([Date Earliest Evidence] as datetime),CAST([Date Created] as datetime))) TTQ,  (SELECT DATEDIFF(minute, CAST([Date Created] as datetime),CAST([Date Incident] as datetime))) TTI,  (SELECT DATEDIFF(minute, CAST([Date Incident] as datetime),CAST([Date Mitigated] as datetime))) TTM,  (SELECT DATEDIFF(minute, CAST([Date Created] as datetime),CAST([Date Mitigated] as datetime))) TTV FROM [LogRhythm_CMDB].[dbo].[vw_Cases]\nWHERE $__timeFilter([Date Created])"
    }
   ]
  },
  {
   "title": "Cases by Owner",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "rawSql": "select a.*,b.[Avg Time to Detect] as 'avg TTD',b.[Avg Time to Respond] as 'avg TTR',b.[Avg Time to Qualify] as 'avg TTQ',b.[Avg Time to Investigate] as 'avg TTI',b.[Avg Time to Mitigate] as 'avg TTM',b.[Avg Time to Recover] as 'avg TTV' from\r\n(select *, (isnull(Created,0)+isnull(Completed,0)+isnull(Incident,0)+isnull(Mitigated,0)+isnull(Resolved,0)) as 'Total Cases' from\r\n(\r\nSELECT p.FullName as \"Case Owner\",count(c.Name) as CaseCount,\r\n(Convert(nvarchar, Case\r\nWhen CaseStatusID = 1 Then 'Created'\r\nWhen CaseStatusID = 2 Then 'Completed'\r\nWhen CaseStatusID = 3 Then 'Incident'\r\nWhen CaseStatusID = 4 Then 'Mitigated'\r\nWhen CaseStatusID = 5 Then 'Resolved' End)) as CaseStatusID\r\n  FROM [LogRhythm_CMDB].[dbo].[Case] as c\r\n  left join [LogRhythmEMDB].[dbo].[Person] as p on p.PersonID=c.PersonID\r\n  where  DateCreated between getdate()-30 and getdate() and p.PersonID is not null\r\ngroup by p.FullName,CaseStatusID\r\n) d\r\npivot\r\n(\r\nsum(CaseCount)\r\nfor CaseStatusID in (Created,Completed,Incident,Mitigated,Resolved)\r\n) piv) as a\r\nfull outer join\r\n(select p.FullName, avg(DATEDIFF(minute,DateEarliestEvidence,DateCreated)) as 'Avg Time to Detect',\r\navg(DATEDIFF(minute,DateCreated,DateMitigated)) as 'Avg Time to Respond',\r\navg(DATEDIFF(minute,DateEarliestEvidence,DateCreated)) as 'Avg Time to Qualify',\r\navg(DATEDIFF(minute,DateCreated,DateClosed)) as 'Avg Time to Investigate',\r\navg(DATEDIFF(minute,DateIncident,DateMitigated)) as 'Avg Time to Mitigate',\r\navg(DATEDIFF(minute,DateMitigated,DateResolved)) as 'Avg Time to Recover'\r\nFROM [LogRhythm_CMDB].[dbo].[Case] as c\r\nleft join [LogRhythmEMDB].[dbo].[Person] as p on p.PersonID=c.PersonID\r\nwhere  DateCreated between getdate()-30 and getdate() and p.PersonID is not null\r\ngroup by FullName) as b on a.[Case Owner]=b.FullName"
    }
   ]
  },
  {
   "title": "Cases By Names",
   "type": "table-old",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 44 },
   "targets": [
    {
     "rawSql": "\r\n\r\nSELECT TOP 1000 [CaseNumber], [Case Name],  [Case Resolution] AS Resolution,  [Case Priority] AS Priority,  [Case Status] AS Status, (SELECT DATEDIFF_BIG (ss, CAST([Date Earliest Evidence] as datetime), CAST([Date Created]as datetime))) TTD,  \r\n(SELECT DATEDIFF_BIG(ss, CAST([Date Incident] as datetime), CAST([Date Mitigated] as datetime))) TTR,  (SELECT DATEDIFF(minute, CAST([Date Earliest Evidence] as datetime),CAST([Date Created] as datetime))) TTQ,  \r\n(SELECT DATEDIFF(minute, CAST([Date Created] as datetime),CAST([Date Incident] as datetime))) TTI,  (SELECT DATEDIFF(minute, CAST([Date Incident] as datetime),CAST([Date Mitigated] as datetime))) TTM,  \r\n(SELECT DATEDIFF(minute, CAST([Date Created] as datetime),CAST([Date Mitigated] as datetime))) TTV FROM [LogRhythm_CMDB].[dbo].[vw_Cases]\r\nWHERE $__timeFilter([Date Created]) \r\nORDER BY\r\n  [CaseNumber] DESC"
    }
   ]
  },
  {
   "title": "Cases Details  Table",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 57 },
   "targets": [
    {
     "rawSql": "\r\nSELECT  [CaseNumber],   [Case Name],  [Case Resolution] AS Resolution,  [Case Priority] AS Priority,  [Case Status] AS Status,  [Case Tags], [Owner], [Case Collaborators] AS Collaborator,  [Evidence Logs Count] AS Logs,  [Evidence Files Count] AS Files,  [Evidence Alarms Count] AS Alarms,  \r\n[Evidence Notes Count] AS Notes FROM [LogRhythm_CMDB].[dbo].[vw_Cases]\r\nWHERE $__timeFilter([Date Created])\r\nORDER BY\r\n  [CaseNumber] DESC"
    }
   ]
  }
 ]
}