{
 "title": "2025: MSSP Entity Based Reporting 2",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "MPS Per Entity",
   "type": "table",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "WITH EntityMPS AS (\r\n    SELECT \r\n        h.EntityID,\r\n        ROUND(MAX(CAST(s.CountLogs AS FLOAT) / 60), 2) AS Max_MPS,\r\n        ROUND(AVG(CAST(s.CountLogs AS FLOAT) / 60), 2) AS Avg_MPS\r\n    FROM [LogRhythmEMDB].[dbo].MsgSource ms\r\n    INNER JOIN [LogRhythmEMDB].[dbo].Host h ON ms.HostID = h.HostID\r\n    INNER JOIN [LogRhythmEMDB].[dbo].MsgSourceMaxLogDate mld ON ms.MsgSourceID = mld.MsgSourceID\r\n    INNER JOIN [LogRhythm_LogMart].[dbo].[StatsMsgSourceCountsMinute] s ON ms.MsgSourceID = s.MsgSourceID\r\n    WHERE ms.MsgSourceID > 0 AND ms.RecordStatus = 1\r\n    GROUP BY h.EntityID\r\n),\r\nLogSourceCounts AS (\r\n    SELECT \r\n        h.EntityID,\r\n        COUNT(ms.MsgSourceID) AS LogSourceCount\r\n    FROM [LogRhythmEMDB].[dbo].MsgSource ms\r\n    INNER JOIN [LogRhythmEMDB].[dbo].Host h ON ms.HostID = h.HostID\r\n    WHERE ms.MsgSourceID > 0 AND ms.RecordStatus = 1\r\n    GROUP BY h.EntityID\r\n)\r\nSELECT \r\n    e.FullName AS 'Entity',\r\n    em.Max_MPS,\r\n    em.Avg_MPS,\r\n    lsc.LogSourceCount AS 'Total LogSource'\r\nFROM EntityMPS em\r\nINNER JOIN [LogRhythmEMDB].[dbo].[Entity] e ON e.EntityID = em.EntityID\r\nINNER JOIN LogSourceCounts lsc ON lsc.EntityID = em.EntityID\r\nORDER BY e.FullName;\r\n"
    }
   ]
  },
  {
   "title": "MPE Per Entity",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "WITH EntityMPS AS (\r\n    SELECT \r\n        h.EntityID,\r\n        ROUND(MAX(CAST(s.CountLogs AS FLOAT) / 60), 2) AS Max_MPS,\r\n        ROUND(AVG(CAST(s.CountLogs AS FLOAT) / 60), 2) AS Avg_MPS\r\n    FROM [LogRhythmEMDB].[dbo].MsgSource ms\r\n    INNER JOIN [LogRhythmEMDB].[dbo].Host h ON ms.HostID = h.HostID\r\n    INNER JOIN [LogRhythmEMDB].[dbo].MsgSourceMaxLogDate mld ON ms.MsgSourceID = mld.MsgSourceID\r\n    INNER JOIN [LogRhythm_LogMart].[dbo].[StatsMsgSourceCountsMinute] s ON ms.MsgSourceID = s.MsgSourceID\r\n    WHERE ms.MsgSourceID > 0 AND ms.RecordStatus = 1\r\n    GROUP BY h.EntityID\r\n),\r\nLogSourceCounts AS (\r\n    SELECT \r\n        h.EntityID,\r\n        COUNT(ms.MsgSourceID) AS LogSourceCount\r\n    FROM [LogRhythmEMDB].[dbo].MsgSource ms\r\n    INNER JOIN [LogRhythmEMDB].[dbo].Host h ON ms.HostID = h.HostID\r\n    WHERE ms.MsgSourceID > 0 AND ms.RecordStatus = 1\r\n    GROUP BY h.EntityID\r\n)\r\nSELECT \r\n    e.FullName AS 'Entity',\r\n    em.Max_MPS,\r\n    em.Avg_MPS,\r\n    lsc.LogSourceCount AS 'Total LogSource'\r\nFROM EntityMPS em\r\nINNER JOIN [LogRhythmEMDB].[dbo].[Entity] e ON e.EntityID = em.EntityID\r\nINNER JOIN LogSourceCounts lsc ON lsc.EntityID = em.EntityID\r\nORDER BY e.FullName;\r\n"
    }
   ]
  },
  {
   "title": "Cases Per Entity",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT b.FullName as 'Entity',count(a.CaseID) as 'Count'\r\n  FROM [LogRhythm_CMDB].[dbo].[Case] as a\r\n  join [LogRhythmEMDB].[dbo].[Entity] as b on a.EntityID=b.EntityID\r\n  group by b.FullName\r\n  order by b.FullName\r\n "
    }
   ]
  },
  {
   "title": "Alarms Per Entity",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 13, "x": 11, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "LogRhythm_Alarms",
     "rawSql": "SELECT \r\n    Entity.Name AS 'Entity',\r\n    COUNT(AlarmName.Name) AS Total_Alarms\r\nFROM \r\n    [LogRhythm_Alarms].[dbo].[Alarm] AS Alarm\r\nJOIN \r\n    LogRhythmEMDB.dbo.AlarmRule AS AlarmName ON Alarm.AlarmRuleID = AlarmName.AlarmRuleID\r\nJOIN \r\n    LogRhythmEMDB.dbo.Entity AS Entity ON Entity.EntityID = Alarm.EntityID\r\nWHERE \r\n    $__timeFilter(Alarm.DateInserted)\r\n    AND AlarmName.[AlarmRuleGroup] != 'LogRhythm Diagnostics' -- Exclusion des alarmes diagnostics\r\nGROUP BY \r\n    Entity.Name\r\nORDER BY \r\n    Total_Alarms DESC;\r\n"
    }
   ]
  },
  {
   "title": "KPIs per Entity (Cases)",
   "type": "table",
   "gridPos": { "h": 14, "w": 11, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\r\nb.FullName,\r\nAVG(DATEDIFF(MINUTE, a.[DateEarliestEvidence], a.[DateCreated])) AS avgTTD,\r\nAVG(DATEDIFF(MINUTE, a.[DateCreated], a.[DateClosed])) AS avgTTR,\r\nCOUNT(*) AS CaseCount \r\nFROM \r\nLogRhythm_CMDB.dbo.[Case] as a\r\njoin [LogRhythmEMDB].[dbo].[Entity] as b on a.EntityID = b.EntityID\r\nGROUP BY\r\nb.FullName"
    }
   ]
  },
  {
   "title": "KPIs per Entity (Alarms)",
   "type": "barchart",
   "gridPos": { "h": 13, "w": 13, "x": 11, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "rawSql": "SELECT\r\nentity.FullName,\r\n   avg(DATEDIFF(MINUTE, alarm_table.DateInserted, a.DateInserted)) AS 'Time to Detect',\r\n   avg(DATEDIFF(MINUTE, a.DateInserted, b.DateInserted)) AS 'Time to Acknowledge',\r\n   avg(DATEDIFF(MINUTE, b.DateInserted, c.DateInserted)) AS 'Time to Qualify',\r\n   avg(DATEDIFF(MINUTE, c.DateInserted, d.DateInserted)) AS 'Time to Report',\r\n   avg(DATEDIFF(MINUTE, c.DateInserted, e.DateInserted)) AS 'Time to Resolve'\r\nFROM [LogRhythm_Alarms].[dbo].[AlarmHistory] a\r\nJOIN [LogRhythm_Alarms].[dbo].[Alarm] alarm_table\r\n   ON a.AlarmID = alarm_table.AlarmID\r\njoin [LogRhythmEMDB].[dbo].[Entity] as entity on alarm_table.EntityID=entity.EntityID\r\nLEFT JOIN [LogRhythm_Alarms].[dbo].[AlarmHistory] b\r\n   ON a.AlarmID = b.AlarmID\r\n   AND b.Comments = 'Changed status to: Open: Working'\r\nLEFT JOIN [LogRhythm_Alarms].[dbo].[AlarmHistory] c\r\n   ON a.AlarmID = c.AlarmID\r\n   AND (c.Comments = 'Changed status to: Closed: False Alarm' OR c.Comments = 'Changed status to: Open: Escalated')\r\nLEFT JOIN [LogRhythm_Alarms].[dbo].[AlarmHistory] d\r\n   ON a.AlarmID = d.AlarmID\r\n   AND d.Comments = 'Changed status to: Closed: Reported'\r\nLEFT JOIN [LogRhythm_Alarms].[dbo].[AlarmHistory] e\r\n   ON a.AlarmID = e.AlarmID\r\n   AND e.Comments = 'Changed status to: Closed: Resolved'\r\nWHERE a.Comments = 'Changed status to: Open'\r\ngroup by entity.FullName"
    }
   ]
  }
 ]
}