{
 "title": "2025: False Postive Report",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Use Cases",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "aie",
     "select": [
      [
       { "params": [ "#_of_Enabled_Rules" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Alarms",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n\tcount(*) as Count\nFROM\n  \tLogRhythm_Alarms.dbo.Alarm a with (NOLOCK)\n  \t  JOIN\n\t  LogRhythmEMDB.dbo.AlarmRule ar\n\t    ON a.AlarmRuleID = ar.AlarmRuleID\nWHERE\n  ar.AlarmType = 5\n    AND\n  $__timeFilter(DateInserted)"
    }
   ]
  },
  {
   "title": "False Positive Alarms",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n\tcount(*) as Count\r\nFROM\r\n  \tLogRhythm_Alarms.dbo.Alarm a with (NOLOCK)\r\n  \t  JOIN\r\n\t  LogRhythmEMDB.dbo.AlarmRule ar\r\n\t    ON a.AlarmRuleID = ar.AlarmRuleID\r\nWhere AlarmStatus = 5\r\n    AND\r\n  $__timeFilter(DateInserted)"
    }
   ]
  },
  {
   "title": "False Positive %",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT count(alarmID)*100/(SELECT count(alarmID) FROM LogRhythm_Alarms.dbo.Alarm a with (NOLOCK) JOIN LogRhythmEMDB.dbo.AlarmRule ar ON a.AlarmRuleID =ar.AlarmRuleID Where  DateInserted between getdate()-7 and getdate() ) as 'FalsePostive %'FROM LogRhythm_Alarms.dbo.Alarm a with (NOLOCK) JOIN LogRhythmEMDB.dbo.AlarmRule ar ON a.AlarmRuleID = ar.AlarmRuleID Where AlarmStatus = 5 AND DateInserted between getdate()-7 and getdate()\r\n"
    }
   ]
  },
  {
   "title": "Alarms Status %",
   "type": "table",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "WITH TotalCounts AS (\r\n    SELECT COUNT(alarmID) AS TotalAlarms\r\n    FROM LogRhythm_Alarms.dbo.Alarm a WITH (NOLOCK)\r\n    JOIN LogRhythmEMDB.dbo.AlarmRule ar ON a.AlarmRuleID = ar.AlarmRuleID\r\n    WHERE DateInserted BETWEEN DATEADD(DAY, -7, GETDATE()) AND GETDATE()\r\n)\r\nSELECT \r\n    CASE \r\n        WHEN AlarmStatus = 0 THEN 'New'\r\n        WHEN AlarmStatus = 1 THEN 'OpenAlarm'\r\n        WHEN AlarmStatus = 2 THEN 'Working'\r\n        WHEN AlarmStatus = 3 THEN 'Escalated'\r\n        WHEN AlarmStatus = 4 THEN 'AutoClosed'\r\n        WHEN AlarmStatus = 5 THEN 'FalsePositive'\r\n        WHEN AlarmStatus = 6 THEN 'Resolved'\r\n        WHEN AlarmStatus = 7 THEN 'UnResolved'\r\n        WHEN AlarmStatus = 8 THEN 'Reported'\r\n        WHEN AlarmStatus = 9 THEN 'Monitor'\r\n    END AS AlarmStatus,\r\n    CONVERT(decimal(5,2), COUNT(a.alarmID) * 100.0 / (SELECT TotalAlarms FROM TotalCounts)) AS Percentage\r\nFROM LogRhythm_Alarms.dbo.Alarm a WITH (NOLOCK)\r\nJOIN LogRhythmEMDB.dbo.AlarmRule ar ON a.AlarmRuleID = ar.AlarmRuleID\r\nWHERE $__timeFilter(DateInserted)\r\nGROUP BY AlarmStatus\r\nORDER BY Percentage DESC;\r\n"
    }
   ]
  },
  {
   "title": "False Positive Alarms",
   "type": "table",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT \n    Priority,\n    COUNT(*) AS Count\nFROM (\n    -- Subquery to join Alarm and MARCMsg tables\n    SELECT \n        alm.AlarmDate, \n        alm.AlarmStatus, \n        atm.MARCMsgID \n    FROM [LogRhythm_Alarms].[dbo].[Alarm] alm\n    JOIN [LogRhythm_Alarms].[dbo].[AlarmToMARCMsg] atm \n        ON alm.AlarmID = atm.AlarmID\n) almm\nJOIN (\n    -- Subquery to categorize priority levels\n    SELECT \n        MsgID,\n        CASE \n            WHEN Priority >= 90 THEN 'Critical' \n            WHEN Priority BETWEEN 75 AND 89 THEN 'Very High' \n            WHEN Priority BETWEEN 65 AND 74 THEN 'High' \n            WHEN Priority BETWEEN 50 AND 64 THEN 'Medium' \n            ELSE 'Low' \n        END AS Priority \n    FROM LogRhythm_Events.dbo.Msg\n) emsg \nON emsg.MsgID = almm.MARCMsgID\nWHERE \n    $__timeFilter(almm.AlarmDate)  -- Dynamic time filter\n    AND almm.AlarmStatus = 5  -- Only FalsePositive alarms\nGROUP BY Priority\nORDER BY \n    CASE Priority\n        WHEN 'Critical' THEN 1\n        WHEN 'Very High' THEN 2\n        WHEN 'High' THEN 3\n        WHEN 'Medium' THEN 4\n        WHEN 'Low' THEN 5\n    END;\n"
    }
   ]
  },
  {
   "title": "Weekly False Positive Alarms ",
   "type": "table",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    DATENAME(dw, AlarmDate) AS Day, \r\n    AlarmDate, \r\n    (ISNULL(New,0) + ISNULL(OpenAlarm,0) + ISNULL(Working,0) + ISNULL(Escalated,0) + \r\n     ISNULL(AutoClosed,0) + ISNULL(FalsePositive,0) + ISNULL(Resolved,0) + \r\n     ISNULL(UnResolved,0) + ISNULL(Reported,0) + ISNULL(Monitor,0)) AS Total,\r\n    (ISNULL(AutoClosed,0) + ISNULL(FalsePositive,0) + ISNULL(Resolved,0) + \r\n     ISNULL(UnResolved,0) + ISNULL(Reported,0) + ISNULL(Monitor,0)) AS Closed\r\nFROM (\r\n    SELECT \r\n        CONVERT(date, AlarmDate) AS AlarmDate, \r\n        COUNT(AlarmName.Name) AS AlarmCount,\r\n        (CASE \r\n            WHEN AlarmStatus = 0 THEN 'New'\r\n            WHEN AlarmStatus = 1 THEN 'OpenAlarm'\r\n            WHEN AlarmStatus = 2 THEN 'Working'\r\n            WHEN AlarmStatus = 3 THEN 'Escalated'\r\n            WHEN AlarmStatus = 4 THEN 'AutoClosed'\r\n            WHEN AlarmStatus = 5 THEN 'FalsePositive'\r\n            WHEN AlarmStatus = 6 THEN 'Resolved'\r\n            WHEN AlarmStatus = 7 THEN 'UnResolved'\r\n            WHEN AlarmStatus = 8 THEN 'Reported'\r\n            WHEN AlarmStatus = 9 THEN 'Monitor' \r\n        END) AS AlarmStatus\r\n    FROM [LogRhythm_Alarms].[dbo].[Alarm] AS Alarm \r\n    JOIN LogRhythmEMDB.dbo.AlarmRule AS AlarmName \r\n        ON Alarm.AlarmRuleID = AlarmName.AlarmRuleID\r\n    WHERE $__timeFilter(AlarmDate)\r\n    GROUP BY AlarmDate, AlarmStatus\r\n) d\r\nPIVOT (\r\n    SUM(AlarmCount)\r\n    FOR AlarmStatus IN (New, OpenAlarm, Working, Escalated, AutoClosed, \r\n                        FalsePositive, Resolved, UnResolved, Reported, Monitor)\r\n) piv\r\nORDER BY AlarmDate;\r\n"
    }
   ]
  },
  {
   "title": "FP Alarms Table by Analyst",
   "type": "table",
   "gridPos": { "h": 7, "w": 14, "x": 10, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "select FullName,(Convert(nvarchar, Case\r\nWhen AlarmStatus = 0 Then 'New'\r\nWhen AlarmStatus = 1 Then 'OpenAlarm'\r\nWhen AlarmStatus = 2 Then 'Working'\r\nWhen AlarmStatus = 3 Then 'Escalated'\r\nWhen AlarmStatus = 4 Then 'AutoClosed'\r\nWhen AlarmStatus = 5 Then 'FalsePositive'\r\nWhen AlarmStatus = 6 Then 'Resolved'\r\nWhen AlarmStatus = 7 Then 'UnResolved'\r\nWhen AlarmStatus = 8 Then 'Reported'\r\nWhen AlarmStatus = 9 Then 'Monitor' End)) as AlarmStatus\r\n, count(AlarmStatus) as 'Count'\r\nfrom AlarmMetrics\r\njoin [LogRhythm_Alarms].[dbo].[Alarm] on Alarm.AlarmID=AlarmMetrics.AlarmID\r\njoin LogRhythmEMDB.dbo.AlarmRule on Alarm.AlarmRuleID=AlarmRule.AlarmRuleID\r\nleft join [LogRhythmEMDB].[dbo].[Person] on Person.PersonID=LastPersonID\r\nwhere $__timeFilter(Alarm.AlarmDate) AND AlarmStatus = 5\r\ngroup by FullName,AlarmStatus"
    }
   ]
  },
  {
   "title": "False Positive Alarms",
   "type": "table",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    Name, \r\n    (ISNULL(AutoClosed,0) + ISNULL(New,0) + ISNULL(OpenAlarm,0) + ISNULL(Reported,0) +\r\n     ISNULL(Resolved,0) + ISNULL(FalsePositive,0) + ISNULL(Monitor,0)) AS Total,\r\n    ISNULL(New,0) AS New,\r\n    ISNULL(OpenAlarm,0) AS OpenAlarm,\r\n    ISNULL(Reported,0) AS Reported,\r\n    ISNULL(Resolved,0) AS Resolved,\r\n    ISNULL(FalsePositive,0) AS FalsePositive,\r\n    ISNULL(Monitor,0) AS Monitor,\r\n    ISNULL(AutoClosed,0) AS AutoClosed\r\nFROM (\r\n    -- Step 1: Retrieve alarm counts grouped by Name and AlarmStatus\r\n    SELECT \r\n        AlarmName.Name,\r\n        COUNT(AlarmName.Name) AS AlarmCount,\r\n        CASE \r\n            WHEN AlarmStatus = 0 THEN 'New' \r\n            WHEN AlarmStatus = 1 THEN 'OpenAlarm' \r\n            WHEN AlarmStatus = 4 THEN 'AutoClosed' \r\n            WHEN AlarmStatus = 5 THEN 'FalsePositive' \r\n            WHEN AlarmStatus = 6 THEN 'Resolved' \r\n            WHEN AlarmStatus = 8 THEN 'Reported' \r\n            WHEN AlarmStatus = 9 THEN 'Monitor' \r\n        END AS AlarmStatus\r\n    FROM [LogRhythm_Alarms].[dbo].[Alarm] AS Alarm \r\n    JOIN LogRhythmEMDB.dbo.AlarmRule AS AlarmName \r\n        ON Alarm.AlarmRuleID = AlarmName.AlarmRuleID\r\n    WHERE $__timeFilter(Alarm.AlarmDate)  -- Apply dynamic time filter\r\n    GROUP BY AlarmName.Name, AlarmStatus\r\n) d\r\nPIVOT (\r\n    -- Step 2: Pivot the AlarmStatus values into columns\r\n    SUM(AlarmCount)\r\n    FOR AlarmStatus IN (AutoClosed, New, Reported, Resolved, FalsePositive, OpenAlarm, Monitor)\r\n) piv\r\nORDER BY Total DESC;\r\n"
    }
   ]
  },
  {
   "title": "All Alarms By Analyst",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "rawSql": "select b.Technician,b.[UnAssigned Alarms],b.[Opened Alarms],b.[Closed Alarms],b.Total,a.[Avg Time to Triage],a.[AVG Time to Close],a.[AVG Time to Investigate],a.[Avg Alarms Risk]\r\nfrom (select FullName as Technician,avg(DATEDIFF(minute,GeneratedOn,OpenedOn)) as 'Avg Time to Triage', avg(DATEDIFF(minute,GeneratedOn,ClosedOn)) as 'AVG Time to Close', avg(DATEDIFF(minute,GeneratedOn,InvestigatedOn)) as 'AVG Time to Investigate'\r\n,avg(m.Priority) as  'Avg Alarms Risk',count(*) as 'Total'\r\nfrom [LogRhythm_Alarms].[dbo].AlarmMetrics\r\njoin [LogRhythm_Alarms].[dbo].[Alarm] as a on a.AlarmID=AlarmMetrics.AlarmID\r\njoin LogRhythmEMDB.dbo.AlarmRule on a.AlarmRuleID=AlarmRule.AlarmRuleID\r\nleft join [LogRhythmEMDB].[dbo].[Person] as p on p.PersonID=LastPersonID\r\nleft join [LogRhythm_Alarms].[dbo].[AlarmToMARCMsg] as am on a.AlarmID=am.AlarmID\r\nleft join [LogRhythm_Events].[dbo].[Msg] as m on am.MARCMsgID=m.MsgID\r\nwhere  $__timeFilter(AlarmDate) and p.PersonID is not null\r\ngroup by FullName) as a\r\nfull outer join\r\n(select *,isnull(\"UnAssigned Alarms\",0)+isnull(\"Opened Alarms\",0)+isnull(\"Closed Alarms\",0) as \"Total\"\r\nfrom\r\n(\r\nselect FullName as Technician, (Convert(nvarchar, Case\r\nWhen AlarmStatus = 0 Then 'UnAssigned Alarms'\r\nWhen AlarmStatus = 1 Then 'Opened Alarms'\r\nWhen AlarmStatus = 2 Then 'Opened Alarms'\r\nWhen AlarmStatus = 3 Then 'Opened Alarms'\r\nWhen AlarmStatus = 4 Then 'Closed Alarms'\r\nWhen AlarmStatus = 5 Then 'Closed Alarms'\r\nWhen AlarmStatus = 6 Then 'Closed Alarms'\r\nWhen AlarmStatus = 7 Then 'Closed Alarms'\r\nWhen AlarmStatus = 8 Then 'Closed Alarms'\r\nWhen AlarmStatus = 9 Then 'Closed Alarms' End)) as AlarmStatus, count(AlarmStatus) as 'Total'\r\nfrom [LogRhythm_Alarms].[dbo].AlarmMetrics\r\njoin [LogRhythm_Alarms].[dbo].[Alarm] as a on a.AlarmID=AlarmMetrics.AlarmID\r\njoin LogRhythmEMDB.dbo.AlarmRule on a.AlarmRuleID=AlarmRule.AlarmRuleID\r\nleft join [LogRhythmEMDB].[dbo].[Person] on Person.PersonID=LastPersonID\r\nleft join [LogRhythm_Alarms].[dbo].[AlarmToMARCMsg] as am on a.AlarmID=am.AlarmID\r\nleft join [LogRhythm_Events].[dbo].[Msg] as m on am.MARCMsgID=m.MsgID\r\nwhere  $__timeFilter(AlarmDate)\r\ngroup by FullName,AlarmStatus\r\n) d\r\npivot\r\n(\r\nsum(Total)\r\nfor AlarmStatus in (\"UnAssigned Alarms\",\"Opened Alarms\",\"Closed Alarms\")\r\n) piv) as b on a.Technician=b.Technician\r\norder by a.Technician"
    }
   ]
  }
 ]
}