{
 "title": "2025: Incidents Dashboard Report",
 "time": { "from": "now-60d", "to": "now" },
 "panels": [
  {
   "title": "Incidents Number",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT DISTINCT\r\n\tcount(DISTINCT C.CaseNumber) as Count\r\nFROM\r\n  \tLogRhythm_CMDB.dbo.[Case] C\r\nWhere C.CaseStatusID IN (3,4,5)\r\n    --AND CT.TagID <> 28\r\n    AND $__timeFilter(C.DateCreated)"
    }
   ]
  },
  {
   "title": "False Positive Incidents",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n\tcount(DISTINCT C.CaseNumber) as Count\r\nFROM\r\n  \tLogRhythm_CMDB.dbo.[Case] C, LogRhythm_CMDB.dbo.CaseToTag CT\r\nWhere C.CaseID = CT.CaseID\r\n    AND C.CaseStatusID IN (3,4,5)\r\n    AND CT.TagID = 28\r\n    AND $__timeFilter(C.DateCreated)"
    }
   ]
  },
  {
   "title": "Incident Status",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__timeEpoch(LogRhythm_CMDB.dbo.[Case].DateCreated),\r\n  COUNT(LogRhythm_CMDB.dbo.[Case].[CaseStatusID]) as value,\r\n  'Open(Created)' as metric\r\nFROM\r\n  LogRhythm_CMDB.dbo.[Case]\r\nWHERE\r\n  $__timeFilter(LogRhythm_CMDB.dbo.[Case].DateCreated)\r\n    AND LogRhythm_CMDB.dbo.[Case].CaseStatusID = 3\r\n  GROUP BY LogRhythm_CMDB.dbo.[Case].[Name], LogRhythm_CMDB.dbo.[Case].DateCreated\r\nORDER BY\r\n  LogRhythm_CMDB.dbo.[Case].DateCreated ASC"
    },
    {
     "rawSql": "SELECT\r\n  $__timeEpoch(LogRhythm_CMDB.dbo.[Case].DateCreated),\r\n  COUNT(LogRhythm_CMDB.dbo.[Case].[CaseStatusID]) as value,\r\n  'Resolved' as metric\r\nFROM\r\n  LogRhythm_CMDB.dbo.[Case]\r\nWHERE\r\n  $__timeFilter(LogRhythm_CMDB.dbo.[Case].DateCreated)\r\n    AND LogRhythm_CMDB.dbo.[Case].CaseStatusID = 5\r\n  GROUP BY LogRhythm_CMDB.dbo.[Case].[Name], LogRhythm_CMDB.dbo.[Case].DateCreated\r\nORDER BY\r\n  LogRhythm_CMDB.dbo.[Case].DateCreated ASC"
    },
    {
     "rawSql": "SELECT\r\n  $__timeEpoch(LogRhythm_CMDB.dbo.[Case].DateCreated),\r\n  COUNT(LogRhythm_CMDB.dbo.[Case].[CaseStatusID]) as value,\r\n  'Mitigated' as metric\r\nFROM\r\n  LogRhythm_CMDB.dbo.[Case]\r\nWHERE\r\n  $__timeFilter(LogRhythm_CMDB.dbo.[Case].DateCreated)\r\n    AND LogRhythm_CMDB.dbo.[Case].CaseStatusID = 4\r\n  GROUP BY LogRhythm_CMDB.dbo.[Case].[Name], LogRhythm_CMDB.dbo.[Case].DateCreated\r\nORDER BY\r\n  LogRhythm_CMDB.dbo.[Case].DateCreated ASC"
    }
   ]
  },
  {
   "title": "Policy Violation Incident",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 14, "x": 9, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__timeEpoch(LogRhythm_CMDB.dbo.[Case].DateCreated),\r\n  LogRhythm_CMDB.dbo.[Case].CaseNumber as value,\r\n  Tag.Tag as metric\r\n  \r\nFROM\r\n  LogRhythm_CMDB.dbo.[Case], LogRhythm_CMDB.dbo.CaseToTag, LogRhythm_CMDB.dbo.Tag\r\nWHERE\r\n        LogRhythm_CMDB.dbo.\"Case\".CaseID = LogRhythm_CMDB.dbo.CaseToTag.CaseID\r\n\t  AND LogRhythm_CMDB.dbo.CaseToTag.TagID = LogRhythm_CMDB.dbo.Tag.TagID\r\n          AND LogRhythm_CMDB.dbo.[Case].CaseStatusID IN (3,5)\r\n\t  AND Tag.Tag LIKE '%violation%'\r\n \t  AND $__timeFilter(LogRhythm_CMDB.dbo.[Case].DateCreated)\r\nORDER BY\r\n  LogRhythm_CMDB.dbo.[Case].DateCreated ASC"
    }
   ]
  },
  {
   "title": "Incident Brief",
   "type": "table",
   "gridPos": { "h": 10, "w": 16, "x": 3, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "rawSql": "SELECT [Case Tags] As 'Incident Tag',COUNT([CaseNumber]) as count FROM [LogRhythm_CMDB].[dbo].[vw_Cases] \nwhere [Case Status] in ('Icident', 'Mitigated', 'Resolved') AND $__timeFilter([Date Created])\nGroup by [Case Tags]\n-- Group by [Case Tags]"
    }
   ]
  },
  {
   "title": "Incident Status",
   "type": "table",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "\r\nSELECT LogRhythm_CMDB.dbo.[Case].CaseNumber AS [Case Number]\r\n     ,LogRhythm_CMDB.dbo.[Case].[Name] AS [Incident Name]\r\n\t   ,LogRhythmEMDB.dbo.Person.FullName AS [Full Name]\r\n\t   ,LogRhythm_CMDB.dbo.[Case].DateCreated AS [Date Created]\r\n\t   ,LogRhythm_CMDB.dbo.[Case].DateClosed AS [Date Closed]\r\n\t   ,LogRhythm_CMDB.dbo.[Case].DateIncident AS [IncidentDate]\r\n\t   ,ISNULL(LogRhythm_CMDB.dbo.[Case].Resolution,'') AS Resolution\r\n     ,CASE WHEN LogRhythm_CMDB.dbo.[Case].CaseStatusID = 3 THEN 'Incident'\r\n            WHEN LogRhythm_CMDB.dbo.[Case].CaseStatusID = 5 THEN 'Resolved'\r\n            ELSE 'Mitigated'END AS [Incident Status]\r\n     -- ,LogRhythm_CMDB.dbo.[Case].CaseStatusID\r\nFROM LogRhythm_CMDB.dbo.[Case], LogRhythmEMDB.dbo.Person\r\nWHERE LogRhythm_CMDB.dbo.[Case].PersonID = LogRhythmEMDB.dbo.Person.PersonID\r\n      AND LogRhythm_CMDB.dbo.[Case].CaseStatusID IN (3,4,5)\r\n      AND $__timeFilter(LogRhythm_CMDB.dbo.[Case].DateCreated)"
    }
   ]
  },
  {
   "title": "Row title",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total days since incident was opened",
   "type": "bargauge",
   "description": "Total number of days incident is still open for",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__timeEpoch(LogRhythm_CMDB.dbo.[Case].DateCreated),\r\n  (DATEDIFF(DAY,LogRhythm_CMDB.dbo.[Case].DateCreated,ISNULL(LogRhythm_CMDB.dbo.[Case].DateClosed,CURRENT_TIMESTAMP))) as value,\r\n  LogRhythm_CMDB.dbo.[Case].[Name] as metric\r\nFROM\r\n  LogRhythm_CMDB.dbo.[Case]\r\nWHERE\r\n  $__timeFilter(LogRhythm_CMDB.dbo.[Case].DateCreated)\r\n  AND LogRhythm_CMDB.dbo.[Case].CaseStatusID IN (3,4)\r\nORDER BY\r\n  LogRhythm_CMDB.dbo.[Case].DateCreated ASC"
    }
   ]
  }
 ]
}