{
 "title": "2025: VP Dashboard Report",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "SOC KPIs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "SOC KPI",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n       DateDIFF(MI,A.AlarmDate,AC.DateCreated) AS 'Average Time To Response'\r\n\t\t , (SELECT DateDIFF(MI,A.AlarmDate,IC.DateClosed) FROM LogRhythm_CMDB.dbo.\"Case\" IC WHERE IC.CaseID=AC.CaseID) AS 'Average Time To Close'\r\n\t\t , (SELECT COUNT(*) from LogRhythm_Alarms.dbo.Alarm a with (NOLOCK) JOIN LogRhythmEMDB.dbo.AlarmRule ar ON a.AlarmRuleID = ar.AlarmRuleID Where ar.AlarmType = 5 AND $__timeFilter(A.AlarmDate)) AS 'Count of Alerts'\r\nFROM LogRhythm_Alarms.dbo.Alarm A, LogRhythm_Alarms.dbo.AlarmToCase AC, LogRhythm_CMDB.dbo.\"Case\" C, LogRhythmEMDB.dbo.Person P\r\n\t\t, LogRhythmEMDB.dbo.AlarmRule AR\r\nWHERE A.AlarmID = AC.AlarmID\r\nAND A.AlarmRuleID = AR.AlarmRuleID\r\nAND AC.CaseID = C.CaseID\r\nAND $__timeFilter(A.AlarmDate)"
    }
   ]
  },
  {
   "title": "SOC KPI Last Month",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 9, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n       DateDIFF(MI,A.AlarmDate,AC.DateCreated) AS 'Average Time To Response'\r\n\t\t , (SELECT DateDIFF(MI,A.AlarmDate,IC.DateClosed) FROM LogRhythm_CMDB.dbo.\"Case\" IC WHERE IC.CaseID=AC.CaseID) AS 'Average Time To Close'\r\n\t\t , (SELECT COUNT(*) from LogRhythm_Alarms.dbo.Alarm a with (NOLOCK) JOIN LogRhythmEMDB.dbo.AlarmRule ar ON a.AlarmRuleID = ar.AlarmRuleID Where ar.AlarmType = 5 AND A.AlarmDate BETWEEN (dateadd(month, -1, $__timeFrom())) and (dateadd(month, -1, $__timeTo()))) AS 'Count of Alerts'\r\nFROM LogRhythm_Alarms.dbo.Alarm A, LogRhythm_Alarms.dbo.AlarmToCase AC, LogRhythm_CMDB.dbo.\"Case\" C, LogRhythmEMDB.dbo.Person P\r\n\t\t, LogRhythmEMDB.dbo.AlarmRule AR\r\nWHERE A.AlarmID = AC.AlarmID\r\nAND A.AlarmRuleID = AR.AlarmRuleID\r\nAND AC.CaseID = C.CaseID\r\nAND A.AlarmDate BETWEEN (dateadd(month, -1, $__timeFrom())) and (dateadd(month, -1, $__timeTo()))"
    }
   ]
  },
  {
   "title": "SOC KPI Explanation ",
   "type": "text",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "options": {
    "content": "# SOC KPI \n___\n1. The analyst should respond to Alarm with **15 minutes**.\n2. The analyst should close the Alarm after investigation within **60 minutes** for Critical Alerts."
   },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Alarms Overall",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Alarm Priority Last Day",
   "type": "table",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\n  Priority,\n  COUNT(*) as Count\nFROM\n   (SELECT alm.[AlarmDate], alm.AlarmStatus,atm.MARCMsgID FROM [LogRhythm_Alarms].[dbo].[Alarm] alm JOIN [LogRhythm_Alarms].dbo.AlarmToMARCMsg atm ON alm.AlarmID = atm.AlarmID) almm\n\t\tJOIN\n\t(SELECT \n\t\tMsgID,\n\t\t(CASE WHEN Priority >= 90 THEN 'Critical' WHEN Priority BETWEEN 75 AND 89 THEN 'Very High' WHEN Priority BETWEEN 65 AND 74 THEN 'High' WHEN Priority BETWEEN 50 AND 64 THEN 'Medium' WHEN Priority < 50 THEN 'Low' END) AS Priority \n\tFROM LogRhythm_Events.dbo.Msg) emsg \n\t\t\tON emsg.MsgID = almm.MARCMsgID\n\tWHERE\n  $__timeFilter(almm.AlarmDate)\nGROUP BY\n  Priority\nORDER BY\n  CASE Priority\n    WHEN 'Critical' THEN 1\n    WHEN 'Very High' THEN 2\n    WHEN 'High' THEN 3\n    WHEN 'Medium' THEN 4\n    WHEN 'Low' THEN 5\n  END"
    }
   ]
  },
  {
   "title": "Alarm Priority Last Month",
   "type": "table",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\n  Priority,\n  COUNT(*) as Count\nFROM\n   (SELECT alm.[AlarmDate], alm.AlarmStatus,atm.MARCMsgID FROM [LogRhythm_Alarms].[dbo].[Alarm] alm JOIN [LogRhythm_Alarms].dbo.AlarmToMARCMsg atm ON alm.AlarmID = atm.AlarmID) almm\n\t\tJOIN\n\t(SELECT \n\t\tMsgID,\n\t\t(CASE WHEN Priority >= 90 THEN 'Critical' WHEN Priority BETWEEN 75 AND 89 THEN 'Very High' WHEN Priority BETWEEN 65 AND 74 THEN 'High' WHEN Priority BETWEEN 50 AND 64 THEN 'Medium' WHEN Priority < 50 THEN 'Low' END) AS Priority \n\tFROM LogRhythm_Events.dbo.Msg) emsg \n\t\t\tON emsg.MsgID = almm.MARCMsgID\n\tWHERE\n  $__timeFilter(almm.AlarmDate)\nGROUP BY\n  Priority\nORDER BY\n  CASE Priority\n    WHEN 'Critical' THEN 1\n    WHEN 'Very High' THEN 2\n    WHEN 'High' THEN 3\n    WHEN 'Medium' THEN 4\n    WHEN 'Low' THEN 5\n  END"
    }
   ]
  },
  {
   "title": "Alarms by Criticality ",
   "type": "text",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
   "options": {
    "content": "# Alarms Criticality\n___\n1. Critical >90\n2. Very High (75 TO 89)\n3. High (65 TO 74)\n4. Medium (50 TO 64)\n5. Low <50"
   },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Use Cases with Alarms Enabled",
   "type": "stat",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT        COUNT(*) AS \"Use Cases\"\r\nFROM            AIERule INNER JOIN\r\n                         AlarmRule ON AIERule.AlarmRuleID = AlarmRule.AlarmRuleID INNER JOIN\r\n                         AIERuleToEngine ON AIERule.AIERuleID = AIERuleToEngine.AIERuleID\r\n\t\t\t\t\t\t WHERE AIERuleToEngine.Enabled =1 AND AlarmRule.Enabled =1"
    }
   ]
  },
  {
   "title": "Use Cases without Alarms Enabled",
   "type": "stat",
   "gridPos": { "h": 10, "w": 4, "x": 4, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT        COUNT(*) AS \"Use Cases\"\r\nFROM            AIERule INNER JOIN\r\n                         AlarmRule ON AIERule.AlarmRuleID = AlarmRule.AlarmRuleID INNER JOIN\r\n                         AIERuleToEngine ON AIERule.AIERuleID = AIERuleToEngine.AIERuleID\r\n\t\t\t\t\t\t WHERE AIERuleToEngine.Enabled =1 AND AlarmRule.Enabled =0"
    }
   ]
  },
  {
   "title": "All Enabled Use Cases",
   "type": "stat",
   "gridPos": { "h": 10, "w": 4, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "aie",
     "select": [
      [
       { "params": [ "#_of_Enabled_Rules" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Alarms",
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n\tcount(*) as Count\nFROM\n  \tLogRhythm_Alarms.dbo.Alarm a with (NOLOCK)\n  \t  JOIN\n\t  LogRhythmEMDB.dbo.AlarmRule ar\n\t    ON a.AlarmRuleID = ar.AlarmRuleID\nWHERE\n  ar.AlarmType = 5\n    AND\n  $__timeFilter(DateInserted)"
    }
   ]
  },
  {
   "title": "Alarms",
   "type": "text",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 17 },
   "options": {
    "content": "# Alarms\n___\n1. Use Cases with Alarms Enabled\n2. Use Cases without Alarms Enabled\n3. All Use Cases Enabled\n4. Sum of Alarms "
   },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Use Cases Creation",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 18, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT        COUNT(DateStructUpdated) As \"Count\", $__timeGroup(DateStructUpdated, '1d') AS time\nFROM            AIERule INNER JOIN\n                         AlarmRule ON AIERule.AlarmRuleID = AlarmRule.AlarmRuleID INNER JOIN\n                         AIERuleToEngine ON AIERule.AIERuleID = AIERuleToEngine.AIERuleID\n\t\t\t\t\t\t WHERE AIERuleToEngine.Enabled =1 AND AlarmRule.Enabled =1 and  $__timeFilter(DateStructUpdated)\n\t\t\t\t\t\t  GROUP BY $__timeGroup(DateStructUpdated, '1d')"
    }
   ]
  },
  {
   "title": "Use Cases Creation Trend",
   "type": "text",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 27 },
   "options": {
    "content": "# Alarms\n___\n1. Use Cases creation Trend"
   },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Alarms Trend",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "select $__timeGroup(AlarmDate, '1d') AS time, COUNT(AlarmDate)\r\nfrom [LogRhythm_Alarms].[dbo].[Alarm]\r\nwhere $__timeFilter(AlarmDate)\r\ngroup by $__timeGroup(AlarmDate, '1d')\r\norder by $__timeGroup(AlarmDate, '1d')"
    }
   ]
  },
  {
   "title": "Alarms Triggered Trend",
   "type": "text",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 39 },
   "options": {
    "content": "# Alarms\n___\n1. Alarms Triggered Trend"
   },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current Alarms Status Percentage",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT Count(*) As 'Closed Alarms'\r\n  FROM [LogRhythm_Alarms].[dbo].[Alarm]\r\nWHERE\r\n  $__timeFilter([DateInserted]) and AlarmStatus >= 4\r\n  "
    },
    {
     "rawSql": "SELECT Count(*) As 'Open Alarms'\r\n  FROM [LogRhythm_Alarms].[dbo].[Alarm]\r\nWHERE\r\n $__timeFilter([DateInserted]) and AlarmStatus < 4"
    }
   ]
  },
  {
   "title": "Last Month Alarms Status Percentage",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 9, "x": 9, "y": 48 },
   "targets": [
    {
     "rawSql": "SELECT Count(*) As 'Open Alarms'\r\n  FROM [LogRhythm_Alarms].[dbo].[Alarm]\r\nWHERE\r\n [DateInserted] BETWEEN (dateadd(month, -1, $__timeFrom())) and (dateadd(month, -1, $__timeTo())) and AlarmStatus < 4\r\n  "
    },
    {
     "rawSql": "SELECT Count(*) As 'Closed Alarms'\r\n  FROM [LogRhythm_Alarms].[dbo].[Alarm]\r\nWHERE\r\n  [DateInserted] BETWEEN (dateadd(month, -1, $__timeFrom())) and (dateadd(month, -1, $__timeTo())) and AlarmStatus >= 4"
    }
   ]
  },
  {
   "title": "Open Vs Closed Alarms",
   "type": "text",
   "gridPos": { "h": 17, "w": 6, "x": 18, "y": 48 },
   "options": {
    "content": "# Alarms\n___\n1. Open Vs Closed Alarms"
   },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Alarms Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 57 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT Count(*) As 'Total of Alarms'\r\n  FROM [LogRhythm_Alarms].[dbo].[Alarm]\r\nWHERE\r\n  $__timeFilter([DateInserted])"
    },
    {
     "rawSql": "SELECT Count(*) As 'Count of Closed Alarms'\r\n  FROM [LogRhythm_Alarms].[dbo].[Alarm]\r\nWHERE\r\n  $__timeFilter([DateInserted]) and AlarmStatus >= 4"
    },
    {
     "rawSql": "SELECT Count(*) As 'Opened Alarms'\r\n  FROM [LogRhythm_Alarms].[dbo].[Alarm]\r\nWHERE\r\n  $__timeFilter([DateInserted])and AlarmStatus < 4"
    }
   ]
  },
  {
   "title": "Alarms Count for last month",
   "type": "stat",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 57 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT Count(*) As 'Total of Alarms'\r\n  FROM [LogRhythm_Alarms].[dbo].[Alarm]\r\nWHERE\r\n  [DateInserted] BETWEEN (dateadd(month, -1, $__timeFrom())) and (dateadd(month, -1, $__timeTo()))"
    },
    {
     "rawSql": "SELECT Count(*) As 'Count of Closed Alarms'\r\n  FROM [LogRhythm_Alarms].[dbo].[Alarm]\r\nWHERE\r\n  [DateInserted] BETWEEN (dateadd(month, -1, $__timeFrom())) and (dateadd(month, -1, $__timeTo())) and AlarmStatus >= 4"
    },
    {
     "rawSql": "SELECT Count(*) As 'Opened Alarms'\r\n  FROM [LogRhythm_Alarms].[dbo].[Alarm]\r\nWHERE\r\n  [DateInserted] BETWEEN (dateadd(month, -1, $__timeFrom())) and (dateadd(month, -1, $__timeTo())) and AlarmStatus < 4"
    }
   ]
  },
  {
   "title": "Incident Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Incidents Number",
   "type": "stat",
   "gridPos": { "h": 11, "w": 7, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT DISTINCT\r\n\tcount(DISTINCT C.CaseNumber) as Count\r\nFROM\r\n  \tLogRhythm_CMDB.dbo.[Case] C\r\nWhere C.CaseStatusID IN (3,4,5)\r\n    --AND CT.TagID <> 28\r\n    AND $__timeFilter(C.DateCreated)"
    }
   ]
  },
  {
   "title": "Security Breach Incident",
   "type": "stat",
   "gridPos": { "h": 11, "w": 6, "x": 7, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__timeEpoch(LogRhythm_CMDB.dbo.[Case].DateCreated),\r\n  LogRhythm_CMDB.dbo.[Case].CaseNumber as value,\r\n  Tag.Tag as metric\r\n  \r\nFROM\r\n  LogRhythm_CMDB.dbo.[Case], LogRhythm_CMDB.dbo.CaseToTag, LogRhythm_CMDB.dbo.Tag\r\nWHERE\r\n        LogRhythm_CMDB.dbo.\"Case\".CaseID = LogRhythm_CMDB.dbo.CaseToTag.CaseID\r\n\t  AND LogRhythm_CMDB.dbo.CaseToTag.TagID = LogRhythm_CMDB.dbo.Tag.TagID\r\n          AND LogRhythm_CMDB.dbo.[Case].CaseStatusID IN (3,5)\r\n\t  AND Tag.Tag LIKE '%Security Breach%'\r\n \t  AND $__timeFilter(LogRhythm_CMDB.dbo.[Case].DateCreated)\r\nORDER BY\r\n  LogRhythm_CMDB.dbo.[Case].DateCreated ASC"
    }
   ]
  },
  {
   "title": "Incident Status",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 10, "x": 13, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__timeEpoch(LogRhythm_CMDB.dbo.[Case].DateCreated),\r\n  COUNT(LogRhythm_CMDB.dbo.[Case].[CaseStatusID]) as value,\r\n  'Open(Created)' as metric\r\nFROM\r\n  LogRhythm_CMDB.dbo.[Case]\r\nWHERE\r\n  $__timeFilter(LogRhythm_CMDB.dbo.[Case].DateCreated)\r\n    AND LogRhythm_CMDB.dbo.[Case].CaseStatusID = 3\r\n  GROUP BY LogRhythm_CMDB.dbo.[Case].[Name], LogRhythm_CMDB.dbo.[Case].DateCreated\r\nORDER BY\r\n  LogRhythm_CMDB.dbo.[Case].DateCreated ASC"
    },
    {
     "rawSql": "SELECT\r\n  $__timeEpoch(LogRhythm_CMDB.dbo.[Case].DateCreated),\r\n  COUNT(LogRhythm_CMDB.dbo.[Case].[CaseStatusID]) as value,\r\n  'Resolved' as metric\r\nFROM\r\n  LogRhythm_CMDB.dbo.[Case]\r\nWHERE\r\n  $__timeFilter(LogRhythm_CMDB.dbo.[Case].DateCreated)\r\n    AND LogRhythm_CMDB.dbo.[Case].CaseStatusID = 5\r\n  GROUP BY LogRhythm_CMDB.dbo.[Case].[Name], LogRhythm_CMDB.dbo.[Case].DateCreated\r\nORDER BY\r\n  LogRhythm_CMDB.dbo.[Case].DateCreated ASC"
    },
    {
     "rawSql": "SELECT\r\n  $__timeEpoch(LogRhythm_CMDB.dbo.[Case].DateCreated),\r\n  COUNT(LogRhythm_CMDB.dbo.[Case].[CaseStatusID]) as value,\r\n  'Mitigated' as metric\r\nFROM\r\n  LogRhythm_CMDB.dbo.[Case]\r\nWHERE\r\n  $__timeFilter(LogRhythm_CMDB.dbo.[Case].DateCreated)\r\n    AND LogRhythm_CMDB.dbo.[Case].CaseStatusID = 4\r\n  GROUP BY LogRhythm_CMDB.dbo.[Case].[Name], LogRhythm_CMDB.dbo.[Case].DateCreated\r\nORDER BY\r\n  LogRhythm_CMDB.dbo.[Case].DateCreated ASC"
    }
   ]
  },
  {
   "title": "Incident Status",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 77 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "SELECT LogRhythm_CMDB.dbo.[Case].[Name] AS [Incident Name]\r\n\t   ,LogRhythmEMDB.dbo.Person.FullName AS [Full Name]\r\n\t   ,ISNULL(LogRhythm_CMDB.dbo.[Case].Resolution,'') AS Resolution\r\n     ,CASE WHEN LogRhythm_CMDB.dbo.[Case].CaseStatusID = 3 THEN 'Incident'\r\n            WHEN LogRhythm_CMDB.dbo.[Case].CaseStatusID = 5 THEN 'Resolved'\r\n            ELSE 'Mitigated'END AS [Incident Status]\r\n     -- ,LogRhythm_CMDB.dbo.[Case].CaseStatusID\r\nFROM LogRhythm_CMDB.dbo.[Case], LogRhythmEMDB.dbo.Person\r\nWHERE LogRhythm_CMDB.dbo.[Case].PersonID = LogRhythmEMDB.dbo.Person.PersonID\r\n      AND LogRhythm_CMDB.dbo.[Case].CaseStatusID IN (3,4,5)\r\n      AND $__timeFilter(LogRhythm_CMDB.dbo.[Case].DateCreated)"
    }
   ]
  },
  {
   "title": "Incident Brief",
   "type": "table",
   "gridPos": { "h": 5, "w": 17, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "rawSql": "SELECT [Case Tags] As 'Incident Tag',COUNT([CaseNumber]) as count FROM [LogRhythm_CMDB].[dbo].[vw_Cases] \nwhere [Case Status] in ('Icident', 'Mitigated', 'Resolved') AND $__timeFilter([Date Created])\nGroup by [Case Tags]\n-- Group by [Case Tags]"
    }
   ]
  },
  {
   "title": "Total days since incident was opened",
   "type": "piechart",
   "description": "Total number of days incident is still open for",
   "gridPos": { "h": 19, "w": 12, "x": 0, "y": 92 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__timeEpoch(LogRhythm_CMDB.dbo.[Case].DateCreated),\r\n  (DATEDIFF(DAY,LogRhythm_CMDB.dbo.[Case].DateCreated,ISNULL(LogRhythm_CMDB.dbo.[Case].DateClosed,CURRENT_TIMESTAMP))) as value,\r\n  LogRhythm_CMDB.dbo.[Case].[Name] as metric\r\nFROM\r\n  LogRhythm_CMDB.dbo.[Case]\r\nWHERE\r\n  $__timeFilter(LogRhythm_CMDB.dbo.[Case].DateCreated)\r\n  AND LogRhythm_CMDB.dbo.[Case].CaseStatusID IN (3,4)\r\nORDER BY\r\n  LogRhythm_CMDB.dbo.[Case].DateCreated ASC"
    }
   ]
  },
  {
   "title": "Policy Violation Incident",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 11, "x": 13, "y": 92 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__timeEpoch(LogRhythm_CMDB.dbo.[Case].DateCreated),\r\n  LogRhythm_CMDB.dbo.[Case].CaseNumber as value,\r\n  Tag.Tag as metric\r\n  \r\nFROM\r\n  LogRhythm_CMDB.dbo.[Case], LogRhythm_CMDB.dbo.CaseToTag, LogRhythm_CMDB.dbo.Tag\r\nWHERE\r\n        LogRhythm_CMDB.dbo.\"Case\".CaseID = LogRhythm_CMDB.dbo.CaseToTag.CaseID\r\n\t  AND LogRhythm_CMDB.dbo.CaseToTag.TagID = LogRhythm_CMDB.dbo.Tag.TagID\r\n          AND LogRhythm_CMDB.dbo.[Case].CaseStatusID IN (3,5)\r\n\t  AND Tag.Tag LIKE '%violation%'\r\n \t  AND $__timeFilter(LogRhythm_CMDB.dbo.[Case].DateCreated)\r\nORDER BY\r\n  LogRhythm_CMDB.dbo.[Case].DateCreated ASC"
    }
   ]
  },
  {
   "title": "Impersonation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 111 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Impersonation",
   "type": "table",
   "gridPos": { "h": 6, "w": 13, "x": 0, "y": 112 },
   "targets": [
    {
     "rawSql": "SELECT $__timeEpoch(LogRhythm_CMDB.dbo.[Case].DateCreated),\r\n  LogRhythm_CMDB.dbo.[Case].Name as 'Case Name',\r\n  Tag.Tag as 'Tag',\r\n CASE WHEN  [LogRhythm_CMDB].[dbo].[Case].CaseStatusid = 1 THEN 'Created'\r\n  when [LogRhythm_CMDB].[dbo].[Case].CaseStatusid = 2 THEN 'Completed'\r\n  when [LogRhythm_CMDB].[dbo].[Case].CaseStatusid = 3 THEN 'Incident'\r\n  when [LogRhythm_CMDB].[dbo].[Case].CaseStatusid = 4 THEN 'Mitigated'\r\n  else  'Resolved' end as [Status]\r\nFROM\r\n  LogRhythm_CMDB.dbo.[Case], LogRhythm_CMDB.dbo.CaseToTag, LogRhythm_CMDB.dbo.Tag\r\nWHERE\r\n        LogRhythm_CMDB.dbo.\"Case\".CaseID = LogRhythm_CMDB.dbo.CaseToTag.CaseID\r\n\t  AND LogRhythm_CMDB.dbo.CaseToTag.TagID = LogRhythm_CMDB.dbo.Tag.TagID\r\n          AND LogRhythm_CMDB.dbo.[Case].CaseStatusID IN (3,5)\r\n\t  AND (Tag.Tag = 'Account impersonation' OR Tag.Tag = 'Domain impersonation')\r\n\t   \t  AND $__timeFilter(LogRhythm_CMDB.dbo.[Case].DateCreated)\r\nORDER BY\r\n  LogRhythm_CMDB.dbo.[Case].DateCreated ASC"
    }
   ]
  },
  {
   "title": "Impersonation",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 11, "x": 13, "y": 112 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__timeEpoch(LogRhythm_CMDB.dbo.[Case].DateCreated),\r\n  LogRhythm_CMDB.dbo.[Case].CaseNumber as value,\r\n  Tag.Tag as metric\r\n  \r\nFROM\r\n  LogRhythm_CMDB.dbo.[Case], LogRhythm_CMDB.dbo.CaseToTag, LogRhythm_CMDB.dbo.Tag\r\nWHERE\r\n        LogRhythm_CMDB.dbo.\"Case\".CaseID = LogRhythm_CMDB.dbo.CaseToTag.CaseID\r\n\t  AND LogRhythm_CMDB.dbo.CaseToTag.TagID = LogRhythm_CMDB.dbo.Tag.TagID\r\n          AND LogRhythm_CMDB.dbo.[Case].CaseStatusID IN (3,5)\r\n\t  AND (Tag.Tag = 'Account impersonation' OR Tag.Tag = 'Domain impersonation')\r\n \t  AND $__timeFilter(LogRhythm_CMDB.dbo.[Case].DateCreated)\r\nORDER BY\r\n  LogRhythm_CMDB.dbo.[Case].DateCreated ASC"
    }
   ]
  }
 ]
}