{
 "title": "2025: Alarms & Cases KPIs 2",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Alarms ",
   "type": "stat",
   "gridPos": { "h": 20, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n\tcount(*) as Count\nFROM\n  \tLogRhythm_Alarms.dbo.Alarm a with (NOLOCK)\n  \t  JOIN\n\t  LogRhythmEMDB.dbo.AlarmRule ar\n\t    ON a.AlarmRuleID = ar.AlarmRuleID\nWHERE\n  ar.AlarmType = 5\n    AND\n  $__timeFilter(DateInserted)"
    }
   ]
  },
  {
   "title": "Alarms Last Day",
   "type": "table",
   "gridPos": { "h": 9, "w": 6, "x": 3, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n\tmsg.Alarm_Priority,\r\n\tAVG(amsg.TTD) avgTTD,\r\n\tAVG(amsg.TTR) avgTTR,\r\n\tCOUNT(*) as Count\r\nFROM\r\n  (SELECT\r\n\tCASE \r\n\t\tWHEN Priority >= 90 THEN 'Critical'\r\n\t\tWHEN Priority BETWEEN 80 and 89 THEN 'High'\r\n\t\tWHEN Priority BETWEEN 65 and 79 THEN 'Medium'\r\n\t\tWHEN Priority BETWEEN 50 and 64 THEN 'Low'\r\n\t\tWHEN Priority < 50 THEN 'Very Low'\r\n\tEND AS Alarm_Priority,\r\n\tMsgID\r\nFROM \r\n\tLogRhythm_Events.dbo.Msg with (NOLOCK)) msg\r\n\t  JOIN\r\n\t(SELECT \r\n\t\ta.DateInserted,\r\n\t\tatm.MARCMsgID,\r\n\t\ta.AlarmID,\r\n\t\tDATEDIFF(MINUTE,am.GeneratedOn,am.OpenedOn) TTT,\r\n\t\tDATEDIFF(MINUTE,am.GeneratedOn,am.InvestigatedOn) TTD,\r\n\t\tDATEDIFF(MINUTE,am.InvestigatedOn,am.ClosedOn) TTR\r\n\tFROM \r\n\t\tLogRhythm_Alarms.dbo.Alarm a with (NOLOCK) \r\n\t\t\tJOIN \r\n\t\tLogRhythm_Alarms.dbo.AlarmToMARCMsg atm with (NOLOCK) \r\n\t\t\tON a.AlarmID = atm.AlarmID\r\n\t\t\tJOIN\r\n\t\t[LogRhythm_Alarms].[dbo].[AlarmMetrics] am with (NOLOCK) \r\n\t\t\tON a.AlarmID = am.AlarmID\r\n\t\t\tJOIN\r\n\t\t[LogRhythmEMDB].[dbo].AlarmRule ar\r\n\t\t  ON a.AlarmRuleID = ar.AlarmRuleID \r\n\t\tWHERE \r\n\t\t  ar.[AlarmType] = 5\r\n\t\t    and\r\n      $__timeFilter(a.DateInserted)) amsg\r\n\t\tON amsg.MARCMsgID = msg.MsgID\r\nGROUP BY\r\n\tmsg.Alarm_Priority\r\nORDER BY \r\n\tCASE msg.Alarm_Priority\r\n\t\tWHEN 'Critical' THEN 1\r\n\t\tWHEN 'High' THEN 2\r\n\t\tWHEN 'Medium' THEN 3\r\n\t\tWHEN 'Low' THEN 4\r\n\t\tWHEN 'Very Low' THEN 5\r\n\tEND"
    }
   ]
  },
  {
   "title": "Alarms by Day",
   "type": "table",
   "gridPos": { "h": 9, "w": 15, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "select datename(dw,AlarmDate) as Day,AlarmDate, (ISNULL(New,0)+ISNULL(OpenAlarm,0)+ISNULL(Working,0)+ISNULL(Escalated,0)+ISNULL(AutoClosed,0)+ISNULL(FalsePositive,0)+ISNULL(Resolved,0)+ISNULL(UnResolved,0)+ISNULL(Reported,0)+ISNULL(Monitor,0)) as Total,\r\n(ISNULL(AutoClosed,0)+ISNULL(FalsePositive,0)+ISNULL(Resolved,0)+ISNULL(UnResolved,0)+ISNULL(Reported,0)+ISNULL(Monitor,0)) as Closed\r\nfrom\r\n(\r\nselect CONVERT(date, AlarmDate) as AlarmDate,count(AlarmName.Name) as AlarmCount,\r\n(Convert(nvarchar, Case\r\nWhen AlarmStatus = 0 Then 'New'\r\nWhen AlarmStatus = 1 Then 'OpenAlarm'\r\nWhen AlarmStatus = 2 Then 'Working'\r\nWhen AlarmStatus = 3 Then 'Escalated'\r\nWhen AlarmStatus = 4 Then 'AutoClosed'\r\nWhen AlarmStatus = 5 Then 'FalsePositive'\r\nWhen AlarmStatus = 6 Then 'Resolved'\r\nWhen AlarmStatus = 7 Then 'UnResolved'\r\nWhen AlarmStatus = 8 Then 'Reported'\r\nWhen AlarmStatus = 9 Then 'Monitor' End)) as AlarmStatus\r\nfrom [LogRhythm_Alarms].[dbo].[Alarm] as Alarm join LogRhythmEMDB.dbo.AlarmRule as AlarmName on Alarm.AlarmRuleID=AlarmName.AlarmRuleID\r\nwhere $__timeFilter(Alarm.AlarmDate)\r\ngroup by AlarmDate,AlarmStatus\r\n) d\r\npivot\r\n(\r\nsum(AlarmCount)\r\nfor AlarmStatus in (New,OpenAlarm,Working,Escalated,AutoClosed,FalsePositive,Resolved,UnResolved,Reported,Monitor)\r\n) piv"
    }
   ]
  },
  {
   "title": "Alarm Priority",
   "type": "table",
   "gridPos": { "h": 11, "w": 6, "x": 3, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\n  Priority,\n  COUNT(*) as Count\nFROM\n   (SELECT alm.[AlarmDate], alm.AlarmStatus,atm.MARCMsgID FROM [LogRhythm_Alarms].[dbo].[Alarm] alm JOIN [LogRhythm_Alarms].dbo.AlarmToMARCMsg atm ON alm.AlarmID = atm.AlarmID) almm\n\t\tJOIN\n\t(SELECT \n\t\tMsgID,\n\t\t(CASE WHEN Priority >= 90 THEN 'Critical' WHEN Priority BETWEEN 75 AND 89 THEN 'Very High' WHEN Priority BETWEEN 65 AND 74 THEN 'High' WHEN Priority BETWEEN 50 AND 64 THEN 'Medium' WHEN Priority < 50 THEN 'Low' END) AS Priority \n\tFROM LogRhythm_Events.dbo.Msg) emsg \n\t\t\tON emsg.MsgID = almm.MARCMsgID\n\tWHERE\n  $__timeFilter(almm.AlarmDate)\nGROUP BY\n  Priority\nORDER BY\n  CASE Priority\n    WHEN 'Critical' THEN 1\n    WHEN 'Very High' THEN 2\n    WHEN 'High' THEN 3\n    WHEN 'Medium' THEN 4\n    WHEN 'Low' THEN 5\n  END"
    }
   ]
  },
  {
   "title": "Alarms Table by Analyst Last Day",
   "type": "table",
   "gridPos": { "h": 11, "w": 15, "x": 9, "y": 9 },
   "targets": [
    {
     "rawSql": "select FullName,(Convert(nvarchar, Case\r\nWhen AlarmStatus = 0 Then 'New'\r\nWhen AlarmStatus = 1 Then 'OpenAlarm'\r\nWhen AlarmStatus = 2 Then 'Working'\r\nWhen AlarmStatus = 3 Then 'Escalated'\r\nWhen AlarmStatus = 4 Then 'AutoClosed'\r\nWhen AlarmStatus = 5 Then 'FalsePositive'\r\nWhen AlarmStatus = 6 Then 'Resolved'\r\nWhen AlarmStatus = 7 Then 'UnResolved'\r\nWhen AlarmStatus = 8 Then 'Reported'\r\nWhen AlarmStatus = 9 Then 'Monitor' End)) as AlarmStatus\r\n, count(AlarmStatus) as 'Count'\r\nfrom AlarmMetrics\r\njoin [LogRhythm_Alarms].[dbo].[Alarm] on Alarm.AlarmID=AlarmMetrics.AlarmID\r\njoin LogRhythmEMDB.dbo.AlarmRule on Alarm.AlarmRuleID=AlarmRule.AlarmRuleID\r\nleft join [LogRhythmEMDB].[dbo].[Person] on Person.PersonID=LastPersonID\r\nwhere Alarm.AlarmDate BETWEEN getdate()-7 AND  getdate()\r\ngroup by FullName,AlarmStatus"
    }
   ]
  },
  {
   "title": "Cases",
   "type": "stat",
   "gridPos": { "h": 15, "w": 3, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n count(*) as Count\nFROM\n  \t[LogRhythm_CMDB].[dbo].[Case] with (NOLOCK)\nWHERE\n  $__timeFilter([DateCreated])"
    }
   ]
  },
  {
   "title": "Cases",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 3, "y": 20 },
   "targets": [
    {
     "rawSql": "SELECT\n  cs.Name as [Case Status],\n  (CASE cs.IsClosedStatus when 1 then 'Closed' ELSE 'Open' END) as [Open_Closed],\n  COUNT(*) as Count\n FROM \n\tLogRhythm_CMDB.dbo.[Case] c with (NOLOCK) \n\t  join \n  LogRhythm_CMDB.dbo.CaseStatus cs\n\t\tON c.CaseStatusID = cs.CaseStatusID\nWHERE  $__timeFilter(c.DateCreated)\nGROUP BY\n  cs.Name,\n  cs.IsClosedStatus\nORDER BY\n  [Open_Closed] ASC"
    }
   ]
  },
  {
   "title": "All Cases KPI",
   "type": "bargauge",
   "gridPos": { "h": 16, "w": 3, "x": 9, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT [Owner], [Case Collaborators],  (SELECT DATEDIFF_BIG (ss, CAST([Date Earliest Evidence] as datetime), CAST([Date Created]as datetime))) TTD,  (SELECT DATEDIFF_BIG(ss, CAST([Date Incident] as datetime), CAST([Date Mitigated] as datetime))) TTR,  (SELECT DATEDIFF(minute, CAST([Date Earliest Evidence] as datetime),CAST([Date Created] as datetime))) TTQ,  (SELECT DATEDIFF(minute, CAST([Date Created] as datetime),CAST([Date Incident] as datetime))) TTI,  (SELECT DATEDIFF(minute, CAST([Date Incident] as datetime),CAST([Date Mitigated] as datetime))) TTM,  (SELECT DATEDIFF(minute, CAST([Date Created] as datetime),CAST([Date Mitigated] as datetime))) TTV FROM [LogRhythm_CMDB].[dbo].[vw_Cases]\nWHERE $__timeFilter([Date Created]) "
    }
   ]
  },
  {
   "title": "Cases By Analyst",
   "type": "table",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "select * from\r\n \r\n(\r\nSELECT p.FullName as \"Case Owner\",count(c.Name) as CaseCount,\r\n(Convert(nvarchar, Case\r\nWhen CaseStatusID = 1 Then 'Created'\r\nWhen CaseStatusID = 2 Then 'Completed'\r\nWhen CaseStatusID = 3 Then 'Incident'\r\nWhen CaseStatusID = 4 Then 'Mitigated'\r\nWhen CaseStatusID = 5 Then 'Resolved' End)) as CaseStatusID\r\n  FROM [LogRhythm_CMDB].[dbo].[Case] as c\r\n  left join [LogRhythmEMDB].[dbo].[Person] as p on p.PersonID=c.PersonID\r\nWHERE  $__timeFilter(c.DateCreated)\r\ngroup by p.FullName,CaseStatusID\r\n \r\n) d\r\npivot\r\n(\r\nsum(CaseCount)\r\nfor CaseStatusID in (Created,Completed,Incident,Mitigated,Resolved)\r\n) piv"
    }
   ]
  },
  {
   "title": "Cases",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 3, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "rawSql": "SELECT\n  [Priority],\n  AVG(DATEDIFF(MiNute,[DateEarliestEvidence],[DateCreated])) avgTTD,\n\tAVG(DATEDIFF(MiNute,[DateCreated],[DateClosed])) avgTTR,\n  COUNT(*) as Count\n FROM \n\tLogRhythm_CMDB.dbo.[Case] with (NOLOCK)\nWHERE  $__timeFilter([DateCreated])\nGROUP BY\n  [Priority]\nORDER BY\n  [Priority] ASC"
    }
   ]
  }
 ]
}