{
 "title": "2025: Case Details",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Cases KPI",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT (SELECT DATEDIFF_BIG (ss, CAST([Date Earliest Evidence] as datetime), CAST([Date Created]as datetime))) TTD,  (SELECT DATEDIFF_BIG(ss, CAST([Date Incident] as datetime), CAST([Date Mitigated] as datetime))) TTR,  (SELECT DATEDIFF(minute, CAST([Date Earliest Evidence] as datetime),CAST([Date Created] as datetime))) TTQ,  (SELECT DATEDIFF(minute, CAST([Date Created] as datetime),CAST([Date Incident] as datetime))) TTI,  (SELECT DATEDIFF(minute, CAST([Date Incident] as datetime),CAST([Date Mitigated] as datetime))) TTM,  (SELECT DATEDIFF(minute, CAST([Date Created] as datetime),CAST([Date Mitigated] as datetime))) TTV FROM [LogRhythm_CMDB].[dbo].[vw_Cases]\nWHERE $__timeFilter([Date Created]) "
    }
   ]
  },
  {
   "title": "P1 & P2 Cases",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "rawSql": "SELECT \n    [Case Priority],  \n    AVG(DATEDIFF_BIG(ss, CAST([Date Earliest Evidence] AS datetime), CAST([Date Created] AS datetime))) AS TTD,  \n    AVG(DATEDIFF_BIG(ss, CAST([Date Incident] AS datetime), CAST([Date Mitigated] AS datetime))) AS TTR,  \n    AVG(DATEDIFF(minute, CAST([Date Earliest Evidence] AS datetime), CAST([Date Created] AS datetime))) AS TTQ,  \n    AVG(DATEDIFF(minute, CAST([Date Created] AS datetime), CAST([Date Incident] AS datetime))) AS TTI,  \n    AVG(DATEDIFF(minute, CAST([Date Incident] AS datetime), CAST([Date Mitigated] AS datetime))) AS TTM,  \n    AVG(DATEDIFF(minute, CAST([Date Created] AS datetime), CAST([Date Mitigated] AS datetime))) AS TTV\nFROM \n    [LogRhythm_CMDB].[dbo].[vw_Cases]\nWHERE \n    $__timeFilter([Date Created]) \n    AND ([Case Priority] = 1 OR [Case Priority] = 2)\nGROUP BY \n    [Case Priority];\n"
    }
   ]
  },
  {
   "title": "Cases Details 1",
   "type": "table",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT [CaseNumber], [Case Name], [Case Status] AS Status, [Owner], [Case Collaborators] AS Collaborator,  (SELECT DATEDIFF_BIG (ss, CAST([Date Earliest Evidence] as datetime), CAST([Date Created]as datetime))) TTD,  \r\n(SELECT DATEDIFF_BIG(ss, CAST([Date Incident] as datetime), CAST([Date Mitigated] as datetime))) TTR,  (SELECT DATEDIFF(minute, CAST([Date Earliest Evidence] as datetime),CAST([Date Created] as datetime))) TTQ,  \r\n(SELECT DATEDIFF(minute, CAST([Date Created] as datetime),CAST([Date Incident] as datetime))) TTI,  (SELECT DATEDIFF(minute, CAST([Date Incident] as datetime),CAST([Date Mitigated] as datetime))) TTM,  \r\n(SELECT DATEDIFF(minute, CAST([Date Created] as datetime),CAST([Date Mitigated] as datetime))) TTV FROM [LogRhythm_CMDB].[dbo].[vw_Cases]\r\nWHERE $__timeFilter([Date Created])\r\nORDER BY\r\n  [CaseNumber] DESC"
    }
   ]
  },
  {
   "title": "Cases Details ",
   "type": "table-old",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "rawSql": "\r\n\r\nSELECT TOP 1000 [CaseNumber], [Case Name],  [Case Resolution] AS Resolution,  [Case Priority] AS Priority,  [Case Status] AS Status, (SELECT DATEDIFF_BIG (ss, CAST([Date Earliest Evidence] as datetime), CAST([Date Created]as datetime))) TTD,  \r\n(SELECT DATEDIFF_BIG(ss, CAST([Date Incident] as datetime), CAST([Date Mitigated] as datetime))) TTR,  (SELECT DATEDIFF(minute, CAST([Date Earliest Evidence] as datetime),CAST([Date Created] as datetime))) TTQ,  \r\n(SELECT DATEDIFF(minute, CAST([Date Created] as datetime),CAST([Date Incident] as datetime))) TTI,  (SELECT DATEDIFF(minute, CAST([Date Incident] as datetime),CAST([Date Mitigated] as datetime))) TTM,  \r\n(SELECT DATEDIFF(minute, CAST([Date Created] as datetime),CAST([Date Mitigated] as datetime))) TTV FROM [LogRhythm_CMDB].[dbo].[vw_Cases]\r\nWHERE $__timeFilter([Date Created]) \r\nORDER BY\r\n  [CaseNumber] DESC"
    }
   ]
  },
  {
   "title": "Cases Details  Table",
   "type": "table",
   "gridPos": { "h": 24, "w": 24, "x": 0, "y": 50 },
   "targets": [
    {
     "rawSql": "\r\nSELECT  [CaseNumber],   [Case Name],  [Case Resolution] AS Resolution,  [Case Priority] AS Priority,  [Case Status] AS Status,  [Case Tags], [Owner], [Case Collaborators] AS Collaborator,  [Evidence Logs Count] AS Logs,  [Evidence Files Count] AS Files,  [Evidence Alarms Count] AS Alarms,  \r\n[Evidence Notes Count] AS Notes FROM [LogRhythm_CMDB].[dbo].[vw_Cases]\r\nWHERE $__timeFilter([Date Created])\r\nORDER BY\r\n  [CaseNumber] DESC"
    }
   ]
  }
 ]
}