{
 "title": "2025: Alarms Report 1",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Total Alarms",
   "type": "stat",
   "gridPos": { "h": 15, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n\tcount(*) as Count\nFROM\n  \tLogRhythm_Alarms.dbo.Alarm a with (NOLOCK)\n  \t  JOIN\n\t  LogRhythmEMDB.dbo.AlarmRule ar\n\t    ON a.AlarmRuleID = ar.AlarmRuleID\nWHERE\n  $__timeFilter(DateInserted)"
    }
   ]
  },
  {
   "title": "Alarm Priority",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 4, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  Priority,\n  COUNT(*) as Count\nFROM\n   (SELECT alm.[AlarmDate], alm.AlarmStatus,atm.MARCMsgID FROM [LogRhythm_Alarms].[dbo].[Alarm] alm JOIN [LogRhythm_Alarms].dbo.AlarmToMARCMsg atm ON alm.AlarmID = atm.AlarmID) almm\n\t\tJOIN\n\t(SELECT \n\t\tMsgID,\n\t\t(CASE WHEN Priority >= 90 THEN 'Critical' WHEN Priority BETWEEN 75 AND 89 THEN 'Very High' WHEN Priority BETWEEN 65 AND 74 THEN 'High' WHEN Priority BETWEEN 50 AND 64 THEN 'Medium' WHEN Priority < 50 THEN 'Low' END) AS Priority \n\tFROM LogRhythm_Events.dbo.Msg) emsg \n\t\t\tON emsg.MsgID = almm.MARCMsgID\n\tWHERE\n  $__timeFilter(almm.AlarmDate)\nGROUP BY\n  Priority\nORDER BY\n  CASE Priority\n    WHEN 'Critical' THEN 1\n    WHEN 'Very High' THEN 2\n    WHEN 'High' THEN 3\n    WHEN 'Medium' THEN 4\n    WHEN 'Low' THEN 5\n  END"
    }
   ]
  },
  {
   "title": "Alarms Table by Analyst",
   "type": "table",
   "gridPos": { "h": 15, "w": 14, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "select FullName,(Convert(nvarchar, Case\r\nWhen AlarmStatus = 0 Then 'New'\r\nWhen AlarmStatus = 1 Then 'OpenAlarm'\r\nWhen AlarmStatus = 2 Then 'Working'\r\nWhen AlarmStatus = 3 Then 'Escalated'\r\nWhen AlarmStatus = 4 Then 'AutoClosed'\r\nWhen AlarmStatus = 5 Then 'FalsePositive'\r\nWhen AlarmStatus = 6 Then 'Resolved'\r\nWhen AlarmStatus = 7 Then 'UnResolved'\r\nWhen AlarmStatus = 8 Then 'Reported'\r\nWhen AlarmStatus = 9 Then 'Monitor' End)) as AlarmStatus\r\n, count(AlarmStatus) as 'Count'\r\nfrom AlarmMetrics\r\njoin [LogRhythm_Alarms].[dbo].[Alarm] on Alarm.AlarmID=AlarmMetrics.AlarmID\r\njoin LogRhythmEMDB.dbo.AlarmRule on Alarm.AlarmRuleID=AlarmRule.AlarmRuleID\r\nleft join [LogRhythmEMDB].[dbo].[Person] on Person.PersonID=LastPersonID\r\nwhere $__timeFilter(Alarm.AlarmDate)\r\ngroup by FullName,AlarmStatus"
    }
   ]
  },
  {
   "title": "Alarms",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 6, "x": 4, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\r\n\tmsg.Alarm_Priority,\r\n\tAVG(amsg.TTD) avgTTD,\r\n\tAVG(amsg.TTR) avgTTR,\r\n\tCOUNT(*) as Count\r\nFROM\r\n  (SELECT\r\n\tCASE \r\n\t\tWHEN Priority >= 90 THEN 'Critical'\r\n\t\tWHEN Priority BETWEEN 80 and 89 THEN 'High'\r\n\t\tWHEN Priority BETWEEN 65 and 79 THEN 'Medium'\r\n\t\tWHEN Priority BETWEEN 50 and 64 THEN 'Low'\r\n\t\tWHEN Priority < 50 THEN 'Very Low'\r\n\tEND AS Alarm_Priority,\r\n\tMsgID\r\nFROM \r\n\tLogRhythm_Events.dbo.Msg with (NOLOCK)) msg\r\n\t  JOIN\r\n\t(SELECT \r\n\t\ta.DateInserted,\r\n\t\tatm.MARCMsgID,\r\n\t\ta.AlarmID,\r\n\t\tDATEDIFF(MINUTE,am.GeneratedOn,am.OpenedOn) TTT,\r\n\t\tDATEDIFF(MINUTE,am.GeneratedOn,am.InvestigatedOn) TTD,\r\n\t\tDATEDIFF(MINUTE,am.InvestigatedOn,am.ClosedOn) TTR\r\n\tFROM \r\n\t\tLogRhythm_Alarms.dbo.Alarm a with (NOLOCK) \r\n\t\t\tJOIN \r\n\t\tLogRhythm_Alarms.dbo.AlarmToMARCMsg atm with (NOLOCK) \r\n\t\t\tON a.AlarmID = atm.AlarmID\r\n\t\t\tJOIN\r\n\t\t[LogRhythm_Alarms].[dbo].[AlarmMetrics] am with (NOLOCK) \r\n\t\t\tON a.AlarmID = am.AlarmID\r\n\t\t\tJOIN\r\n\t\t[LogRhythmEMDB].[dbo].AlarmRule ar\r\n\t\t  ON a.AlarmRuleID = ar.AlarmRuleID \r\n\t\tWHERE \r\n\t\t  ar.[AlarmType] = 5\r\n\t\t    and\r\n      $__timeFilter(a.DateInserted)) amsg\r\n\t\tON amsg.MARCMsgID = msg.MsgID\r\nGROUP BY\r\n\tmsg.Alarm_Priority\r\nORDER BY \r\n\tCASE msg.Alarm_Priority\r\n\t\tWHEN 'Critical' THEN 1\r\n\t\tWHEN 'High' THEN 2\r\n\t\tWHEN 'Medium' THEN 3\r\n\t\tWHEN 'Low' THEN 4\r\n\t\tWHEN 'Very Low' THEN 5\r\n\tEND"
    }
   ]
  },
  {
   "title": "Alarms",
   "type": "table",
   "gridPos": { "h": 21, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "select Name, (ISNULL(AutoClosed,0)+ISNULL(New,0)+ISNULL(OpenAlarm,0)+ISNULL(Reported,0)+ISNULL(Resolved,0)+ISNULL(FalsePositive,0)+ISNULL(Monitor,0)) as Total,ISNULL(New,0) as New,ISNULL(OpenAlarm,0) as 'Open',ISNULL(Reported,0) as Reported,ISNULL(Resolved,0) as Resolved,ISNULL(FalsePositive,0) as 'False Positive',ISNULL(Monitor,0) as Monitor,ISNULL(AutoClosed, 0 )as 'Auto Closed'\r\nfrom\r\n(\r\nselect AlarmName.Name,count(AlarmName.Name) as AlarmCount,\r\n(Convert(nvarchar, Case When AlarmStatus = 4 Then 'AutoClosed' When AlarmStatus = 8 Then 'Reported' When AlarmStatus = 6 Then 'Resolved' When AlarmStatus = 5 Then 'FalsePositive' When AlarmStatus = 0 Then 'New' When AlarmStatus = 1 Then 'OpenAlarm' when AlarmStatus = 9 Then 'Monitor' End)) as AlarmStatus\r\nfrom [LogRhythm_Alarms].[dbo].[Alarm] as Alarm join LogRhythmEMDB.dbo.AlarmRule as AlarmName on Alarm.AlarmRuleID=AlarmName.AlarmRuleID\r\nwhere $__timeFilter(Alarm.AlarmDate)\r\ngroup by AlarmName.Name,AlarmStatus\r\n ) d\r\npivot\r\n(\r\n  max(AlarmCount)\r\n  for AlarmStatus in (AutoClosed,New,Reported,Resolved,FalsePositive,OpenAlarm,Monitor)\r\n) piv"
    }
   ]
  }
 ]
}