{
 "title": "2025: Log Sources Report 3",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Messages Per Second",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "USE [LogRhythm_LogMart];\r\nSELECT\r\n  [Avg MPS] = CAST(SUM(CAST(CountProcessedLogs as BIGINT)) AS real) / CAST(DATEDIFF(ss,$__timeFrom(),$__timeTo()) as BIGINT),\r\n\t[Max MPS] = CAST(MAX(CountProcessedLogs) AS float) / 60.0\r\nFROM\r\n\t[dbo].StatsDeploymentCountsMinute with (NOLOCK)\r\nWHERE  $__timeFilter(StatDate);"
    }
   ]
  },
  {
   "title": "Total Log Sources",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(*) as Count\nFROM\n  LogRhythmEMDB.dbo.MsgSource with (NOLOCK)\nWHERE\n  RecordStatus = 1 AND Name NOT LIKE 'AI Engine%'"
    }
   ]
  },
  {
   "title": "Devices Not Reporting for 1+ Day",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "Use LogRhythmEMDB\r\nselect Count(*) as \"Log Sources\"\r\nfrom MsgSource a join MsgSourceMaxLogDate as b on a.MsgSourceID=b.MsgSourceID\r\n\r\nwhere a.MsgSourceID>0 and a.RecordStatus=1 and b.MaxLogDate > GetDate() - 100\r\nand b.MaxLogDate < DATEADD(minute, -1440, GETDATE()) "
    }
   ]
  },
  {
   "title": "Avg Log Size",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Average Log Size Bytes",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mediator.processing",
     "select": [
      [
       { "params": [ "Average_Log_Size_Bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=", "value": "LR-XM-Primary" }
     ]
    }
   ]
  },
  {
   "title": "User Experience Table",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "Select TOP 10000 WT.TaskName, WT.LongResults, WT.ShortResults, WT.NumResults, datediff(minute,WT.DateCreated,WT.DateUpdated) QueryTime, U.Login from WebTask WT Inner Join WebSearch WS ON WS.WebSearchID = WT.WebSearchId INNER JOIN WebTaskToUser WTU On WTU.WebTaskId = WT.TaskID Inner JOin SCUser U On U.UserID = WTU.UserId"
    }
   ]
  },
  {
   "title": "Logs - Events - Alarms",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "select \r\n  $__timeGroup(StatDate, '1d') AS time,\r\n  [Logs] = SUM(cast(CountProcessedLogs as bigint)),\r\n  [Events] = SUM(cast(CountEventsForwarded as bigint)),\r\n  [Alarms] = SUM(cast(CountAlarms as bigint))\r\nfrom \r\n  LogRhythm_LogMart.dbo.StatsDeploymentCountsHour with (NOLOCK)\r\nWHERE \r\n  $__timeFilter(StatDate)\r\ngroup by \r\n   $__timeGroup(StatDate, '1d');"
    }
   ]
  },
  {
   "title": "MPS Per Entity",
   "type": "table",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 13 },
   "targets": [
    {
     "rawSql": "WITH EntityMPS AS (\r\n    SELECT \r\n        h.EntityID,\r\n        ROUND(MAX(CAST(s.CountLogs AS FLOAT) / 60), 2) AS Max_MPS,\r\n        ROUND(AVG(CAST(s.CountLogs AS FLOAT) / 60), 2) AS Avg_MPS\r\n    FROM [LogRhythmEMDB].[dbo].MsgSource ms\r\n    INNER JOIN [LogRhythmEMDB].[dbo].Host h ON ms.HostID = h.HostID\r\n    INNER JOIN [LogRhythmEMDB].[dbo].MsgSourceMaxLogDate mld ON ms.MsgSourceID = mld.MsgSourceID\r\n    INNER JOIN [LogRhythm_LogMart].[dbo].[StatsMsgSourceCountsMinute] s ON ms.MsgSourceID = s.MsgSourceID\r\n    WHERE ms.MsgSourceID > 0 AND ms.RecordStatus = 1\r\n    GROUP BY h.EntityID\r\n),\r\nLogSourceCounts AS (\r\n    SELECT \r\n        h.EntityID,\r\n        COUNT(ms.MsgSourceID) AS LogSourceCount\r\n    FROM [LogRhythmEMDB].[dbo].MsgSource ms\r\n    INNER JOIN [LogRhythmEMDB].[dbo].Host h ON ms.HostID = h.HostID\r\n    WHERE ms.MsgSourceID > 0 AND ms.RecordStatus = 1\r\n    GROUP BY h.EntityID\r\n)\r\nSELECT \r\n    e.FullName AS 'Entity',\r\n    em.Max_MPS,\r\n    em.Avg_MPS,\r\n    lsc.LogSourceCount AS 'Total LogSource'\r\nFROM EntityMPS em\r\nINNER JOIN [LogRhythmEMDB].[dbo].[Entity] e ON e.EntityID = em.EntityID\r\nINNER JOIN LogSourceCounts lsc ON lsc.EntityID = em.EntityID\r\nORDER BY e.FullName;\r\n"
    }
   ]
  },
  {
   "title": "MPE Per Entity",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 15, "x": 9, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "WITH EntityMPS AS (\r\n    SELECT \r\n        h.EntityID,\r\n        ROUND(MAX(CAST(s.CountLogs AS FLOAT) / 60), 2) AS Max_MPS,\r\n        ROUND(AVG(CAST(s.CountLogs AS FLOAT) / 60), 2) AS Avg_MPS\r\n    FROM [LogRhythmEMDB].[dbo].MsgSource ms\r\n    INNER JOIN [LogRhythmEMDB].[dbo].Host h ON ms.HostID = h.HostID\r\n    INNER JOIN [LogRhythmEMDB].[dbo].MsgSourceMaxLogDate mld ON ms.MsgSourceID = mld.MsgSourceID\r\n    INNER JOIN [LogRhythm_LogMart].[dbo].[StatsMsgSourceCountsMinute] s ON ms.MsgSourceID = s.MsgSourceID\r\n    WHERE ms.MsgSourceID > 0 AND ms.RecordStatus = 1\r\n    GROUP BY h.EntityID\r\n),\r\nLogSourceCounts AS (\r\n    SELECT \r\n        h.EntityID,\r\n        COUNT(ms.MsgSourceID) AS LogSourceCount\r\n    FROM [LogRhythmEMDB].[dbo].MsgSource ms\r\n    INNER JOIN [LogRhythmEMDB].[dbo].Host h ON ms.HostID = h.HostID\r\n    WHERE ms.MsgSourceID > 0 AND ms.RecordStatus = 1\r\n    GROUP BY h.EntityID\r\n)\r\nSELECT \r\n    e.FullName AS 'Entity',\r\n    em.Max_MPS,\r\n    em.Avg_MPS,\r\n    lsc.LogSourceCount AS 'Total LogSource'\r\nFROM EntityMPS em\r\nINNER JOIN [LogRhythmEMDB].[dbo].[Entity] e ON e.EntityID = em.EntityID\r\nINNER JOIN LogSourceCounts lsc ON lsc.EntityID = em.EntityID\r\nORDER BY e.FullName;\r\n"
    }
   ]
  },
  {
   "title": "Log Sources Report",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "select c.Name as 'Host',a.Name as 'Log Source',(select top(1) DateAssigned from HostIdentifier where HostID=a.HostID) as 'Host Created Date',a.DateUpdated as 'Updated Date',\r\nMaxLogDate as 'Last Log Message',\r\n(SELECT max(CountLogs/60)  FROM [LogRhythm_LogMart].[dbo].[StatsMsgSourceCountsMinute]  where MsgSourceID=a.MsgSourceID) as 'Max MPS',  (SELECT avg(countlogs/60)  FROM [LogRhythm_LogMart].[dbo].[StatsMsgSourceCountsMinute]    where MsgSourceID=a.MsgSourceID) as 'Avg MPS'\r\nfrom MsgSource a\r\njoin MsgSourceMaxLogDate as b on a.MsgSourceID=b.MsgSourceID\r\njoin Host as c on c.HostID=a.HostID\r\nwhere a.MsgSourceID>0 and a.RecordStatus=1\r\n--and a.MsgSourceID=18\r\norder by 'Max MPS' DESC"
    }
   ]
  },
  {
   "title": "Host Report",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    c.Name AS 'Host', \r\n    (SELECT TOP 1 DateAssigned FROM HostIdentifier WHERE HostID = c.HostID ORDER BY DateAssigned ASC) AS 'Host Created Date',\r\n    MAX(a.DateUpdated) AS 'Updated Date',\r\n    MAX(b.MaxLogDate) AS 'Last Log Message',\r\n    (SELECT MAX(CountLogs / 60)  \r\n     FROM [LogRhythm_LogMart].[dbo].[StatsMsgSourceCountsMinute]  \r\n     WHERE MsgSourceID IN (SELECT MsgSourceID FROM MsgSource WHERE HostID = c.HostID)) AS 'Max MPS',\r\n    (SELECT AVG(CountLogs / 60)  \r\n     FROM [LogRhythm_LogMart].[dbo].[StatsMsgSourceCountsMinute]  \r\n     WHERE MsgSourceID IN (SELECT MsgSourceID FROM MsgSource WHERE HostID = c.HostID)) AS 'Avg MPS'\r\nFROM MsgSource a\r\nJOIN MsgSourceMaxLogDate b ON a.MsgSourceID = b.MsgSourceID\r\nJOIN Host c ON c.HostID = a.HostID\r\nWHERE a.MsgSourceID > 0 AND a.RecordStatus = 1\r\nGROUP BY c.Name, c.HostID\r\nORDER BY 'Max MPS' DESC;\r\n"
    }
   ]
  }
 ]
}