{
 "title": "2025: Customer Created Dashboard 01",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<a>\n  <div style=\"display: flex; flex-direction: column; justify-content: center; align-items: center; width: 100%; height: 100%; cursor: pointer; background-color: #f0f0f0; background-image: url('background-image-url.jpg'); background-size: cover; background-position: center;\">\n    <img src=\"https://www.cdg.ma/themes/cdg/asset/img/logo_hp.png\" style=\"max-width: 80%; max-height: 80%; display: block; margin: auto;\">\n  </div>\n</a>\n"
   }
  },
  {
   "title": "SLA des Cases par TTD & TTR",
   "type": "table",
   "gridPos": { "h": 28, "w": 15, "x": 0, "y": 3 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  c.[CaseNumber] AS CaseID,                                   -- Identifiant unique pour chaque case\r\n  c.[Name] AS Case_Name,                                      -- Nom du case\r\n  c.[Priority],                                               -- Priorité de l'incident\r\n  p.FullName AS Case_Owner,                                   -- Propriétaire du case (analyste)\r\n  e.Name AS Entity_Name,                                      -- Nom de l'entité liée\r\n  DATEDIFF(MINUTE, c.[DateEarliestEvidence], c.[DateCreated]) AS TTD,  -- Temps écoulé avant détection\r\n  DATEDIFF(MINUTE, c.[DateCreated], c.[DateClosed]) AS TTR            -- Temps écoulé avant clôture\r\nFROM \r\n  LogRhythm_CMDB.dbo.[Case] AS c WITH (NOLOCK)\r\nLEFT JOIN \r\n  LogRhythmEMDB.dbo.[Person] AS p ON p.PersonID = c.PersonID   -- Joindre la table Person pour obtenir le propriétaire\r\nLEFT JOIN \r\n  LogRhythmEMDB.dbo.[Entity] AS e ON c.EntityID = e.EntityID   -- Joindre la table Entity pour obtenir le nom de l'entité\r\nWHERE  \r\n  $__timeFilter(c.[DateCreated])                               -- Filtre temporel pour les incidents créés dans une certaine période\r\nORDER BY\r\n  TTD DESC;                                                   -- Tri par temps de détection (TTD) décroissant\r\n"
    }
   ]
  },
  {
   "title": "Mean Time to Detect & Mean Time to Resolve",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  AVG(DATEDIFF(MINUTE, [DateEarliestEvidence], [DateCreated])) AS MTTD,\n  AVG(DATEDIFF(MINUTE, [DateCreated], [DateClosed])) AS MTTR\nFROM \n  LogRhythm_CMDB.dbo.[Case] WITH (NOLOCK)\nWHERE  \n  $__timeFilter([DateCreated]) \n\n"
    }
   ]
  },
  {
   "title": "Avg TTD & TTR by Analyst",
   "type": "table",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  p.FullName AS \"Analyste\",                                         -- Propriétaire du case (analyste)\r\n  COUNT(c.CaseNumber) AS \"Total Cases\",                               -- Total des cases traités par chaque propriétaire\r\n  AVG(DATEDIFF(MINUTE, [DateEarliestEvidence], [DateCreated])) AS 'Avg Time to Detect',  -- Moyenne du temps avant détection (TTD)\r\n  AVG(DATEDIFF(MINUTE, [DateCreated], [DateClosed])) AS 'Avg Time to Resolve'     -- Moyenne du temps avant résolution (TTR)\r\n  \r\nFROM \r\n  LogRhythm_CMDB.dbo.[Case] AS c WITH (NOLOCK)\r\nLEFT JOIN \r\n  LogRhythmEMDB.dbo.[Person] AS p ON p.PersonID = c.PersonID        -- Joindre la table Person pour obtenir le propriétaire\r\nWHERE  \r\n  $__timeFilter([DateCreated])                                      -- Filtre temporel pour les incidents créés dans une certaine période\r\nGROUP BY \r\n  p.FullName                                                       -- Groupement par propriétaire de case (analyste)\r\nORDER BY \r\n  \"Total Cases\" DESC;                                                 -- Tri par nombre total de cases traités\r\n"
    }
   ]
  },
  {
   "title": "Avg TTD & TTR by Priority",
   "type": "table",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 20 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  [Priority],                                                   -- Priorité de l'incident\r\n  COUNT(c.CaseNumber) AS \"Total Cases\",                           -- Total des cases traités pour chaque priorité\r\n  AVG(DATEDIFF(MINUTE, [DateEarliestEvidence], [DateCreated])) AS 'Avg Time to Detect',  -- Moyenne du temps avant détection (TTD)\r\n  AVG(DATEDIFF(MINUTE, [DateCreated], [DateClosed])) AS 'Avg Time to Resolve'  -- Moyenne du temps avant résolution (TTR)\r\n  \r\nFROM \r\n  LogRhythm_CMDB.dbo.[Case] AS c WITH (NOLOCK)\r\nLEFT JOIN \r\n  LogRhythmEMDB.dbo.[Person] AS p ON p.PersonID = c.PersonID    -- Joindre la table Person pour obtenir le propriétaire\r\nWHERE  \r\n  $__timeFilter([DateCreated])                                  -- Filtre temporel pour les incidents créés dans une certaine période\r\nGROUP BY \r\n  [Priority]                                                    -- Groupement par priorité\r\nORDER BY \r\n  Priority DESC;                                             -- Tri par priorité\r\n"
    }
   ]
  }
 ]
}