{
 "title": "2025: Custom Report by Customer 1",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Use Cases",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "aie",
     "select": [
      [
       { "params": [ "#_of_Enabled_Rules" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Alarms",
   "type": "table",
   "gridPos": { "h": 8, "w": 14, "x": 5, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n\tmsg.Alarm_Priority,\r\n\tAVG(amsg.TTD) avgTTD,\r\n\tAVG(amsg.TTR) avgTTR,\r\n\tCOUNT(*) as Count\r\nFROM\r\n  (SELECT\r\n\tCASE \r\n\t\tWHEN Priority >= 90 THEN 'Critical'\r\n\t\tWHEN Priority BETWEEN 80 and 89 THEN 'High'\r\n\t\tWHEN Priority BETWEEN 65 and 79 THEN 'Medium'\r\n\t\tWHEN Priority BETWEEN 50 and 64 THEN 'Low'\r\n\t\tWHEN Priority < 50 THEN 'Very Low'\r\n\tEND AS Alarm_Priority,\r\n\tMsgID\r\nFROM \r\n\tLogRhythm_Events.dbo.Msg with (NOLOCK)) msg\r\n\t  JOIN\r\n\t(SELECT \r\n\t\ta.DateInserted,\r\n\t\tatm.MARCMsgID,\r\n\t\ta.AlarmID,\r\n\t\tDATEDIFF(MINUTE,am.GeneratedOn,am.OpenedOn) TTT,\r\n\t\tDATEDIFF(MINUTE,am.GeneratedOn,am.InvestigatedOn) TTD,\r\n\t\tDATEDIFF(MINUTE,am.InvestigatedOn,am.ClosedOn) TTR\r\n\tFROM \r\n\t\tLogRhythm_Alarms.dbo.Alarm a with (NOLOCK) \r\n\t\t\tJOIN \r\n\t\tLogRhythm_Alarms.dbo.AlarmToMARCMsg atm with (NOLOCK) \r\n\t\t\tON a.AlarmID = atm.AlarmID\r\n\t\t\tJOIN\r\n\t\t[LogRhythm_Alarms].[dbo].[AlarmMetrics] am with (NOLOCK) \r\n\t\t\tON a.AlarmID = am.AlarmID\r\n\t\t\tJOIN\r\n\t\t[LogRhythmEMDB].[dbo].AlarmRule ar\r\n\t\t  ON a.AlarmRuleID = ar.AlarmRuleID \r\n\t\tWHERE \r\n\t\t  ar.[AlarmType] = 5\r\n\t\t    and\r\n      $__timeFilter(a.DateInserted)) amsg\r\n\t\tON amsg.MARCMsgID = msg.MsgID\r\nGROUP BY\r\n\tmsg.Alarm_Priority\r\nORDER BY \r\n\tCASE msg.Alarm_Priority\r\n\t\tWHEN 'Critical' THEN 1\r\n\t\tWHEN 'High' THEN 2\r\n\t\tWHEN 'Medium' THEN 3\r\n\t\tWHEN 'Low' THEN 4\r\n\t\tWHEN 'Very Low' THEN 5\r\n\tEND"
    }
   ]
  },
  {
   "title": "Alarms",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n\tcount(*) as Count\nFROM\n  \tLogRhythm_Alarms.dbo.Alarm a with (NOLOCK)\n  \t  JOIN\n\t  LogRhythmEMDB.dbo.AlarmRule ar\n\t    ON a.AlarmRuleID = ar.AlarmRuleID\nWHERE\n  ar.AlarmType = 5\n    AND\n  $__timeFilter(DateInserted)"
    }
   ]
  },
  {
   "title": "Alarms By Analyst",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "select b.Technician,b.[UnAssigned Alarms],b.[Opened Alarms],b.[Closed Alarms],b.Total,a.[Avg Time to Triage],a.[AVG Time to Close],a.[AVG Time to Investigate],a.[Avg Alarms Risk]\r\nfrom (select FullName as Technician,avg(DATEDIFF(minute,GeneratedOn,OpenedOn)) as 'Avg Time to Triage', avg(DATEDIFF(minute,GeneratedOn,ClosedOn)) as 'AVG Time to Close', avg(DATEDIFF(minute,GeneratedOn,InvestigatedOn)) as 'AVG Time to Investigate'\r\n,avg(m.Priority) as  'Avg Alarms Risk',count(*) as 'Total'\r\nfrom [LogRhythm_Alarms].[dbo].AlarmMetrics\r\njoin [LogRhythm_Alarms].[dbo].[Alarm] as a on a.AlarmID=AlarmMetrics.AlarmID\r\njoin LogRhythmEMDB.dbo.AlarmRule on a.AlarmRuleID=AlarmRule.AlarmRuleID\r\nleft join [LogRhythmEMDB].[dbo].[Person] as p on p.PersonID=LastPersonID\r\nleft join [LogRhythm_Alarms].[dbo].[AlarmToMARCMsg] as am on a.AlarmID=am.AlarmID\r\nleft join [LogRhythm_Events].[dbo].[Msg] as m on am.MARCMsgID=m.MsgID\r\nwhere  $__timeFilter(AlarmDate) and p.PersonID is not null\r\ngroup by FullName) as a\r\nfull outer join\r\n(select *,isnull(\"UnAssigned Alarms\",0)+isnull(\"Opened Alarms\",0)+isnull(\"Closed Alarms\",0) as \"Total\"\r\nfrom\r\n(\r\nselect FullName as Technician, (Convert(nvarchar, Case\r\nWhen AlarmStatus = 0 Then 'UnAssigned Alarms'\r\nWhen AlarmStatus = 1 Then 'Opened Alarms'\r\nWhen AlarmStatus = 2 Then 'Opened Alarms'\r\nWhen AlarmStatus = 3 Then 'Opened Alarms'\r\nWhen AlarmStatus = 4 Then 'Closed Alarms'\r\nWhen AlarmStatus = 5 Then 'Closed Alarms'\r\nWhen AlarmStatus = 6 Then 'Closed Alarms'\r\nWhen AlarmStatus = 7 Then 'Closed Alarms'\r\nWhen AlarmStatus = 8 Then 'Closed Alarms'\r\nWhen AlarmStatus = 9 Then 'Closed Alarms' End)) as AlarmStatus, count(AlarmStatus) as 'Total'\r\nfrom [LogRhythm_Alarms].[dbo].AlarmMetrics\r\njoin [LogRhythm_Alarms].[dbo].[Alarm] as a on a.AlarmID=AlarmMetrics.AlarmID\r\njoin LogRhythmEMDB.dbo.AlarmRule on a.AlarmRuleID=AlarmRule.AlarmRuleID\r\nleft join [LogRhythmEMDB].[dbo].[Person] on Person.PersonID=LastPersonID\r\nleft join [LogRhythm_Alarms].[dbo].[AlarmToMARCMsg] as am on a.AlarmID=am.AlarmID\r\nleft join [LogRhythm_Events].[dbo].[Msg] as m on am.MARCMsgID=m.MsgID\r\nwhere  $__timeFilter(AlarmDate)\r\ngroup by FullName,AlarmStatus\r\n) d\r\npivot\r\n(\r\nsum(Total)\r\nfor AlarmStatus in (\"UnAssigned Alarms\",\"Opened Alarms\",\"Closed Alarms\")\r\n) piv) as b on a.Technician=b.Technician\r\norder by a.Technician\r\n"
    }
   ]
  },
  {
   "title": "Cases by Analyst",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "rawSql": "select a.*,b.[Avg Time to Detect] as 'avg TTD',b.[Avg Time to Respond] as 'avg TTR',b.[Avg Time to Qualify] as 'avg TTQ',b.[Avg Time to Investigate] as 'avg TTI',b.[Avg Time to Mitigate] as 'avg TTM',b.[Avg Time to Recover] as 'avg TTV' from\r\n(select *, (isnull(Created,0)+isnull(Completed,0)+isnull(Incident,0)+isnull(Mitigated,0)+isnull(Resolved,0)) as 'Total Cases' from\r\n(\r\nSELECT p.FullName as \"Case Owner\",count(c.Name) as CaseCount,\r\n(Convert(nvarchar, Case\r\nWhen CaseStatusID = 1 Then 'Created'\r\nWhen CaseStatusID = 2 Then 'Completed'\r\nWhen CaseStatusID = 3 Then 'Incident'\r\nWhen CaseStatusID = 4 Then 'Mitigated'\r\nWhen CaseStatusID = 5 Then 'Resolved' End)) as CaseStatusID\r\n  FROM [LogRhythm_CMDB].[dbo].[Case] as c\r\n  left join [LogRhythmEMDB].[dbo].[Person] as p on p.PersonID=c.PersonID\r\n  where  DateCreated between getdate()-30 and getdate() and p.PersonID is not null\r\ngroup by p.FullName,CaseStatusID\r\n) d\r\npivot\r\n(\r\nsum(CaseCount)\r\nfor CaseStatusID in (Created,Completed,Incident,Mitigated,Resolved)\r\n) piv) as a\r\nfull outer join\r\n(select p.FullName, avg(DATEDIFF(minute,DateEarliestEvidence,DateCreated)) as 'Avg Time to Detect',\r\navg(DATEDIFF(minute,DateCreated,DateMitigated)) as 'Avg Time to Respond',\r\navg(DATEDIFF(minute,DateEarliestEvidence,DateCreated)) as 'Avg Time to Qualify',\r\navg(DATEDIFF(minute,DateCreated,DateClosed)) as 'Avg Time to Investigate',\r\navg(DATEDIFF(minute,DateIncident,DateMitigated)) as 'Avg Time to Mitigate',\r\navg(DATEDIFF(minute,DateMitigated,DateResolved)) as 'Avg Time to Recover'\r\nFROM [LogRhythm_CMDB].[dbo].[Case] as c\r\nleft join [LogRhythmEMDB].[dbo].[Person] as p on p.PersonID=c.PersonID\r\nwhere  DateCreated between getdate()-30 and getdate() and p.PersonID is not null\r\ngroup by FullName) as b on a.[Case Owner]=b.FullName"
    }
   ]
  },
  {
   "title": "Alarms By Analyst",
   "type": "table",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "rawSql": "select *\r\nfrom\r\n(\r\nselect FullName,(Convert(nvarchar, Case \r\nWhen AlarmStatus = 0 Then 'New' \r\nWhen AlarmStatus = 1 Then 'Opened'\r\nWhen AlarmStatus = 2 Then 'Opened'\r\nWhen AlarmStatus = 3 Then 'Opened'\r\nWhen AlarmStatus = 4 Then 'Closed' \r\nWhen AlarmStatus = 5 Then 'Closed' \r\nWhen AlarmStatus = 6 Then 'Closed' \r\nWhen AlarmStatus = 7 Then 'Closed' \r\nWhen AlarmStatus = 8 Then 'Closed' \r\nWhen AlarmStatus = 9 Then 'Closed' End)) as AlarmStatus \r\n, count(AlarmStatus) as 'Total'\r\nfrom [LogRhythm_Alarms].[dbo].AlarmMetrics \r\njoin [LogRhythm_Alarms].[dbo].[Alarm] on Alarm.AlarmID=AlarmMetrics.AlarmID \r\njoin LogRhythmEMDB.dbo.AlarmRule on Alarm.AlarmRuleID=AlarmRule.AlarmRuleID\r\nleft join [LogRhythmEMDB].[dbo].[Person] on Person.PersonID=LastPersonID\r\nwhere  $__timeFilter(AlarmDate)\r\ngroup by FullName,AlarmStatus\r\n) d\r\npivot\r\n(\r\nsum(Total)\r\nfor AlarmStatus in (New,Opened,Closed)\r\n) piv"
    }
   ]
  },
  {
   "title": "Weekly Alarms Status",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "rawSql": "select datename(dw,AlarmDate) as Day,AlarmDate, (ISNULL(New,0)+ISNULL(OpenAlarm,0)+ISNULL(Working,0)+ISNULL(Escalated,0)+ISNULL(AutoClosed,0)+ISNULL(FalsePositive,0)+ISNULL(Resolved,0)+ISNULL(UnResolved,0)+ISNULL(Reported,0)+ISNULL(Monitor,0)) as Total,\r\n(ISNULL(AutoClosed,0)+ISNULL(FalsePositive,0)+ISNULL(Resolved,0)+ISNULL(UnResolved,0)+ISNULL(Reported,0)+ISNULL(Monitor,0)) as Closed\r\nfrom\r\n(\r\nselect CONVERT(date, AlarmDate) as AlarmDate,count(AlarmName.Name) as AlarmCount,\r\n(Convert(nvarchar, Case\r\nWhen AlarmStatus = 0 Then 'New'\r\nWhen AlarmStatus = 1 Then 'OpenAlarm'\r\nWhen AlarmStatus = 2 Then 'Working'\r\nWhen AlarmStatus = 3 Then 'Escalated'\r\nWhen AlarmStatus = 4 Then 'AutoClosed'\r\nWhen AlarmStatus = 5 Then 'FalsePositive'\r\nWhen AlarmStatus = 6 Then 'Resolved'\r\nWhen AlarmStatus = 7 Then 'UnResolved'\r\nWhen AlarmStatus = 8 Then 'Reported'\r\nWhen AlarmStatus = 9 Then 'Monitor' End)) as AlarmStatus\r\nfrom [LogRhythm_Alarms].[dbo].[Alarm] as Alarm join LogRhythmEMDB.dbo.AlarmRule as AlarmName on Alarm.AlarmRuleID=AlarmName.AlarmRuleID\r\nwhere\r\nAlarm.AlarmDate BETWEEN getdate()-6 AND getdate()\r\ngroup by AlarmDate,AlarmStatus\r\n) d\r\npivot\r\n(\r\nsum(AlarmCount)\r\nfor AlarmStatus in (New,OpenAlarm,Working,Escalated,AutoClosed,FalsePositive,Resolved,UnResolved,Reported,Monitor)\r\n) piv\r\n"
    }
   ]
  },
  {
   "title": "Alarms by status",
   "type": "table",
   "gridPos": { "h": 18, "w": 20, "x": 3, "y": 45 },
   "targets": [
    {
     "rawSql": "select Name, (ISNULL(New,0)+ISNULL(OpenAlarm,0)+ISNULL(Working,0)+ISNULL(Escalated,0)+ISNULL(AutoClosed,0)+ISNULL(FalsePositive,0)+ISNULL(Resolved,0)+ISNULL(UnResolved,0)+ISNULL(Reported,0)+ISNULL(Monitor,0)) as Total,\r\nISNULL(New,0) as New,\r\nISNULL(OpenAlarm,0) as 'Open',\r\nISNULL(Working,0) as Working,\r\nISNULL(Escalated,0) as Escalated,\r\nISNULL(AutoClosed, 0 )as 'Auto Closed',\r\nISNULL(FalsePositive,0) as 'False Positive',\r\nISNULL(Resolved,0) as Resolved,\r\nISNULL(UnResolved,0) as UnResolved,\r\nISNULL(Reported,0) as Reported,\r\nISNULL(Monitor,0) as Monitor\r\nfrom\r\n(\r\nselect AlarmName.Name,count(AlarmName.Name) as AlarmCount,\r\n(Convert(nvarchar, Case\r\nWhen AlarmStatus = 0 Then 'New' \r\nWhen AlarmStatus = 1 Then 'OpenAlarm'\r\nWhen AlarmStatus = 2 Then 'Working'\r\nWhen AlarmStatus = 3 Then 'Escalated'\r\nWhen AlarmStatus = 4 Then 'AutoClosed' \r\nWhen AlarmStatus = 5 Then 'FalsePositive' \r\nWhen AlarmStatus = 6 Then 'Resolved' \r\nWhen AlarmStatus = 7 Then 'UnResolved' \r\nWhen AlarmStatus = 8 Then 'Reported' \r\nWhen AlarmStatus = 9 Then 'Monitor' End)) as AlarmStatus\r\nfrom [LogRhythm_Alarms].[dbo].[Alarm] as Alarm join LogRhythmEMDB.dbo.AlarmRule as AlarmName on Alarm.AlarmRuleID=AlarmName.AlarmRuleID\r\nwhere\r\n $__timeFilter(Alarm.AlarmDate)\r\ngroup by AlarmName.Name,AlarmStatus\r\n) d\r\npivot\r\n(\r\nmax(AlarmCount)\r\nfor AlarmStatus in (New,OpenAlarm,Working,Escalated,AutoClosed,FalsePositive,Resolved,UnResolved,Reported,Monitor)\r\n) piv\r\n"
    }
   ]
  },
  {
   "title": "Alarm SLA",
   "type": "table",
   "gridPos": { "h": 13, "w": 23, "x": 0, "y": 63 },
   "targets": [
    {
     "rawSql": "select [LogRhythm_Alarms].[dbo].AlarmMetrics.AlarmID,Name,\r\nCoalesce( Convert(varchar(5),abs(DateDiff(day, (cast(OpenedOn as datetime)-cast(GeneratedOn as datetime)),'1900-01-01')))  + ':'\r\n + Convert(varchar(10),(cast(OpenedOn as datetime)-cast(GeneratedOn as datetime)), 108),'00:00:00:00') as 'Response Time',\r\n Coalesce( Convert(varchar(5),abs(DateDiff(day, (cast(ClosedOn as datetime)-cast(GeneratedOn as datetime)),'1900-01-01')))  + ':'\r\n + Convert(varchar(10),(cast(ClosedOn as datetime)-cast(GeneratedOn as datetime)), 108),'00:00:00:00') as 'Resolution Time',\r\nGeneratedOn,OpenedOn,ClosedOn,\r\n(Convert(nvarchar, Case When AlarmStatus = 4 Then 'AutoClosed' When AlarmStatus = 8 Then 'Reported' When AlarmStatus = 6 Then 'Resolved' When AlarmStatus = 5 Then 'FalsePositive' When AlarmStatus = 0 Then 'New' When AlarmStatus = 1 Then 'OpenAlarm' when AlarmStatus = 9 Then 'Monitor' End)) as AlarmStatus,FullName\r\nfrom [LogRhythm_Alarms].[dbo].AlarmMetrics\r\njoin [LogRhythm_Alarms].[dbo].[Alarm] on Alarm.AlarmID=AlarmMetrics.AlarmID \r\njoin LogRhythmEMDB.dbo.AlarmRule on Alarm.AlarmRuleID=AlarmRule.AlarmRuleID\r\nleft join [LogRhythmEMDB].[dbo].[Person] on Person.PersonID=LastPersonID\r\nwhere  $__timeFilter(AlarmDate)\r\norder by [LogRhythm_Alarms].[dbo].AlarmMetrics.AlarmID desc\r\n"
    }
   ]
  }
 ]
}