{
 "title": "2025: Log Sources Report",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Messages Per Second",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "USE [LogRhythm_LogMart];\r\nSELECT\r\n  [Avg MPS] = CAST(SUM(CAST(CountProcessedLogs as BIGINT)) AS real) / CAST(DATEDIFF(ss,$__timeFrom(),$__timeTo()) as BIGINT),\r\n\t[Max MPS] = CAST(MAX(CountProcessedLogs) AS float) / 60.0\r\nFROM\r\n\t[dbo].StatsDeploymentCountsMinute with (NOLOCK)\r\nWHERE  $__timeFilter(StatDate);"
    }
   ]
  },
  {
   "title": "Total Log Sources Without LR",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(*)\nFROM\n  LogRhythmEMDB.dbo.MsgSource with (NOLOCK)\nWHERE\n  RecordStatus = 1 AND Name NOT LIKE 'AI Engine%'\n  AND MsgSourceTypeID != 3\n  AND MsgSourceTypeID != 1000539\nAND MsgSourceTypeID != 1000162\nAND MsgSourceTypeID != 1000158\nAND MsgSourceTypeID != 1000059\nAND MsgSourceTypeID != 1000044\n"
    }
   ]
  },
  {
   "title": "Log Processing Rates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "select \r\n  $__timeGroup(StatDate, '1d') AS time,\r\n  [Logs Processed] = SUM(cast(CountProcessedLogs as bigint)),\r\n  [Actual Logs Processed By AIEs] = SUM(cast(CountAnalyzedLogs as bigint)),\r\n  [Logs Processed By AIEs] = \r\n    case \r\n      when SUM(cast(CountAnalyzedLogs as bigint)) = 0 THEN 0\r\n      when SUM(cast(CountAnalyzedLogs as bigint)) <= SUM(cast(CountProcessedLogs as bigint)) THEN SUM(cast(CountAnalyzedLogs as bigint))\r\n      else SUM(cast(CountProcessedLogs as bigint))\r\n    end,\r\n  [Events Forwarded By LMs] = SUM(cast(CountEventsForwarded as bigint)),\r\n  [Events Forwarded By AIEs] = SUM(cast(CountEventsAIEngine as bigint)),\r\n  [Alarms] = SUM(cast(CountAlarms as bigint))\r\nfrom \r\n  LogRhythm_LogMart.dbo.StatsDeploymentCountsHour with (NOLOCK)\r\nWHERE \r\n  $__timeFilter(StatDate)\r\ngroup by \r\n   $__timeGroup(StatDate, '1d');"
    }
   ]
  },
  {
   "title": "LogSource MPS Last 6 Hours",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "rawSql": "Use LogRhythmEMDB\r\nselect top 10 a.Name as 'Log Source',\r\n(select top(1) DateAssigned from HostIdentifier where HostID=a.HostID) as 'Host Created Date',\r\nMaxLogDate as 'Last Log Message',\r\n(SELECT max(CountLogs/60)  FROM [LogRhythm_LogMart].[dbo].[StatsMsgSourceCountsMinute]  where MsgSourceID=a.MsgSourceID AND LogRhythm_LogMart.dbo.StatsMsgSourceCountsMinute.StatDate > DateAdd(hour,-6,GETDATE())) as 'Max MPS',\r\n(SELECT avg(countlogs/60)  FROM [LogRhythm_LogMart].[dbo].[StatsMsgSourceCountsMinute]  where MsgSourceID=a.MsgSourceID AND LogRhythm_LogMart.dbo.StatsMsgSourceCountsMinute.StatDate > DateAdd(hour,-6,GETDATE())) as 'Avg MPS'\r\nfrom MsgSource a\r\njoin MsgSourceMaxLogDate as b on a.MsgSourceID=b.MsgSourceID\r\njoin Host as c on c.HostID=a.HostID\r\nwhere a.MsgSourceID>0 and a.RecordStatus=1\r\n\r\norder by 'Avg MPS' DESC"
    }
   ]
  },
  {
   "title": "Log Sources MPS for 1 Day",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "rawSql": "Use LogRhythmEMDB\r\nselect top 20 a.Name as 'Log Source',\r\n(select top(1) DateAssigned from HostIdentifier where HostID=a.HostID) as 'Host Created Date',a.DateUpdated as 'Updated Date',\r\nMaxLogDate as 'Last Log Message',\r\n(SELECT max(CountLogs/60)  FROM [LogRhythm_LogMart].[dbo].[StatsMsgSourceCountsMinute]  where MsgSourceID=a.MsgSourceID AND LogRhythm_LogMart.dbo.StatsMsgSourceCountsMinute.StatDate > GETDATE() - 1) as 'Max MPS',\r\n(SELECT avg(countlogs/60)  FROM [LogRhythm_LogMart].[dbo].[StatsMsgSourceCountsMinute]  where MsgSourceID=a.MsgSourceID AND LogRhythm_LogMart.dbo.StatsMsgSourceCountsMinute.StatDate > GETDATE() - 1) as 'Avg MPS'\r\nfrom MsgSource a\r\njoin MsgSourceMaxLogDate as b on a.MsgSourceID=b.MsgSourceID\r\njoin Host as c on c.HostID=a.HostID\r\nwhere a.MsgSourceID>0 and a.RecordStatus=1\r\n--and a.MsgSourceID=18\r\norder by 'Avg MPS' DESC"
    }
   ]
  },
  {
   "title": "Devices Not Reporting for 1 Day",
   "type": "stat",
   "gridPos": { "h": 4, "w": 13, "x": 0, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "Use LogRhythmEMDB\r\nselect Count(*) as \"Log Sources\"\r\nfrom MsgSource a join MsgSourceMaxLogDate as b on a.MsgSourceID=b.MsgSourceID\r\n\r\nwhere a.MsgSourceID>0 and a.RecordStatus=1 and b.MaxLogDate > GetDate() - 100\r\nand b.MaxLogDate < DATEADD(minute, -1440, GETDATE()) "
    }
   ]
  },
  {
   "title": "Devices Not Reporting for 7 Day",
   "type": "stat",
   "gridPos": { "h": 4, "w": 11, "x": 13, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "Use LogRhythmEMDB\r\nselect Count(*) as \"Log Sources\"\r\nfrom MsgSource a join MsgSourceMaxLogDate as b on a.MsgSourceID=b.MsgSourceID\r\n\r\nwhere a.MsgSourceID>0 and a.RecordStatus=1 and b.MaxLogDate > GetDate() - 100\r\nand b.MaxLogDate < DATEADD(minute, -10080, GETDATE()) "
    }
   ]
  },
  {
   "title": "Devices Not Reporting for 1 Day",
   "type": "table",
   "gridPos": { "h": 15, "w": 13, "x": 0, "y": 45 },
   "targets": [
    {
     "rawSql": "Use LogRhythmEMDB\r\nselect a.Name as 'Log Source', b.MaxLogDate\r\nfrom MsgSource a join MsgSourceMaxLogDate as b on a.MsgSourceID=b.MsgSourceID\r\n\r\nwhere a.MsgSourceID>0 and a.RecordStatus=1 and b.MaxLogDate > GetDate() - 100\r\nand b.MaxLogDate < DATEADD(minute, -1440, GETDATE()) \r\nORDER BY b.MaxLogDate"
    }
   ]
  },
  {
   "title": "Devices Not Reporting for 7 Days",
   "type": "table",
   "gridPos": { "h": 15, "w": 11, "x": 13, "y": 45 },
   "targets": [
    {
     "rawSql": "Use LogRhythmEMDB\r\nselect a.Name as 'Log Source', b.MaxLogDate\r\nfrom MsgSource a join MsgSourceMaxLogDate as b on a.MsgSourceID=b.MsgSourceID\r\n\r\nwhere a.MsgSourceID>0 and a.RecordStatus=1 and b.MaxLogDate > GetDate() - 100\r\nand b.MaxLogDate < DATEADD(minute, -10080, GETDATE()) \r\nORDER BY b.MaxLogDate"
    }
   ]
  },
  {
   "title": "Devices Not Reporting for 30 Day",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 60 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "Use LogRhythmEMDB\r\nselect Count(*) as \"Log Sources\"from MsgSource a join MsgSourceMaxLogDate as b on a.MsgSourceID=b.MsgSourceID\r\n\r\nwhere a.MsgSourceID>0 and a.RecordStatus=1 and b.MaxLogDate > GetDate() - 100\r\nand b.MaxLogDate < GETDATE() - 30"
    }
   ]
  },
  {
   "title": "Devices Not Reporting for 30 Day",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 64 },
   "targets": [
    {
     "rawSql": "Use LogRhythmEMDB\r\nselect a.Name as 'Log Source', b.MaxLogDate\r\nfrom MsgSource a join MsgSourceMaxLogDate as b on a.MsgSourceID=b.MsgSourceID\r\n\r\nwhere a.MsgSourceID>0 and a.RecordStatus=1 and b.MaxLogDate > GetDate() - 100\r\nand b.MaxLogDate < DATEADD(minute, -43200, GETDATE()) \r\nORDER BY b.MaxLogDate"
    }
   ]
  }
 ]
}