{
 "title": "2025: Alarms Per Entity",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Alarms per Entity Summary ",
   "type": "table",
   "gridPos": { "h": 11, "w": 13, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "select Entity.Name as 'Entity',\r\n(Convert(nvarchar, Case\r\nWhen AlarmStatus = 0 Then 'New'\r\nWhen AlarmStatus = 1 Then 'OpenAlarm'\r\nWhen AlarmStatus = 2 Then 'Working'\r\nWhen AlarmStatus = 3 Then 'Escalated'\r\nWhen AlarmStatus = 4 Then 'AutoClosed'\r\nWhen AlarmStatus = 5 Then 'FalsePositive'\r\nWhen AlarmStatus = 6 Then 'Resolved'\r\nWhen AlarmStatus = 7 Then 'UnResolved'\r\nWhen AlarmStatus = 8 Then 'Reported'\r\nWhen AlarmStatus = 9 Then 'Monitor' End)) as Alarm_Status,\r\nCount(AlarmName.Name) as Alarm_Count\r\nfrom [LogRhythm_Alarms].[dbo].[Alarm] as Alarm join LogRhythmEMDB.dbo.AlarmRule as AlarmName on Alarm.AlarmRuleID=AlarmName.AlarmRuleID\r\njoin LogRhythmEMDB.dbo.Entity as Entity on Entity.EntityID=Alarm.EntityID\r\nWHERE $__timeFilter(DateInserted)\r\nGroup by Entity.Name, AlarmStatus\r\nORDER BY\r\n  [AlarmStatus] DESC"
    }
   ]
  },
  {
   "title": "Total Alarms",
   "type": "stat",
   "gridPos": { "h": 10, "w": 11, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n\tcount(*) as Count\nFROM\n  \tLogRhythm_Alarms.dbo.Alarm a with (NOLOCK)\n  \t  JOIN\n\t  LogRhythmEMDB.dbo.AlarmRule ar\n\t    ON a.AlarmRuleID = ar.AlarmRuleID\nWHERE\n  ar.AlarmType = 5\n    AND\n  $__timeFilter(DateInserted)"
    }
   ]
  },
  {
   "title": "Alarms per Entity",
   "type": "table",
   "gridPos": { "h": 24, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "rawSql": "select Entity.Name as 'Entity',Alarm.AlarmDate,Alarm.AlarmID,AlarmName.Name,\r\n(Convert(nvarchar, Case When AlarmStatus = 4 Then 'Auto Closed' When AlarmStatus = 8 Then 'Reported' When AlarmStatus = 6 Then 'Resolved' When AlarmStatus = 5 Then 'False Positive' When AlarmStatus = 0 Then 'New' When AlarmStatus = 1 Then 'OpenAlarm' when AlarmStatus = 9 Then 'Monitor' End)) as AlarmStatus\r\nfrom [LogRhythm_Alarms].[dbo].[Alarm] as Alarm join LogRhythmEMDB.dbo.AlarmRule as AlarmName on Alarm.AlarmRuleID=AlarmName.AlarmRuleID\r\njoin LogRhythmEMDB.dbo.Entity as Entity on Entity.EntityID=Alarm.EntityID\r\nWHERE $__timeFilter(DateInserted)\r\nORDER BY\r\n  [AlarmStatus] DESC"
    }
   ]
  }
 ]
}