{
 "title": "2025: CASE KPI - SLA Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total CASES",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) FROM [LogRhythm_CMDB].[dbo].[CASE]  WHERE $__timeFilter(DateCreated) "
    }
   ]
  },
  {
   "title": "Breached",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(CASE WHEN [Priority] =1 AND  DATEDIFF(HOUR,DateCreated,DateClosed) > 12 THEN 1 \r\n WHEN [Priority] =2 AND  DATEDIFF(DAY,DateCreated,DateClosed) > 3 THEN 1 \r\n WHEN [Priority] =3 AND  DATEDIFF(DAY,DateCreated,DateClosed) > 15 THEN 1 \r\n WHEN [Priority] IN (4,5) AND  DATEDIFF(DAY,DateCreated,DateClosed) > 30 THEN 1 ELSE NULL END)  AS [Breached_SLA]\r\n  FROM [LogRhythm_CMDB].[dbo].[CASE]  WHERE $__timeFilter(DateCreated) "
    }
   ]
  },
  {
   "title": "Not Breached",
   "type": "stat",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(CASE WHEN [Priority] =1 AND  DATEDIFF(HOUR,DateCreated,DateClosed) < 12 THEN 1 \r\n WHEN [Priority] =2 AND  DATEDIFF(DAY,DateCreated,DateClosed) < 3 THEN 1 \r\n WHEN [Priority] =3 AND  DATEDIFF(DAY,DateCreated,DateClosed) < 15 THEN 1 \r\n WHEN [Priority] IN (4,5) AND  DATEDIFF(DAY,DateCreated,DateClosed) < 30 THEN 1 ELSE NULL END)  AS [Not_Breached_SLA]\r\nFROM [LogRhythm_CMDB].[dbo].[CASE]  WHERE $__timeFilter(DateCreated) "
    }
   ]
  },
  {
   "title": "Cases SLA",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT [CaseNumber],c.[Name],[DateCreated],[Owner]=(SELECT pr.fullname FROM  [logrhythm_cmdb].[dbo].[Case] cl left join [logrhythmEMDB].[dbo].[person] pr on pr.personid = cl.lastupdatedby WHERE cl.caseid=c.caseid),[DateClosed],Status=cs.[Name],[Priority], \r\nCASE WHEN [Priority] =1 AND  DATEDIFF(HOUR,DateCreated,DateClosed) > 12 THEN 'YES' \r\n WHEN [Priority] =2 AND  DATEDIFF(DAY,DateCreated,DateClosed) > 3 THEN 'YES' \r\n WHEN [Priority] =3 AND  DATEDIFF(DAY,DateCreated,DateClosed) > 15 THEN 'YES' \r\n WHEN [Priority] IN (4,5) AND  DATEDIFF(DAY,DateCreated,DateClosed) > 30 THEN 'YES' ELSE 'NO' END AS [Breached SLA]\r\nFROM [logrhythm_cmdb].[dbo].[Case] c LEFT JOIN [logrhythm_cmdb].[dbo].[Casestatus] cs  ON  c.casestatusid = cs.casestatusid  WHERE $__timeFilter(DateCreated)  "
    }
   ]
  }
 ]
}