{
 "title": "2025: Customer Created Dashboard 02",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "server",
    "query": "SHOW TAG VALUES FROM \"system\" WITH KEY = \"host\""
   },
   { "name": "inter", "label": "Interval", "query": "10s,30s,1m,2m,5m,10m,30m,1h" },
   {
    "name": "host",
    "label": "Host",
    "query": "show tag values from /transporter/ with key = host"
   }
  ]
 },
 "panels": [
  {
   "title": "Memory used percent",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(used_percent) FROM \"mem\" WHERE \"host\" =~ /^$server$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "load 1",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"load1\") FROM \"system\" WHERE \"host\" =~ /^$server$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Elasticsearch Health",
   "type": "table",
   "gridPos": { "h": 3, "w": 6, "x": 9, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "limit": "1",
     "measurement": "elasticsearch_cluster_health",
     "select": [
      [
       { "params": [ "status" ], "type": "field" },
       {
        "params": [],
        "type": "mode"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "load 5",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"load5\") FROM \"system\" WHERE \"host\" =~ /^$server$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Max Disk used percent",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(used_percent) FROM \"disk\" WHERE \"host\" =~ /^$server$/ and \"device\" != 'rootfs'  and $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "load 15",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 9, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"load15\") FROM \"system\" WHERE \"host\" =~ /^$server$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "API Gateway",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "service_metric.running",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=", "value": "api-gateway" }
     ]
    }
   ]
  },
  {
   "title": "Service Registry",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "service_metric.running",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=", "value": "service-registry" }
     ]
    }
   ]
  },
  {
   "title": "Requests",
   "type": "table-old",
   "description": "If transporter has been restarted within the last 15 minutes, it will be the number of requests since restart.",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 8 },
   "targets": [
    {
     "alias": "[$tag_cluster] [$tag_host]",
     "groupBy": [
      { "params": [ "15m" ], "type": "time" },
      { "params": [ "cluster" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "transporter.http.requests",
     "query": "SELECT last(\"value\") - min(\"value\") FROM \"transporter.http.requests\" WHERE (\"host\" =~ /^$host$/) AND time >= now() - 15m GROUP BY \"cluster\", \"host\" fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       },
       { "params": [ "-" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Elasticsearch Response Time",
   "type": "table-old",
   "description": "If Transporter is not indexing, the 15 minute average will reflect the duration of the last successful request from Transporter to elasticsearch.",
   "gridPos": { "h": 3, "w": 10, "x": 7, "y": 8 },
   "targets": [
    {
     "alias": "<b>[$tag_cluster]</b> $tag_host",
     "groupBy": [
      { "params": [ "15m" ], "type": "time" },
      { "params": [ "cluster" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "transporter.elastic.processor.last_duration",
     "query": "SELECT mean(\"value\") FROM \"transporter.elastic.processor.last_duration\" WHERE (\"host\" =~ /^$host$/) AND time >= now() - 15m GROUP BY \"cluster\", \"host\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Failed Requests",
   "type": "table-old",
   "description": "If transporter has been restarted within the last 15 minutes, it will be the number of failed requests since restart.",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 8 },
   "targets": [
    {
     "alias": "[$tag_cluster] [$tag_host] Elasticsearch",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "cluster" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^(transporter.http.requests.rejected|transporter.http.requests.forbidden|transporter.http.requests.too_many|transporter.http.requests.too_many_timeout)/",
     "query": "SELECT last(\"value\") - min(\"value\") FROM /^(transporter.http.requests.rejected|transporter.http.requests.forbidden|transporter.http.requests.too_many|transporter.http.requests.too_many_timeout)/ WHERE (\"host\" =~ /^$host$/) AND time >= now() - 15m GROUP BY  \"host\", \"cluster\" fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "[$tag_cluster] [$tag_host] CloudAI",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cloudai.failure",
     "query": "SELECT last(\"value\") - min(\"value\") FROM \"cloudai.failure\" WHERE (\"host\" =~ /^$host$/) AND time >= now() - 15m GROUP BY \"host\", \"cluster\" fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Anomalies remontées par entité",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    Entity.Name AS 'Entity',\r\n    COUNT(AlarmName.Name) AS Total_Alarms\r\nFROM \r\n    [LogRhythm_Alarms].[dbo].[Alarm] AS Alarm\r\nJOIN \r\n    LogRhythmEMDB.dbo.AlarmRule AS AlarmName ON Alarm.AlarmRuleID = AlarmName.AlarmRuleID\r\nJOIN \r\n    LogRhythmEMDB.dbo.Entity AS Entity ON Entity.EntityID = Alarm.EntityID\r\nWHERE \r\n    $__timeFilter(Alarm.DateInserted)\r\n    AND AlarmName.[AlarmRuleGroup] != 'LogRhythm Diagnostics' -- Exclusion des alarmes diagnostics\r\nGROUP BY \r\n    Entity.Name\r\nORDER BY \r\n    Total_Alarms DESC;\r\n"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 8, "w": 10, "x": 7, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "USE [LogRhythm_LogMart];\r\nSELECT\r\n  \r\n  [Avg MPS] = CAST(SUM(CAST(CountProcessedLogs AS BIGINT)) AS real) / CAST(DATEDIFF(ss, $__timeFrom(), $__timeTo()) AS BIGINT),\r\n  [Max MPS] = CAST(MAX(CountProcessedLogs) AS float) / 60.0\r\nFROM\r\n  [dbo].StatsDeploymentCountsMinute WITH (NOLOCK)\r\nWHERE \r\n  $__timeFilter(StatDate);\r\n"
    }
   ]
  },
  {
   "title": " LogRhythm Diagnostics Alarms",
   "type": "table",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    Entity.Name AS 'Entity',\r\n    A.[AlarmID] AS 'Alarm ID',\r\n    AR.[Name] AS 'Alarm Name'\r\n    \r\nFROM \r\n    [LogRhythm_Alarms].[dbo].[Alarm] AS A\r\nJOIN \r\n    LogRhythmEMDB.dbo.AlarmRule AS AR ON A.[AlarmRuleID] = AR.[AlarmRuleID]\r\nJOIN \r\n    LogRhythmEMDB.dbo.Entity AS Entity ON Entity.EntityID = A.EntityID\r\nWHERE \r\n    $__timeFilter(A.[DateInserted])\r\n    AND AR.[AlarmRuleGroup] = 'LogRhythm Diagnostics' -- Alarmes diagnostics\r\nORDER BY \r\n    A.[AlarmID] DESC;\r\n"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $col",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "key": "host", "params": [ "tag" ], "type": "tag" }
     ],
     "measurement": "cpu_percentageBusy",
     "query": "SELECT   mean(usage_active) as \"CPU\"   FROM \"cpu\" WHERE \"host\" =~ /$server$/ and  cpu = 'cpu-total' AND $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk used percent",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 7, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $tag_path",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "path" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "query": "SELECT mean(\"used_percent\") AS \"used_percent\" FROM \"disk\"  WHERE \"host\" =~ /$server$/ AND $timeFilter GROUP BY time($interval), \"host\", \"path\"\n",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "used_percent" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory used percent",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 19 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_host: used",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "query": "SELECT mean(\"used_percent\") as \"Memory\" FROM \"mem\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), host ORDER BY asc",
     "select": [
      [
       { "params": [ "available_percent" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  }
 ]
}