{
 "title": "2025: MSSP Cases Report",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "All Cases",
   "type": "stat",
   "gridPos": { "h": 5, "w": 13, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n count(*) as Count\nFROM\n  \t[LogRhythm_CMDB].[dbo].[Case] with (NOLOCK)\nWHERE\n  $__timeFilter([DateCreated])"
    }
   ]
  },
  {
   "title": "Cases by Entity by Priority",
   "type": "table",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "WITH AvgTimes AS (\r\n  SELECT\r\n    AVG(DATEDIFF(MINUTE, c.[DateEarliestEvidence], c.[DateCreated])) AS avgTTD,\r\n    AVG(DATEDIFF(MINUTE, c.[DateCreated], c.[DateClosed])) AS avgTTR,\r\n    COUNT(*) AS CaseCount,\r\n    c.[EntityID]\r\n  FROM \r\n    LogRhythm_CMDB.dbo.[Case] c WITH (NOLOCK)\r\n  WHERE \r\n    c.[DateClosed] IS NOT NULL  -- Ensures only closed cases are considered for TTR\r\n    AND c.[EntityID] IS NOT NULL  -- Ensures valid EntityID for proper joins\r\n  GROUP BY\r\n    c.[EntityID]\r\n)\r\nSELECT\r\n  e.[Name] AS EntityName,\r\n  at.avgTTD,\r\n  at.avgTTR,\r\n  at.CaseCount\r\nFROM \r\n  AvgTimes at\r\nINNER JOIN\r\n  [LogRhythmEMDB].[dbo].[Entity] e ON at.[EntityID] = e.[EntityID]\r\nWHERE\r\n  e.[Name] IS NOT NULL;  -- Ensures no NULL entity names\r\n"
    }
   ]
  },
  {
   "title": "Cases by Entities",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH AvgTimes AS (\n  SELECT\n    COUNT(*) AS Count,\n    [EntityID]\n  FROM \n    LogRhythm_CMDB.dbo.[Case] WITH (NOLOCK)\n  GROUP BY\n    [EntityID]\n)\nSELECT\n  e.[Name] AS EntityName,\n  at.Count\nFROM \n  AvgTimes at\nLEFT JOIN \n  [LogRhythmEMDB].[dbo].[Entity] e ON at.[EntityID] = e.[EntityID]\nWHERE \n  e.[Name] IS NOT NULL;"
    }
   ]
  },
  {
   "title": "Cases by Entities Table",
   "type": "table",
   "gridPos": { "h": 10, "w": 11, "x": 13, "y": 7 },
   "targets": [
    {
     "rawSql": "WITH AvgTimes AS (\n  SELECT\n    COUNT(*) AS Count,\n    [EntityID]\n  FROM \n    LogRhythm_CMDB.dbo.[Case] WITH (NOLOCK)\n  GROUP BY\n    [EntityID]\n)\nSELECT\n  e.[Name] AS EntityName,\n  at.Count\nFROM \n  AvgTimes at\nLEFT JOIN \n  [LogRhythmEMDB].[dbo].[Entity] e ON at.[EntityID] = e.[EntityID]\nWHERE \n  e.[Name] IS NOT NULL;"
    }
   ]
  },
  {
   "title": "Cases by entity by Status by Count",
   "type": "table",
   "gridPos": { "h": 15, "w": 9, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT * FROM\r\n(\r\n    SELECT \r\n        e.Name AS [Entity Name], \r\n        COUNT(c.Name) AS CaseCount,\r\n        CASE \r\n            WHEN c.CaseStatusID = 1 THEN 'Created'\r\n            WHEN c.CaseStatusID = 2 THEN 'Completed'\r\n            WHEN c.CaseStatusID = 3 THEN 'Incident'\r\n            WHEN c.CaseStatusID = 4 THEN 'Mitigated'\r\n            WHEN c.CaseStatusID = 5 THEN 'Resolved' \r\n        END AS CaseStatus\r\n    FROM [LogRhythm_CMDB].[dbo].[Case] AS c\r\n    LEFT JOIN [LogRhythmEMDB].[dbo].[Person] AS p ON p.PersonID = c.PersonID\r\n    LEFT JOIN [LogRhythmEMDB].[dbo].[Entity] AS e ON e.EntityID = c.EntityID \r\n    WHERE e.Name IS NOT NULL  -- Exclude NULL Entity Names\r\n      AND c.CaseStatusID IS NOT NULL  -- Exclude NULL Case Statuses\r\n    GROUP BY e.Name, c.CaseStatusID\r\n) d\r\nPIVOT\r\n(\r\n    SUM(CaseCount)\r\n    FOR CaseStatus IN ([Created], [Completed], [Incident], [Mitigated], [Resolved])\r\n) piv;\r\n"
    }
   ]
  },
  {
   "title": "Case Full Table",
   "type": "table",
   "gridPos": { "h": 14, "w": 15, "x": 9, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "rawSql": "WITH Cases AS (\r\n    SELECT\r\n        c.EntityID,\r\n        COUNT(c.Name) AS CaseCount,\r\n        (CONVERT(NVARCHAR, CASE\r\n            WHEN CaseStatusID = 1 THEN 'Created'\r\n            WHEN CaseStatusID = 2 THEN 'Completed'\r\n            WHEN CaseStatusID = 3 THEN 'Incident'\r\n            WHEN CaseStatusID = 4 THEN 'Mitigated'\r\n            WHEN CaseStatusID = 5 THEN 'Resolved' \r\n        END)) AS CaseStatusName\r\n    FROM [LogRhythm_CMDB].[dbo].[Case] AS c\r\n    LEFT JOIN [LogRhythmEMDB].[dbo].[Person] AS p ON p.PersonID = c.PersonID\r\n    WHERE DateCreated BETWEEN DATEADD(DAY, -30, GETDATE()) AND GETDATE() \r\n    AND p.PersonID IS NOT NULL\r\n    GROUP BY c.EntityID, CaseStatusID\r\n),\r\nPivotedCases AS (\r\n    SELECT\r\n        EntityID,\r\n        ISNULL([Created], 0) AS Created,\r\n        ISNULL([Completed], 0) AS Completed,\r\n        ISNULL([Incident], 0) AS Incident,\r\n        ISNULL([Mitigated], 0) AS Mitigated,\r\n        ISNULL([Resolved], 0) AS Resolved\r\n    FROM Cases\r\n    PIVOT\r\n    (\r\n        SUM(CaseCount)\r\n        FOR CaseStatusName IN ([Created], [Completed], [Incident], [Mitigated], [Resolved])\r\n    ) piv\r\n)\r\nSELECT\r\n    ISNULL(e.Name, 'Unknown') AS [Entity Name], \r\n    pc.Created,\r\n    pc.Completed,\r\n    pc.Incident,\r\n    pc.Mitigated,\r\n    pc.Resolved,\r\n    b.[Avg Time to Detect],\r\n    b.[Avg Time to Respond],\r\n    b.[Avg Time to Qualify],\r\n    b.[Avg Time to Investigate],\r\n    b.[Avg Time to Mitigate],\r\n    b.[Avg Time to Recover]\r\nFROM PivotedCases AS pc\r\nLEFT JOIN (\r\n    SELECT\r\n        e.EntityID,\r\n        AVG(DATEDIFF(MINUTE, DateEarliestEvidence, DateCreated)) AS [Avg Time to Detect],\r\n        AVG(DATEDIFF(MINUTE, DateCreated, DateMitigated)) AS [Avg Time to Respond],\r\n        AVG(DATEDIFF(MINUTE, DateEarliestEvidence, DateCreated)) AS [Avg Time to Qualify],\r\n        AVG(DATEDIFF(MINUTE, DateCreated, DateClosed)) AS [Avg Time to Investigate],\r\n        AVG(DATEDIFF(MINUTE, DateIncident, DateMitigated)) AS [Avg Time to Mitigate],\r\n        AVG(DATEDIFF(MINUTE, DateMitigated, DateResolved)) AS [Avg Time to Recover]\r\n    FROM [LogRhythm_CMDB].[dbo].[Case] AS c\r\n    LEFT JOIN [LogRhythmEMDB].[dbo].[Person] AS p ON p.PersonID = c.PersonID\r\n    LEFT JOIN [LogRhythmEMDB].[dbo].[Entity] AS e ON e.EntityID = c.EntityID\r\n    WHERE DateCreated BETWEEN DATEADD(DAY, -30, GETDATE()) AND GETDATE()\r\n    AND p.PersonID IS NOT NULL\r\n    GROUP BY e.EntityID\r\n) AS b ON pc.EntityID = b.EntityID\r\nLEFT JOIN [LogRhythmEMDB].[dbo].[Entity] AS e ON e.EntityID = pc.EntityID\r\nORDER BY e.Name;\r\n"
    }
   ]
  }
 ]
}