{
 "title": "2025: RhythmAI Suggested Dashboard for CISO",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  { "title": "Executive/CISO SOC Dashboard", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "All Logs",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "normalDate", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "msgClassTypeName:*",
     "timeField": "normalDate"
    }
   ]
  },
  {
   "title": "Important Events",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "normalDate", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "msgClassName:* AND isEvent:\"true\"",
     "timeField": "normalDate"
    }
   ]
  },
  {
   "title": "Classified Events Trend",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 6, "y": 1 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "normalDate", "id": "2", "settings": { "interval": "1h", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "isEvent:\"true\"",
     "timeField": "normalDate"
    }
   ]
  },
  {
   "title": "Big Data Trending",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 1 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "normalDate", "id": "2", "settings": { "interval": "1h", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "msgClassTypeName:*",
     "timeField": "normalDate"
    }
   ]
  },
  {
   "title": "Total Alarms (30 Days)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    [AlarmID],\r\n    [EntityID],\r\n    [AlarmRuleID],\r\n    [AlarmDate],\r\n    [DateInserted],\r\n    [DateUpdated],\r\n    [AlarmStatus],\r\n    [LastPersonID]\r\nFROM \r\n    [LogRhythm_Alarms].[dbo].[Alarm]\r\nWHERE \r\n    [AlarmDate] >= DATEFROMPARTS(YEAR(GETDATE()), MONTH(GETDATE()) - 1, 1)\r\n    AND [AlarmDate] < DATEFROMPARTS(YEAR(GETDATE()), MONTH(GETDATE()), 1);\r\n"
    }
   ]
  },
  {
   "title": "Alarms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "select \r\n  $__timeGroup(StatDate, '1d') AS time,\r\n  [Alarms] = SUM(cast(CountAlarms as bigint))\r\nfrom \r\n  LogRhythm_LogMart.dbo.StatsDeploymentCountsHour with (NOLOCK)\r\nWHERE \r\n  $__timeFilter(StatDate)\r\ngroup by \r\n   $__timeGroup(StatDate, '1d');"
    }
   ]
  },
  {
   "title": "Org Risk by RBP %",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Avg Risk by RBP",
     "bucketAggs": [
      { "field": "normalDate", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "priority",
       "id": "1",
       "meta": {},
       "settings": { "missing": 2 },
       "type": "avg"
      }
     ],
     "timeField": "normalDate"
    }
   ]
  },
  {
   "title": "Org Risk Last Month",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 3, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "normalDate", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "amount",
       "id": "1",
       "meta": {},
       "settings": { "missing": 2 },
       "type": "avg"
      }
     ],
     "query": "logSourceName:*aie*",
     "timeField": "normalDate"
    }
   ]
  },
  {
   "title": "Alarms Per Entity",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 16 },
   "targets": [
    {
     "dataset": "LogRhythm_Alarms",
     "rawSql": "SELECT \r\n    Entity.Name AS 'Entity',\r\n    COUNT(AlarmName.Name) AS Total_Alarms\r\nFROM \r\n    [LogRhythm_Alarms].[dbo].[Alarm] AS Alarm\r\nJOIN \r\n    LogRhythmEMDB.dbo.AlarmRule AS AlarmName ON Alarm.AlarmRuleID = AlarmName.AlarmRuleID\r\nJOIN \r\n    LogRhythmEMDB.dbo.Entity AS Entity ON Entity.EntityID = Alarm.EntityID\r\nWHERE \r\n    $__timeFilter(Alarm.DateInserted)\r\n    AND AlarmName.[AlarmRuleGroup] != 'LogRhythm Diagnostics' -- Exclusion des alarmes diagnostics\r\nGROUP BY \r\n    Entity.Name\r\nORDER BY \r\n    Total_Alarms DESC;\r\n"
    }
   ]
  },
  {
   "title": "Alarms per Entity",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "rawSql": "SELECT\r\nentity.FullName,\r\n   avg(DATEDIFF(MINUTE, alarm_table.DateInserted, a.DateInserted)) AS 'Time to Detect',\r\n   avg(DATEDIFF(MINUTE, a.DateInserted, b.DateInserted)) AS 'Time to Acknowledge',\r\n   avg(DATEDIFF(MINUTE, b.DateInserted, c.DateInserted)) AS 'Time to Qualify',\r\n   avg(DATEDIFF(MINUTE, c.DateInserted, d.DateInserted)) AS 'Time to Report',\r\n   avg(DATEDIFF(MINUTE, c.DateInserted, e.DateInserted)) AS 'Time to Resolve'\r\nFROM [LogRhythm_Alarms].[dbo].[AlarmHistory] a\r\nJOIN [LogRhythm_Alarms].[dbo].[Alarm] alarm_table\r\n   ON a.AlarmID = alarm_table.AlarmID\r\njoin [LogRhythmEMDB].[dbo].[Entity] as entity on alarm_table.EntityID=entity.EntityID\r\nLEFT JOIN [LogRhythm_Alarms].[dbo].[AlarmHistory] b\r\n   ON a.AlarmID = b.AlarmID\r\n   AND b.Comments = 'Changed status to: Open: Working'\r\nLEFT JOIN [LogRhythm_Alarms].[dbo].[AlarmHistory] c\r\n   ON a.AlarmID = c.AlarmID\r\n   AND (c.Comments = 'Changed status to: Closed: False Alarm' OR c.Comments = 'Changed status to: Open: Escalated')\r\nLEFT JOIN [LogRhythm_Alarms].[dbo].[AlarmHistory] d\r\n   ON a.AlarmID = d.AlarmID\r\n   AND d.Comments = 'Changed status to: Closed: Reported'\r\nLEFT JOIN [LogRhythm_Alarms].[dbo].[AlarmHistory] e\r\n   ON a.AlarmID = e.AlarmID\r\n   AND e.Comments = 'Changed status to: Closed: Resolved'\r\nWHERE a.Comments = 'Changed status to: Open'\r\ngroup by entity.FullName"
    }
   ]
  },
  {
   "title": "False Positive Alarms",
   "type": "stat",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n\tcount(*) as Count\r\nFROM\r\n  \tLogRhythm_Alarms.dbo.Alarm a with (NOLOCK)\r\n  \t  JOIN\r\n\t  LogRhythmEMDB.dbo.AlarmRule ar\r\n\t    ON a.AlarmRuleID = ar.AlarmRuleID\r\nWhere AlarmStatus = 5\r\n    AND\r\n  $__timeFilter(DateInserted)"
    }
   ]
  },
  {
   "title": "SLA Breached",
   "type": "stat",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(CASE WHEN [Priority] =1 AND  DATEDIFF(HOUR,DateCreated,DateClosed) > 12 THEN 1 \r\n WHEN [Priority] =2 AND  DATEDIFF(DAY,DateCreated,DateClosed) > 3 THEN 1 \r\n WHEN [Priority] =3 AND  DATEDIFF(DAY,DateCreated,DateClosed) > 15 THEN 1 \r\n WHEN [Priority] IN (4,5) AND  DATEDIFF(DAY,DateCreated,DateClosed) > 30 THEN 1 ELSE NULL END)  AS [Breached_SLA]\r\n  FROM [LogRhythm_CMDB].[dbo].[CASE]  WHERE $__timeFilter(DateCreated) "
    }
   ]
  },
  {
   "title": "Alarms KPIs",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\nentity.FullName,\r\n   avg(DATEDIFF(MINUTE, alarm_table.DateInserted, a.DateInserted)) AS 'Time to Detect (in min)',\r\n   avg(DATEDIFF(MINUTE, a.DateInserted, b.DateInserted)) AS 'Time to Acknowledge (in min)',\r\n   avg(DATEDIFF(MINUTE, b.DateInserted, c.DateInserted)) AS 'Time to Qualify (in min)',\r\n   avg(DATEDIFF(MINUTE, c.DateInserted, d.DateInserted)) AS 'Time to Report (in min)',\r\n   avg(DATEDIFF(MINUTE, c.DateInserted, e.DateInserted)) AS 'Time to Resolve (in min)'\r\nFROM [LogRhythm_Alarms].[dbo].[AlarmHistory] a\r\nJOIN [LogRhythm_Alarms].[dbo].[Alarm] alarm_table\r\n   ON a.AlarmID = alarm_table.AlarmID\r\njoin [LogRhythmEMDB].[dbo].[Entity] as entity on alarm_table.EntityID=entity.EntityID\r\nLEFT JOIN [LogRhythm_Alarms].[dbo].[AlarmHistory] b\r\n   ON a.AlarmID = b.AlarmID\r\n   AND b.Comments = 'Changed status to: Open: Working'\r\nLEFT JOIN [LogRhythm_Alarms].[dbo].[AlarmHistory] c\r\n   ON a.AlarmID = c.AlarmID\r\n   AND (c.Comments = 'Changed status to: Closed: False Alarm' OR c.Comments = 'Changed status to: Open: Escalated')\r\nLEFT JOIN [LogRhythm_Alarms].[dbo].[AlarmHistory] d\r\n   ON a.AlarmID = d.AlarmID\r\n   AND d.Comments = 'Changed status to: Closed: Reported'\r\nLEFT JOIN [LogRhythm_Alarms].[dbo].[AlarmHistory] e\r\n   ON a.AlarmID = e.AlarmID\r\n   AND e.Comments = 'Changed status to: Closed: Resolved'\r\nWHERE a.Comments = 'Changed status to: Open'\r\ngroup by entity.FullName"
    }
   ]
  },
  {
   "title": "Alarms By Analyst",
   "type": "table",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 35 },
   "targets": [
    {
     "rawSql": "SELECT \r\n  b.Analyst,\r\n  b.[UnAssigned Alarms],\r\n  b.[Opened Alarms],\r\n  b.[Closed Alarms],\r\n  b.Total,\r\n  a.[Avg Time to Triage],\r\n  a.[AVG Time to Close],\r\n  a.[AVG Time to Investigate],\r\n  a.[Avg Alarms Risk]\r\nFROM (\r\n  SELECT \r\n    FullName AS Analyst,\r\n    AVG(DATEDIFF(MINUTE, GeneratedOn, OpenedOn)) AS [Avg Time to Triage],\r\n    AVG(DATEDIFF(MINUTE, GeneratedOn, ClosedOn)) AS [AVG Time to Close],\r\n    AVG(DATEDIFF(MINUTE, GeneratedOn, InvestigatedOn)) AS [AVG Time to Investigate],\r\n    AVG(m.Priority) AS [Avg Alarms Risk],\r\n    COUNT(*) AS Total\r\n  FROM [LogRhythm_Alarms].[dbo].AlarmMetrics\r\n  JOIN [LogRhythm_Alarms].[dbo].[Alarm] AS a ON a.AlarmID = AlarmMetrics.AlarmID\r\n  JOIN LogRhythmEMDB.dbo.AlarmRule ON a.AlarmRuleID = AlarmRule.AlarmRuleID\r\n  LEFT JOIN [LogRhythmEMDB].[dbo].[Person] AS p ON p.PersonID = LastPersonID\r\n  LEFT JOIN [LogRhythm_Alarms].[dbo].[AlarmToMARCMsg] AS am ON a.AlarmID = am.AlarmID\r\n  LEFT JOIN [LogRhythm_Events].[dbo].[Msg] AS m ON am.MARCMsgID = m.MsgID\r\n  WHERE \r\n    AlarmDate >= DATEFROMPARTS(YEAR(GETDATE()), MONTH(GETDATE()) - 1, 1)\r\n    AND AlarmDate < DATEFROMPARTS(YEAR(GETDATE()), MONTH(GETDATE()), 1)\r\n    AND p.PersonID IS NOT NULL\r\n  GROUP BY FullName\r\n) AS a\r\nFULL OUTER JOIN (\r\n  SELECT *, \r\n    ISNULL([UnAssigned Alarms], 0) + ISNULL([Opened Alarms], 0) + ISNULL([Closed Alarms], 0) AS Total\r\n  FROM (\r\n    SELECT \r\n      FullName AS Analyst, \r\n      CONVERT(nvarchar, CASE\r\n        WHEN AlarmStatus = 0 THEN 'UnAssigned Alarms'\r\n        WHEN AlarmStatus IN (1, 2, 3) THEN 'Opened Alarms'\r\n        WHEN AlarmStatus BETWEEN 4 AND 9 THEN 'Closed Alarms'\r\n      END) AS AlarmStatus, \r\n      COUNT(AlarmStatus) AS Total\r\n    FROM [LogRhythm_Alarms].[dbo].AlarmMetrics\r\n    JOIN [LogRhythm_Alarms].[dbo].[Alarm] AS a ON a.AlarmID = AlarmMetrics.AlarmID\r\n    JOIN LogRhythmEMDB.dbo.AlarmRule ON a.AlarmRuleID = AlarmRule.AlarmRuleID\r\n    LEFT JOIN [LogRhythmEMDB].[dbo].[Person] ON Person.PersonID = LastPersonID\r\n    LEFT JOIN [LogRhythm_Alarms].[dbo].[AlarmToMARCMsg] AS am ON a.AlarmID = am.AlarmID\r\n    LEFT JOIN [LogRhythm_Events].[dbo].[Msg] AS m ON am.MARCMsgID = m.MsgID\r\n    WHERE \r\n      AlarmDate >= DATEFROMPARTS(YEAR(GETDATE()), MONTH(GETDATE()) - 1, 1)\r\n      AND AlarmDate < DATEFROMPARTS(YEAR(GETDATE()), MONTH(GETDATE()), 1)\r\n    GROUP BY FullName, AlarmStatus\r\n  ) d\r\n  PIVOT (\r\n    SUM(Total)\r\n    FOR AlarmStatus IN ([UnAssigned Alarms], [Opened Alarms], [Closed Alarms])\r\n  ) piv\r\n) AS b \r\nON a.Analyst = b.Analyst\r\nORDER BY a.Analyst;"
    }
   ]
  },
  {
   "title": "Threat Landscape Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "panels": [
    {
     "title": "AI Attack Vectors",
     "type": "piechart",
     "gridPos": { "h": 11, "w": 10, "x": 0, "y": 281 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "object",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "logSourceName:*aie*",
       "timeField": "normalDate"
      }
     ]
    },
    {
     "title": "Emerging Threat by AI",
     "type": "piechart",
     "gridPos": { "h": 11, "w": 14, "x": 10, "y": 281 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "threatName",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "logSourceName:*aie*",
       "timeField": "normalDate"
      }
     ]
    },
    {
     "title": "Attack Vectors Reported from Log Sources",
     "type": "piechart",
     "gridPos": { "h": 11, "w": 10, "x": 0, "y": 292 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "msgClassName",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "msgClassTypeName:\"Security\" ",
       "timeField": "normalDate"
      }
     ]
    },
    {
     "title": "Emerging Threat by ALog Sources",
     "type": "piechart",
     "gridPos": { "h": 11, "w": 14, "x": 10, "y": 292 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "threatName",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "msgClassTypeName:\"Security\" ",
       "timeField": "normalDate"
      }
     ]
    }
   ]
  },
  {
   "title": "Operational Maturity Index (OMI)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "panels": [
    {
     "title": "Detection Score",
     "type": "piechart",
     "gridPos": { "h": 14, "w": 7, "x": 0, "y": 605 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "action",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "msgClassTypeName:\"Security\"",
       "timeField": "normalDate"
      }
     ]
    },
    {
     "title": "Ramy Ahmad",
     "type": "text",
     "gridPos": { "h": 7, "w": 3, "x": 7, "y": 605 },
     "options": {
      "content": "<center><img src=\"https://user-images.githubusercontent.com/42772877/190494244-5aae59b2-6a9f-482f-b19f-e6ffb6edc553.jpeg\">\n         "
     }
    },
    {
     "title": "Syed KPI",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 5, "x": 10, "y": 605 },
     "fieldConfig": { "defaults": { "unit": "m" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "rawSql": "SELECT TOP 10000 [Owner], [Case Collaborators],  (SELECT DATEDIFF_BIG (ss, CAST([Date Earliest Evidence] as datetime), CAST([Date Created]as datetime))) TTD,  (SELECT DATEDIFF_BIG(ss, CAST([Date Incident] as datetime), CAST([Date Mitigated] as datetime))) TTR,  (SELECT DATEDIFF(minute, CAST([Date Earliest Evidence] as datetime),CAST([Date Created] as datetime))) TTQ,  (SELECT DATEDIFF(minute, CAST([Date Created] as datetime),CAST([Date Incident] as datetime))) TTI,  (SELECT DATEDIFF(minute, CAST([Date Incident] as datetime),CAST([Date Mitigated] as datetime))) TTM,  (SELECT DATEDIFF(minute, CAST([Date Created] as datetime),CAST([Date Mitigated] as datetime))) TTV FROM [LogRhythm_CMDB].[dbo].[vw_Cases]\nWHERE [Owner] = 'Syed Rizvi'"
      }
     ]
    },
    {
     "title": "Omar Naggar KPI",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 6, "x": 15, "y": 605 },
     "fieldConfig": { "defaults": { "unit": "m" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "rawSql": "SELECT TOP 10000 [Owner], [Case Collaborators],  (SELECT DATEDIFF_BIG (ss, CAST([Date Earliest Evidence] as datetime), CAST([Date Created]as datetime))) TTD,  (SELECT DATEDIFF_BIG(ss, CAST([Date Incident] as datetime), CAST([Date Mitigated] as datetime))) TTR,  (SELECT DATEDIFF(minute, CAST([Date Earliest Evidence] as datetime),CAST([Date Created] as datetime))) TTQ,  (SELECT DATEDIFF(minute, CAST([Date Created] as datetime),CAST([Date Incident] as datetime))) TTI,  (SELECT DATEDIFF(minute, CAST([Date Incident] as datetime),CAST([Date Mitigated] as datetime))) TTM,  (SELECT DATEDIFF(minute, CAST([Date Created] as datetime),CAST([Date Mitigated] as datetime))) TTV FROM [LogRhythm_CMDB].[dbo].[vw_Cases]\nWHERE [Owner] = 'Naggar, Omar Admin'"
      }
     ]
    },
    {
     "title": "Omar Naggar",
     "type": "text",
     "gridPos": { "h": 7, "w": 3, "x": 21, "y": 605 },
     "options": {
      "content": "<center><img src=\"https://user-images.githubusercontent.com/42772877/190494302-474f49c6-ae71-44c9-bcda-52b313629a25.jpeg\">\n         "
     }
    },
    {
     "title": "Syed",
     "type": "text",
     "gridPos": { "h": 7, "w": 3, "x": 7, "y": 642 },
     "options": {
      "content": "<center><img src=\"https://raw.githubusercontent.com/Ramyahmad/Reporting/main/rizvi.jpeg\">\n         "
     }
    },
    {
     "title": "Ramy Ahmad KPI",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 5, "x": 10, "y": 642 },
     "fieldConfig": { "defaults": { "unit": "m" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "rawSql": "SELECT TOP 10000 [Owner], [Case Collaborators],  (SELECT DATEDIFF_BIG (ss, CAST([Date Earliest Evidence] as datetime), CAST([Date Created]as datetime))) TTD,  (SELECT DATEDIFF_BIG(ss, CAST([Date Incident] as datetime), CAST([Date Mitigated] as datetime))) TTR,  (SELECT DATEDIFF(minute, CAST([Date Earliest Evidence] as datetime),CAST([Date Created] as datetime))) TTQ,  (SELECT DATEDIFF(minute, CAST([Date Created] as datetime),CAST([Date Incident] as datetime))) TTI,  (SELECT DATEDIFF(minute, CAST([Date Incident] as datetime),CAST([Date Mitigated] as datetime))) TTM,  (SELECT DATEDIFF(minute, CAST([Date Created] as datetime),CAST([Date Mitigated] as datetime))) TTV FROM [LogRhythm_CMDB].[dbo].[vw_Cases]\nWHERE [Owner] = 'Ramy Ahmad'"
      }
     ]
    },
    {
     "title": "AbdelRahim KPI",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 6, "x": 15, "y": 642 },
     "fieldConfig": { "defaults": { "unit": "m" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "rawSql": "SELECT TOP 10000 [Owner], [Case Collaborators],  (SELECT DATEDIFF_BIG (ss, CAST([Date Earliest Evidence] as datetime), CAST([Date Created]as datetime))) TTD,  (SELECT DATEDIFF_BIG(ss, CAST([Date Incident] as datetime), CAST([Date Mitigated] as datetime))) TTR,  (SELECT DATEDIFF(minute, CAST([Date Earliest Evidence] as datetime),CAST([Date Created] as datetime))) TTQ,  (SELECT DATEDIFF(minute, CAST([Date Created] as datetime),CAST([Date Incident] as datetime))) TTI,  (SELECT DATEDIFF(minute, CAST([Date Incident] as datetime),CAST([Date Mitigated] as datetime))) TTM,  (SELECT DATEDIFF(minute, CAST([Date Created] as datetime),CAST([Date Mitigated] as datetime))) TTV FROM [LogRhythm_CMDB].[dbo].[vw_Cases]\nWHERE [Owner] = 'Abodouh, Abdelrahim'"
      }
     ]
    },
    {
     "title": "AbdelRahim",
     "type": "text",
     "gridPos": { "h": 7, "w": 3, "x": 21, "y": 642 },
     "options": {
      "content": "<center><img src=\"https://raw.githubusercontent.com/Ramyahmad/Reporting/main/abdo.jpeg\">\n         "
     }
    }
   ]
  },
  {
   "title": "Incident Response Breakdown",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "panels": [
    {
     "title": "Incidents",
     "type": "stat",
     "gridPos": { "h": 8, "w": 5, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "rawSql": "SELECT DISTINCT\r\n\tcount(DISTINCT C.CaseNumber) as Count\r\nFROM\r\n  \tLogRhythm_CMDB.dbo.[Case] C\r\nWhere C.CaseStatusID IN (3,4,5)\r\n    --AND CT.TagID <> 28\r\n    AND $__timeFilter(C.DateCreated)"
      }
     ]
    },
    {
     "title": "Incidents Status",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 7, "x": 5, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "count" ] } },
     "targets": [
      {
       "rawSql": "SELECT\r\n  $__timeEpoch(LogRhythm_CMDB.dbo.[Case].DateCreated),\r\n  COUNT(LogRhythm_CMDB.dbo.[Case].[CaseStatusID]) as value,\r\n  'Open(Created)' as metric\r\nFROM\r\n  LogRhythm_CMDB.dbo.[Case]\r\nWHERE\r\n  $__timeFilter(LogRhythm_CMDB.dbo.[Case].DateCreated)\r\n    AND LogRhythm_CMDB.dbo.[Case].CaseStatusID = 3\r\n  GROUP BY LogRhythm_CMDB.dbo.[Case].[Name], LogRhythm_CMDB.dbo.[Case].DateCreated\r\nORDER BY\r\n  LogRhythm_CMDB.dbo.[Case].DateCreated ASC"
      },
      {
       "rawSql": "SELECT\r\n  $__timeEpoch(LogRhythm_CMDB.dbo.[Case].DateCreated),\r\n  COUNT(LogRhythm_CMDB.dbo.[Case].[CaseStatusID]) as value,\r\n  'Resolved' as metric\r\nFROM\r\n  LogRhythm_CMDB.dbo.[Case]\r\nWHERE\r\n  $__timeFilter(LogRhythm_CMDB.dbo.[Case].DateCreated)\r\n    AND LogRhythm_CMDB.dbo.[Case].CaseStatusID = 5\r\n  GROUP BY LogRhythm_CMDB.dbo.[Case].[Name], LogRhythm_CMDB.dbo.[Case].DateCreated\r\nORDER BY\r\n  LogRhythm_CMDB.dbo.[Case].DateCreated ASC"
      },
      {
       "rawSql": "SELECT\r\n  $__timeEpoch(LogRhythm_CMDB.dbo.[Case].DateCreated),\r\n  COUNT(LogRhythm_CMDB.dbo.[Case].[CaseStatusID]) as value,\r\n  'Mitigated' as metric\r\nFROM\r\n  LogRhythm_CMDB.dbo.[Case]\r\nWHERE\r\n  $__timeFilter(LogRhythm_CMDB.dbo.[Case].DateCreated)\r\n    AND LogRhythm_CMDB.dbo.[Case].CaseStatusID = 4\r\n  GROUP BY LogRhythm_CMDB.dbo.[Case].[Name], LogRhythm_CMDB.dbo.[Case].DateCreated\r\nORDER BY\r\n  LogRhythm_CMDB.dbo.[Case].DateCreated ASC"
      }
     ]
    },
    {
     "title": "Time since incident was opened",
     "type": "bargauge",
     "gridPos": { "h": 18, "w": 12, "x": 12, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "d" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\r\n  $__timeEpoch(LogRhythm_CMDB.dbo.[Case].DateCreated),\r\n  (DATEDIFF(DAY,LogRhythm_CMDB.dbo.[Case].DateCreated,ISNULL(LogRhythm_CMDB.dbo.[Case].DateClosed,CURRENT_TIMESTAMP))) as value,\r\n  LogRhythm_CMDB.dbo.[Case].[Name] as metric\r\nFROM\r\n  LogRhythm_CMDB.dbo.[Case]\r\nWHERE\r\n  $__timeFilter(LogRhythm_CMDB.dbo.[Case].DateCreated)\r\n  AND LogRhythm_CMDB.dbo.[Case].CaseStatusID IN (3,4)\r\nORDER BY\r\n  LogRhythm_CMDB.dbo.[Case].DateCreated ASC"
      }
     ]
    },
    {
     "title": "Cases by Categories",
     "type": "table",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 55 },
     "targets": [
      {
       "rawSql": "SELECT \r\n  t.Tag AS Tag,\r\n  COUNT(ct.CaseID) AS Count\r\nFROM \r\n  [LogRhythm_CMDB].[dbo].[CaseToTag] AS ct\r\nJOIN \r\n  [LogRhythm_CMDB].[dbo].[Tag] AS t ON ct.TagID = t.TagID\r\nJOIN \r\n  [LogRhythm_CMDB].[dbo].[Case] AS c ON c.CaseID = ct.CaseID\r\nWHERE \r\n  c.DateCreated BETWEEN DATEADD(DAY, -30, GETDATE()) AND GETDATE()\r\nGROUP BY \r\n  t.Tag\r\nORDER BY \r\n  Count DESC\r\n"
      }
     ]
    },
    {
     "title": "All Cases KPI",
     "type": "stat",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "m" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "rawSql": "SELECT TOP 1000 [Owner], [Case Collaborators],  (SELECT DATEDIFF_BIG (ss, CAST([Date Earliest Evidence] as datetime), CAST([Date Created]as datetime))) TTD,  (SELECT DATEDIFF_BIG(ss, CAST([Date Incident] as datetime), CAST([Date Mitigated] as datetime))) TTR,  (SELECT DATEDIFF(minute, CAST([Date Earliest Evidence] as datetime),CAST([Date Created] as datetime))) TTQ,  (SELECT DATEDIFF(minute, CAST([Date Created] as datetime),CAST([Date Incident] as datetime))) TTI,  (SELECT DATEDIFF(minute, CAST([Date Incident] as datetime),CAST([Date Mitigated] as datetime))) TTM,  (SELECT DATEDIFF(minute, CAST([Date Created] as datetime),CAST([Date Mitigated] as datetime))) TTV FROM [LogRhythm_CMDB].[dbo].[vw_Cases]"
      }
     ]
    }
   ]
  },
  {
   "title": "Strategic Risk Score & Trends",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "collapsed": true,
   "panels": [
    {
     "title": "Risk %",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 115 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "bucketAggs": [
        { "field": "normalDate", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "amount",
         "id": "1",
         "meta": {},
         "settings": { "missing": 2 },
         "type": "avg"
        }
       ],
       "query": "logSourceName:*aie*",
       "timeField": "normalDate"
      }
     ]
    },
    {
     "title": "External Risk",
     "type": "barchart",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 123 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "commonEventName",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "msgClassTypeName:\"Security\" AND directionName:\"External\"",
       "timeField": "normalDate"
      }
     ]
    },
    {
     "title": "Internal Risk",
     "type": "barchart",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 132 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "commonEventName",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "msgClassTypeName:\"Security\" AND NOT directionName:\"External\"",
       "timeField": "normalDate"
      }
     ]
    }
   ]
  }
 ]
}