{
 "title": "2025: Log Sources Report 2",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Messages Per Second",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "USE [LogRhythm_LogMart];\r\nSELECT\r\n  [Avg MPS] = CAST(SUM(CAST(CountProcessedLogs as BIGINT)) AS real) / CAST(DATEDIFF(ss,$__timeFrom(),$__timeTo()) as BIGINT),\r\n\t[Max MPS] = CAST(MAX(CountProcessedLogs) AS float) / 60.0\r\nFROM\r\n\t[dbo].StatsDeploymentCountsMinute with (NOLOCK)\r\nWHERE  $__timeFilter(StatDate);"
    }
   ]
  },
  {
   "title": "Total Log Sources",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(*) as Count\nFROM\n  LogRhythmEMDB.dbo.MsgSource with (NOLOCK)\nWHERE\n  RecordStatus = 1 AND Name NOT LIKE 'AI Engine%'"
    }
   ]
  },
  {
   "title": "Log Processing Rates",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "select \r\n  $__timeGroup(StatDate, '1d') AS time,\r\n  [Logs Processed] = SUM(cast(CountProcessedLogs as bigint)),\r\n  [Actual Logs Processed By AIEs] = SUM(cast(CountAnalyzedLogs as bigint)),\r\n  [Logs Processed By AIEs] = \r\n    case \r\n      when SUM(cast(CountAnalyzedLogs as bigint)) = 0 THEN 0\r\n      when SUM(cast(CountAnalyzedLogs as bigint)) <= SUM(cast(CountProcessedLogs as bigint)) THEN SUM(cast(CountAnalyzedLogs as bigint))\r\n      else SUM(cast(CountProcessedLogs as bigint))\r\n    end,\r\n  [Events Forwarded By LMs] = SUM(cast(CountEventsForwarded as bigint)),\r\n  [Events Forwarded By AIEs] = SUM(cast(CountEventsAIEngine as bigint)),\r\n  [Alarms] = SUM(cast(CountAlarms as bigint))\r\nfrom \r\n  LogRhythm_LogMart.dbo.StatsDeploymentCountsHour with (NOLOCK)\r\nWHERE \r\n  $__timeFilter(StatDate)\r\ngroup by \r\n   $__timeGroup(StatDate, '1d');"
    }
   ]
  },
  {
   "title": "Log Sources Report",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "rawSql": "select c.Name as 'Host',a.Name as 'Log Source',(select top(1) DateAssigned from HostIdentifier where HostID=a.HostID) as 'Host Created Date',a.DateUpdated as 'Updated Date',\r\nMaxLogDate as 'Last Log Message',\r\n(SELECT max(CountLogs/60)  FROM [LogRhythm_LogMart].[dbo].[StatsMsgSourceCountsMinute]  where MsgSourceID=a.MsgSourceID) as 'Max MPS',  (SELECT avg(countlogs/60)  FROM [LogRhythm_LogMart].[dbo].[StatsMsgSourceCountsMinute]    where MsgSourceID=a.MsgSourceID) as 'Avg MPS'\r\nfrom MsgSource a\r\njoin MsgSourceMaxLogDate as b on a.MsgSourceID=b.MsgSourceID\r\njoin Host as c on c.HostID=a.HostID\r\nwhere a.MsgSourceID>0 and a.RecordStatus=1\r\n--and a.MsgSourceID=18\r\norder by 'Max MPS' DESC"
    }
   ]
  },
  {
   "title": "Host Report",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    c.Name AS 'Host', \r\n    (SELECT TOP 1 DateAssigned FROM HostIdentifier WHERE HostID = c.HostID ORDER BY DateAssigned ASC) AS 'Host Created Date',\r\n    MAX(a.DateUpdated) AS 'Updated Date',\r\n    MAX(b.MaxLogDate) AS 'Last Log Message',\r\n    (SELECT MAX(CountLogs / 60)  \r\n     FROM [LogRhythm_LogMart].[dbo].[StatsMsgSourceCountsMinute]  \r\n     WHERE MsgSourceID IN (SELECT MsgSourceID FROM MsgSource WHERE HostID = c.HostID)) AS 'Max MPS',\r\n    (SELECT AVG(CountLogs / 60)  \r\n     FROM [LogRhythm_LogMart].[dbo].[StatsMsgSourceCountsMinute]  \r\n     WHERE MsgSourceID IN (SELECT MsgSourceID FROM MsgSource WHERE HostID = c.HostID)) AS 'Avg MPS'\r\nFROM MsgSource a\r\nJOIN MsgSourceMaxLogDate b ON a.MsgSourceID = b.MsgSourceID\r\nJOIN Host c ON c.HostID = a.HostID\r\nWHERE a.MsgSourceID > 0 AND a.RecordStatus = 1\r\nGROUP BY c.Name, c.HostID\r\nORDER BY 'Max MPS' DESC;\r\n"
    }
   ]
  }
 ]
}