{
 "title": "2025: SOC Dashboard (Comprehensive)",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Avg Log Size",
   "type": "stat",
   "gridPos": { "h": 13, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Average Log Size Bytes",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mediator.processing",
     "select": [
      [
       { "params": [ "Average_Log_Size_Bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=", "value": "LR-XM-Primary" }
     ]
    }
   ]
  },
  {
   "title": "MPS",
   "type": "stat",
   "gridPos": { "h": 13, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "USE [LogRhythm_LogMart];\r\nSELECT\r\n  [Avg MPS] = CAST(SUM(CAST(CountProcessedLogs as BIGINT)) AS real) / CAST(DATEDIFF(ss,$__timeFrom(),$__timeTo()) as BIGINT),\r\n\t[Max MPS] = CAST(MAX(CountProcessedLogs) AS float) / 60.0\r\nFROM\r\n\t[dbo].StatsDeploymentCountsMinute with (NOLOCK)\r\nWHERE  $__timeFilter(StatDate);"
    }
   ]
  },
  {
   "title": "Integrated Log Sources",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(*)\nFROM\n  LogRhythmEMDB.dbo.MsgSource with (NOLOCK)\nWHERE\n  RecordStatus = 1\n"
    }
   ]
  },
  {
   "title": "Devices Not Reporting for 7 Day",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "Use LogRhythmEMDB\r\nselect Count(*) as \"Log Sources\"\r\nfrom MsgSource a join MsgSourceMaxLogDate as b on a.MsgSourceID=b.MsgSourceID\r\n\r\nwhere a.MsgSourceID>0 and a.RecordStatus=1 and b.MaxLogDate > GetDate() - 100\r\nand b.MaxLogDate < DATEADD(minute, -10080, GETDATE()) "
    }
   ]
  },
  {
   "title": "Classified Events",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "normalDate", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "msgClassName:* AND isEvent:\"true\"",
     "timeField": "normalDate"
    }
   ]
  },
  {
   "title": "Classified Events Trend",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "normalDate", "id": "2", "settings": { "interval": "1h", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "isEvent:\"true\"",
     "timeField": "normalDate"
    }
   ]
  },
  {
   "title": "User Experience Table",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 6, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "Select TOP 10000 WT.TaskName, WT.LongResults, WT.ShortResults, WT.NumResults, datediff(minute,WT.DateCreated,WT.DateUpdated) QueryTime, U.Login from WebTask WT Inner Join WebSearch WS ON WS.WebSearchID = WT.WebSearchId INNER JOIN WebTaskToUser WTU On WTU.WebTaskId = WT.TaskID Inner JOin SCUser U On U.UserID = WTU.UserId"
    }
   ]
  },
  {
   "title": "Data Lake - Big Data",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 13, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "normalDate", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "msgClassTypeName:*",
     "timeField": "normalDate"
    }
   ]
  },
  {
   "title": "Big Data Trending",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 7 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "normalDate", "id": "2", "settings": { "interval": "1h", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "msgClassTypeName:*",
     "timeField": "normalDate"
    }
   ]
  },
  {
   "title": "Top Event Types",
   "type": "bargauge",
   "gridPos": { "h": 22, "w": 3, "x": 0, "y": 13 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "msgClassTypeName",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "normalDate"
    }
   ]
  },
  {
   "title": "Security Events",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 7, "x": 3, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "msgClassName",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "msgClassTypeName:\"Security\"",
     "timeField": "normalDate"
    }
   ]
  },
  {
   "title": "Audit Events",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 7, "x": 10, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "msgClassName",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "msgClassTypeName:\"Audit\"",
     "timeField": "normalDate"
    }
   ]
  },
  {
   "title": "Operations Events",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "msgClassName",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "msgClassTypeName:\"Operations\"",
     "timeField": "normalDate"
    }
   ]
  },
  {
   "title": "Top Devices",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 10, "x": 3, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "msgSourceTypeName",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "normalDate"
    }
   ]
  },
  {
   "title": "Log Source MPS Table",
   "type": "table",
   "gridPos": { "h": 13, "w": 11, "x": 13, "y": 22 },
   "targets": [
    {
     "rawSql": "Use LogRhythmEMDB\r\nselect top 10 a.Name as 'Log Source',\r\n(select top(1) DateAssigned from HostIdentifier where HostID=a.HostID) as 'Host Created Date',\r\nMaxLogDate as 'Last Log Message',\r\n(SELECT max(CountLogs/60)  FROM [LogRhythm_LogMart].[dbo].[StatsMsgSourceCountsMinute]  where MsgSourceID=a.MsgSourceID AND LogRhythm_LogMart.dbo.StatsMsgSourceCountsMinute.StatDate > DateAdd(hour,-24,GETDATE())) as 'Max MPS',\r\n(SELECT avg(countlogs/60)  FROM [LogRhythm_LogMart].[dbo].[StatsMsgSourceCountsMinute]  where MsgSourceID=a.MsgSourceID AND LogRhythm_LogMart.dbo.StatsMsgSourceCountsMinute.StatDate > DateAdd(hour,-24,GETDATE())) as 'Avg MPS'\r\nfrom MsgSource a\r\njoin MsgSourceMaxLogDate as b on a.MsgSourceID=b.MsgSourceID\r\njoin Host as c on c.HostID=a.HostID\r\nwhere a.MsgSourceID>0 and a.RecordStatus=1\r\n\r\norder by 'Avg MPS' DESC"
    }
   ]
  },
  {
   "title": "Attacks",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "msgClassName",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "msgClassName:*attack*",
     "timeField": "normalDate"
    }
   ]
  },
  {
   "title": "Malware",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 6, "x": 6, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "msgClassName",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "msgClassName:*malware*",
     "timeField": "normalDate"
    }
   ]
  },
  {
   "title": "Account Management ",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 6, "x": 12, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "msgClassName",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "msgClassName:(\"Account Created\" OR \"Account Deleted\")",
     "timeField": "normalDate"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "msgClassName",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "msgClassName:*network*",
     "timeField": "normalDate"
    }
   ]
  }
 ]
}