{
 "title": "2025: SOC Report 2",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "All Logs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "normalDate", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "msgClassTypeName:*",
     "timeField": "normalDate"
    }
   ]
  },
  {
   "title": "Event Types",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 3, "x": 6, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "msgClassTypeName",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "normalDate"
    }
   ]
  },
  {
   "title": "Org Avg Risk by MDI %",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Avg Risk by RBP",
     "bucketAggs": [
      { "field": "normalDate", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "priority",
       "id": "1",
       "meta": {},
       "settings": { "missing": 2 },
       "type": "avg"
      }
     ],
     "timeField": "normalDate"
    }
   ]
  },
  {
   "title": "Org Risk by Analytics Engines",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "normalDate", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "amount",
       "id": "1",
       "meta": {},
       "settings": { "missing": 2 },
       "type": "avg"
      }
     ],
     "query": "logSourceName:*aie*",
     "timeField": "normalDate"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "USE [LogRhythm_LogMart];\r\nSELECT\r\n  \r\n  [Avg MPS] = CAST(SUM(CAST(CountProcessedLogs AS BIGINT)) AS real) / CAST(DATEDIFF(ss, $__timeFrom(), $__timeTo()) AS BIGINT),\r\n  [Max MPS] = CAST(MAX(CountProcessedLogs) AS float) / 60.0\r\nFROM\r\n  [dbo].StatsDeploymentCountsMinute WITH (NOLOCK)\r\nWHERE \r\n  $__timeFilter(StatDate);\r\n"
    }
   ]
  },
  {
   "title": "Important Events",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "normalDate", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "msgClassName:* AND isEvent:\"true\"",
     "timeField": "normalDate"
    }
   ]
  },
  {
   "title": "Integrated Log Sources",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(*)\nFROM\n  LogRhythmEMDB.dbo.MsgSource with (NOLOCK)\nWHERE\n  RecordStatus = 1 AND Name NOT LIKE 'AI Engine%'\n  AND MsgSourceTypeID != 3\n  AND MsgSourceTypeID != 1000539\nAND MsgSourceTypeID != 1000162\nAND MsgSourceTypeID != 1000158\nAND MsgSourceTypeID != 1000059\nAND MsgSourceTypeID != 1000044\n"
    }
   ]
  },
  {
   "title": "Alarms",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    COUNT(*) AS Total_Alarms  -- Alarms\r\nFROM \r\n    [LogRhythm_Alarms].[dbo].[Alarm] AS Alarm\r\nJOIN \r\n    LogRhythmEMDB.dbo.AlarmRule AS AlarmName ON Alarm.AlarmRuleID = AlarmName.AlarmRuleID\r\nJOIN \r\n    LogRhythmEMDB.dbo.Entity AS Entity ON Entity.EntityID = Alarm.EntityID\r\nWHERE \r\n    $__timeFilter(Alarm.DateInserted)  -- Utilisation du filtre temporel Grafana\r\n    \r\n"
    }
   ]
  },
  {
   "title": "Alerts by Risk",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 3, "x": 6, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "LogRhythm_Alarms",
     "rawSql": "SELECT \r\n    [High], \r\n    [Medium], \r\n    [Low]\r\nFROM \r\n(\r\n    SELECT\r\n        CASE \r\n            WHEN Priority >= 60 THEN 'High'\r\n            WHEN Priority BETWEEN 40 AND 59 THEN 'Medium'\r\n            WHEN Priority < 40 THEN 'Low'\r\n        END AS Alarm_Priority,\r\n        MsgID\r\n    FROM \r\n        LogRhythm_Events.dbo.Msg WITH (NOLOCK)\r\n    JOIN\r\n        (SELECT \r\n            atm.MARCMsgID\r\n        FROM \r\n            LogRhythm_Alarms.dbo.Alarm a WITH (NOLOCK) \r\n        JOIN \r\n            LogRhythm_Alarms.dbo.AlarmToMARCMsg atm WITH (NOLOCK) \r\n            ON a.AlarmID = atm.AlarmID\r\n        JOIN\r\n            [LogRhythm_Alarms].[dbo].[AlarmMetrics] am WITH (NOLOCK) \r\n            ON a.AlarmID = am.AlarmID\r\n        JOIN\r\n            [LogRhythmEMDB].[dbo].AlarmRule ar\r\n            ON a.AlarmRuleID = ar.AlarmRuleID \r\n        WHERE \r\n            ar.[AlarmType] = 5  -- Type d'alarme pertinent\r\n            AND ar.[AlarmRuleGroup] != 'LogRhythm Diagnostics' -- Exclusion des alarmes de diagnostic\r\n            AND $__timeFilter(a.DateInserted)  -- Application de la fenêtre de temps Grafana\r\n        ) amsg\r\n        ON amsg.MARCMsgID = Msg.MsgID\r\n) SourceTable\r\nPIVOT\r\n(\r\n    COUNT(MsgID) \r\n    FOR Alarm_Priority IN ([High], [Medium], [Low])\r\n) PivotTable;\r\n"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 9, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    SUM(ISNULL(New, 0)) AS [New Alarms], -- Total des nouvelles alarmes\r\n    SUM(ISNULL(OpenAlarm, 0) + ISNULL(Working, 0)) AS [In Progress Alarms], -- Total des alarmes en cours de traitement\r\n    SUM(ISNULL(Escalated, 0) + ISNULL(AutoClosed, 0) + ISNULL(FalsePositive, 0) + ISNULL(Resolved, 0) + ISNULL(UnResolved, 0) + ISNULL(Reported, 0) + ISNULL(Monitor, 0)) AS [Closed Alarms], -- Total des alarmes clôturées\r\n\r\n    -- Total des alarmes\r\n    SUM(ISNULL(New, 0) + ISNULL(OpenAlarm, 0) + ISNULL(Working, 0) + ISNULL(Escalated, 0) + ISNULL(AutoClosed, 0) + ISNULL(FalsePositive, 0) + ISNULL(Resolved, 0) + ISNULL(UnResolved, 0) + ISNULL(Reported, 0) + ISNULL(Monitor, 0)) AS [Total Alarms]\r\nFROM\r\n(\r\n    SELECT \r\n        AlarmName.Name,\r\n        COUNT(AlarmName.Name) AS AlarmCount,\r\n        (CONVERT(nvarchar, CASE\r\n            WHEN AlarmStatus = 0 THEN 'New'\r\n            WHEN AlarmStatus = 1 THEN 'OpenAlarm'\r\n            WHEN AlarmStatus = 2 THEN 'Working'\r\n            WHEN AlarmStatus = 3 THEN 'Escalated'\r\n            WHEN AlarmStatus = 4 THEN 'AutoClosed'\r\n            WHEN AlarmStatus = 5 THEN 'FalsePositive'\r\n            WHEN AlarmStatus = 6 THEN 'Resolved'\r\n            WHEN AlarmStatus = 7 THEN 'UnResolved'\r\n            WHEN AlarmStatus = 8 THEN 'Reported'\r\n            WHEN AlarmStatus = 9 THEN 'Monitor'\r\n        END)) AS AlarmStatus\r\n    FROM \r\n        [LogRhythm_Alarms].[dbo].[Alarm] AS Alarm \r\n        JOIN LogRhythmEMDB.dbo.AlarmRule AS AlarmName ON Alarm.AlarmRuleID = AlarmName.AlarmRuleID\r\n    WHERE \r\n        $__timeFilter(Alarm.AlarmDate)\r\n    GROUP BY \r\n        AlarmName.Name, AlarmStatus\r\n) d\r\nPIVOT\r\n(\r\n    MAX(AlarmCount)\r\n    FOR AlarmStatus IN (New, OpenAlarm, Working, Escalated, AutoClosed, FalsePositive, Resolved, UnResolved, Reported, Monitor)\r\n) piv;\r\n"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  AVG(DATEDIFF(MINUTE, [DateEarliestEvidence], [DateCreated])) AS MTTD,\n  AVG(DATEDIFF(MINUTE, [DateCreated], [DateClosed])) AS MTTR\nFROM \n  LogRhythm_CMDB.dbo.[Case] WITH (NOLOCK)\nWHERE  \n  $__timeFilter([DateCreated]) \n\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "  -- Total des cases avec une priorité P3 (Priorité 3 ou 4) dans la période définie\r\n  (SELECT \r\n      COUNT(*) AS Total_Cases_P34\r\n   FROM \r\n      [LogRhythm_CMDB].[dbo].[Case] c WITH (NOLOCK) \r\n      JOIN LogRhythm_CMDB.dbo.CaseStatus cs ON c.CaseStatusID = cs.CaseStatusID\r\n   WHERE \r\n      $__timeFilter(c.DateCreated) \r\n      AND c.Priority BETWEEN 1 AND 2\r\n  );"
    }
   ]
  },
  {
   "title": "Alerts Qualifications",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n \r\n  -- Détail des cases par priorité dans la période définie\r\n  (SELECT \r\n      COUNT(c.CaseID) \r\n   FROM \r\n      LogRhythm_CMDB.dbo.[Case] c WITH (NOLOCK)\r\n   WHERE \r\n      $__timeFilter(c.[DateCreated])\r\n      AND c.Priority = 1\r\n  ) AS Total_Cases_Priority1,\r\n\r\n  (SELECT \r\n      COUNT(c.CaseID) \r\n   FROM \r\n      LogRhythm_CMDB.dbo.[Case] c WITH (NOLOCK)\r\n   WHERE \r\n      $__timeFilter(c.[DateCreated])\r\n      AND c.Priority = 2\r\n  ) AS Total_Cases_Priority2,\r\n\r\n  (SELECT \r\n      COUNT(c.CaseID) \r\n   FROM \r\n      LogRhythm_CMDB.dbo.[Case] c WITH (NOLOCK)\r\n   WHERE \r\n      $__timeFilter(c.[DateCreated])\r\n      AND c.Priority = 3\r\n  ) AS Total_Cases_Priority3,\r\n\r\n  (SELECT \r\n      COUNT(c.CaseID) \r\n   FROM \r\n      LogRhythm_CMDB.dbo.[Case] c WITH (NOLOCK)\r\n   WHERE \r\n      $__timeFilter(c.[DateCreated])\r\n      AND c.Priority = 4\r\n  ) AS Total_Cases_Priority4,\r\n\r\n  (SELECT \r\n      COUNT(c.CaseID) \r\n   FROM \r\n      LogRhythm_CMDB.dbo.[Case] c WITH (NOLOCK)\r\n   WHERE \r\n      $__timeFilter(c.[DateCreated])\r\n      AND c.Priority = 5\r\n  ) AS Total_Cases_Priority5;\r\n"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 15 },
   "targets": [
    {
     "dataset": "LogRhythm_Alarms",
     "rawSql": "SELECT \r\n    Entity.Name AS 'Entity',\r\n    COUNT(AlarmName.Name) AS Total_Alarms\r\nFROM \r\n    [LogRhythm_Alarms].[dbo].[Alarm] AS Alarm\r\nJOIN \r\n    LogRhythmEMDB.dbo.AlarmRule AS AlarmName ON Alarm.AlarmRuleID = AlarmName.AlarmRuleID\r\nJOIN \r\n    LogRhythmEMDB.dbo.Entity AS Entity ON Entity.EntityID = Alarm.EntityID\r\nWHERE \r\n    $__timeFilter(Alarm.DateInserted)\r\n    AND AlarmName.[AlarmRuleGroup] != 'LogRhythm Diagnostics' -- Exclusion des alarmes diagnostics\r\nGROUP BY \r\n    Entity.Name\r\nORDER BY \r\n    Total_Alarms DESC;\r\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "  -- Total des cases avec une priorité P3 (Priorité 3 ou 4) dans la période définie\r\n  (SELECT \r\n      COUNT(*) AS Total_Cases_P34\r\n   FROM \r\n      [LogRhythm_CMDB].[dbo].[Case] c WITH (NOLOCK) \r\n      JOIN LogRhythm_CMDB.dbo.CaseStatus cs ON c.CaseStatusID = cs.CaseStatusID\r\n   WHERE \r\n      $__timeFilter(c.DateCreated) \r\n      AND c.Priority BETWEEN 3 AND 4\r\n  );"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n\tcount(*) as Count\r\nFROM\r\n  \tLogRhythm_Alarms.dbo.Alarm a with (NOLOCK)\r\n  \t  JOIN\r\n\t  LogRhythmEMDB.dbo.AlarmRule ar\r\n\t    ON a.AlarmRuleID = ar.AlarmRuleID\r\nWhere AlarmStatus = 5\r\n    AND\r\n  $__timeFilter(DateInserted)"
    }
   ]
  }
 ]
}