{
 "title": "2025: Admin-Audit Report 2",
 "time": { "from": "now-90d", "to": "now" },
 "panels": [
  {
   "title": "Integrated Log Sources",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(*)\nFROM\n  LogRhythmEMDB.dbo.MsgSource with (NOLOCK)\nWHERE\n  RecordStatus = 1\n"
    }
   ]
  },
  {
   "title": "Messages Per Second",
   "type": "stat",
   "gridPos": { "h": 6, "w": 11, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "USE [LogRhythm_LogMart];\r\nSELECT\r\n  [Avg MPS] = CAST(SUM(CAST(CountProcessedLogs as BIGINT)) AS real) / CAST(DATEDIFF(ss,$__timeFrom(),$__timeTo()) as BIGINT),\r\n\t[Max MPS] = CAST(MAX(CountProcessedLogs) AS float) / 60.0\r\nFROM\r\n\t[dbo].StatsDeploymentCountsMinute with (NOLOCK)\r\nWHERE  $__timeFilter(StatDate);"
    }
   ]
  },
  {
   "title": "Avg Log Size",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Average Log Size Bytes",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mediator.processing",
     "select": [
      [
       { "params": [ "Average_Log_Size_Bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=", "value": "LR-XM-Primary" }
     ]
    }
   ]
  },
  {
   "title": "Devices Not Reporting for 7 Day",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "Use LogRhythmEMDB\r\nselect Count(*) as \"Log Sources\"\r\nfrom MsgSource a join MsgSourceMaxLogDate as b on a.MsgSourceID=b.MsgSourceID\r\n\r\nwhere a.MsgSourceID>0 and a.RecordStatus=1 and b.MaxLogDate > GetDate() - 100\r\nand b.MaxLogDate < DATEADD(minute, -10080, GETDATE()) "
    }
   ]
  },
  {
   "title": "Console Logged in Users",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT DISTINCT SDES.login_name, SDES.host_name as LoginFrom\r\nFROM sys.dm_exec_sessions SDES\r\nWHERE (SDES.database_id =8 or SDES.database_id =9)  AND \r\n(SDES.login_name !='sa' AND SDES.login_name !='' AND SDES.login_name  NOT LIKE 'LogRhythm%')\r\nOrder BY login_name"
    }
   ]
  },
  {
   "title": "MPE Rules Changes",
   "type": "table",
   "gridPos": { "h": 11, "w": 16, "x": 8, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT        dbo.MPERule_SHADOW.DateUpdated, dbo.MPERule_SHADOW.TransType, dbo.MPERule_SHADOW.OriginalUser,\r\n                         dbo.MPERule_SHADOW.MPERuleID, dbo.MPERule.FullName, dbo.MPERule.ShortDesc\r\nFROM            dbo.MPERule_SHADOW INNER JOIN\r\n                         dbo.MPERule ON dbo.MPERule_SHADOW.MPERuleID = dbo.MPERule.MPERuleID\r\nWHERE $__timeFilter(dbo.MPERule_SHADOW.DateUpdated)\r\nORDER BY dbo.MPERule_SHADOW.DateUpdated"
    }
   ]
  },
  {
   "title": "Added Log-Sources",
   "type": "table",
   "gridPos": { "h": 16, "w": 8, "x": 0, "y": 12 },
   "targets": [
    {
     "rawSql": "Use [LogRhythmEMDB]\r\nSELECT dbo.MsgSourceType.FullName, Count(*) as LogSourcesCount, dbo.MsgSource_SHADOW.OriginalUser\r\nFrom dbo.MsgSource INNER JOIN dbo.MsgSourceType ON dbo.MsgSource.MsgSourceTypeID = dbo.MsgSourceType.MsgSourceTypeID INNER JOIN\r\ndbo.MsgSource_SHADOW ON dbo.MsgSource.MsgSourceID = dbo.MsgSource_Shadow.MsgSourceID\r\nWHERE $__timeFilter(dbo.MsgSource_Shadow.TransDate) AND\r\ndbo.MsgSource_Shadow.TransType='INSERT' AND dbo.MsgSourceType.FullName not like'%LogRhythm%'\r\nGROUP BY dbo.MsgSourceType.FullName, dbo.MsgSource_Shadow.OriginalUser"
    }
   ]
  },
  {
   "title": "GLPR Rules Modified",
   "type": "table",
   "gridPos": { "h": 11, "w": 16, "x": 8, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT        TOP (100) PERCENT dbo.GlobalLogProcessingRule_SHADOW.DateUpdated, dbo.GlobalLogProcessingRule_SHADOW.TransType, dbo.GlobalLogProcessingRule_SHADOW.OriginalUser, dbo.GlobalLogProcessingRule.Name, \r\n                         dbo.GlobalLogProcessingRule.LongDesc\r\nFROM            dbo.GlobalLogProcessingRule_SHADOW INNER JOIN\r\n                         dbo.GlobalLogProcessingRule ON dbo.GlobalLogProcessingRule_SHADOW.GlobalLogProcessingRuleID = dbo.GlobalLogProcessingRule.GlobalLogProcessingRuleID\r\nWHERE        (dbo.GlobalLogProcessingRule_SHADOW.DateUpdated IS NOT NULL) AND $__timeFilter(dbo.GlobalLogProcessingRule_SHADOW.DateUpdated)\r\nORDER BY dbo.GlobalLogProcessingRule_SHADOW.DateUpdated"
    }
   ]
  },
  {
   "title": "Use Cases Creation",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT        COUNT(DateStructUpdated) As \"Count\", $__timeGroup(DateStructUpdated, '1d') AS time\nFROM            AIERule INNER JOIN\n                         AlarmRule ON AIERule.AlarmRuleID = AlarmRule.AlarmRuleID INNER JOIN\n                         AIERuleToEngine ON AIERule.AIERuleID = AIERuleToEngine.AIERuleID\n\t\t\t\t\t\t WHERE AIERuleToEngine.Enabled =1 AND AlarmRule.Enabled =1 and  $__timeFilter(DateStructUpdated)\n\t\t\t\t\t\t  GROUP BY $__timeGroup(DateStructUpdated, '1d')"
    }
   ]
  },
  {
   "title": "AIE Rules Changed",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "rawSql": "SELECT dbo.AIERuleToEngine_SHADOW.TransDate, dbo.AIERuleToEngine_SHADOW.TransType, dbo.AIERule.Name AS [Rule Name],\r\n dbo.AIERuleToEngine_SHADOW.OriginalUser,\r\n (SELECT case \r\n When dbo.AIERuleToEngine_SHADOW.Enabled is NULL THEN 'Not Yet Enabled'\r\n When dbo.AIERuleToEngine_SHADOW.Enabled = '0' THEN 'Enabled' end) as 'Rule Status'\r\nFROM   dbo.AIERuleToEngine_SHADOW INNER JOIN\r\n                         dbo.AIERule ON dbo.AIERuleToEngine_SHADOW.AIERuleID = dbo.AIERule.AIERuleID\r\nWHERE        (dbo.AIERuleToEngine_SHADOW.TransDate > GETDATE() - 10)\r\nORDER BY dbo.AIERuleToEngine_SHADOW.TransDate"
    }
   ]
  }
 ]
}