{
 "title": "2025: User Experiance Report",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Total Log Sources",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(*) as Count\nFROM\n  LogRhythmEMDB.dbo.MsgSource with (NOLOCK)\nWHERE\n  RecordStatus = 1 AND Name NOT LIKE 'AI Engine%'"
    }
   ]
  },
  {
   "title": "User Experience Table",
   "type": "stat",
   "gridPos": { "h": 7, "w": 11, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "Select TOP 10000 WT.TaskName, WT.LongResults, WT.ShortResults, WT.NumResults, datediff(minute,WT.DateCreated,WT.DateUpdated) QueryTime, U.Login from WebTask WT Inner Join WebSearch WS ON WS.WebSearchID = WT.WebSearchId INNER JOIN WebTaskToUser WTU On WTU.WebTaskId = WT.TaskID Inner JOin SCUser U On U.UserID = WTU.UserId"
    }
   ]
  },
  {
   "title": "Messages Per Second",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "USE [LogRhythm_LogMart];\r\nSELECT\r\n  [Avg MPS] = CAST(SUM(CAST(CountProcessedLogs as BIGINT)) AS real) / CAST(DATEDIFF(ss,$__timeFrom(),$__timeTo()) as BIGINT),\r\n\t[Max MPS] = CAST(MAX(CountProcessedLogs) AS float) / 60.0\r\nFROM\r\n\t[dbo].StatsDeploymentCountsMinute with (NOLOCK)\r\nWHERE  $__timeFilter(StatDate);"
    }
   ]
  },
  {
   "title": "FAILED Web Console Searches",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT        dbo.WebTask.DateCreated, dbo.Person.FullName AS [Analyst Name], dbo.WebTask.TaskName, dbo.WebTask.LongResults, dbo.WebTask.ShortResults, dbo.WebTask.NumResults\r\nFROM            dbo.WebSearch INNER JOIN\r\n                         dbo.WebTask ON dbo.WebSearch.WebSearchID = dbo.WebTask.WebSearchId INNER JOIN\r\n                         dbo.WebTaskToUser ON dbo.WebTask.TaskID = dbo.WebTaskToUser.WebTaskId INNER JOIN\r\n                         dbo.Person ON dbo.WebTaskToUser.UserId = dbo.Person.PersonID\r\nWHERE        (dbo.WebTask.LongResults NOT LIKE 'Alarm Drill%') AND dbo.WebTask.ShortResults LIKE '%Failed%' AND $__timeFilter(dbo.WebTask.DateCreated\r\n)\r\nORDER BY dbo.WebTask.DateCreated"
    }
   ]
  },
  {
   "title": "User Experience Table",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "rawSql": "Select TOP 10000 WT.TaskName, WT.LongResults, WT.ShortResults, WT.NumResults, datediff(minute,WT.DateCreated,WT.DateUpdated) QueryTime, U.Login from WebTask WT Inner Join WebSearch WS ON WS.WebSearchID = WT.WebSearchId INNER JOIN WebTaskToUser WTU On WTU.WebTaskId = WT.TaskID Inner JOin SCUser U On U.UserID = WTU.UserId"
    }
   ]
  },
  {
   "title": "Heavy Searches by Results Returned ",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "rawSql": "Select TOP 10000 WT.TaskName, WT.LongResults, WT.ShortResults, WT.NumResults, datediff(minute,WT.DateCreated,WT.DateUpdated) QueryTime, U.Login from WebTask WT Inner Join WebSearch WS ON WS.WebSearchID = WT.WebSearchId INNER JOIN WebTaskToUser WTU On WTU.WebTaskId = WT.TaskID Inner JOin SCUser U On U.UserID = WTU.UserId where WT.NumResults > 25000"
    }
   ]
  },
  {
   "title": "Heavy Searches By Query Time",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {
     "rawSql": "Select TOP 10000 WT.TaskName, WT.LongResults, WT.ShortResults, WT.NumResults, datediff(minute,WT.DateCreated,WT.DateUpdated) QueryTime, U.Login from WebTask WT Inner Join WebSearch WS ON WS.WebSearchID = WT.WebSearchId INNER JOIN WebTaskToUser WTU On WTU.WebTaskId = WT.TaskID Inner JOin SCUser U On U.UserID = WTU.UserId where  datediff(minute,WT.DateCreated,WT.DateUpdated) >= 3"
    }
   ]
  }
 ]
}