{
 "title": "2025: Customer Created Dashboard 06",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<a>\n  <div style=\"display: flex; flex-direction: column; justify-content: center; align-items: center; width: 100%; height: 100%; cursor: pointer; background-color: #f0f0f0; background-image: url('background-image-url.jpg'); background-size: cover; background-position: center;\">\n    <img src=\"https://www.cdg.ma/themes/cdg/asset/img/logo_hp.png\" style=\"max-width: 80%; max-height: 80%; display: block; margin: auto;\">\n  </div>\n</a>\n"
   }
  },
  {
   "type": "table",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 3 },
   "targets": [
    {
     "dataset": "LogRhythm_Alarms",
     "rawSql": "SELECT \r\n    Entity.Name AS 'Entity',\r\n    COUNT(AlarmName.Name) AS Total_Alarms\r\nFROM \r\n    [LogRhythm_Alarms].[dbo].[Alarm] AS Alarm\r\nJOIN \r\n    LogRhythmEMDB.dbo.AlarmRule AS AlarmName ON Alarm.AlarmRuleID = AlarmName.AlarmRuleID\r\nJOIN \r\n    LogRhythmEMDB.dbo.Entity AS Entity ON Entity.EntityID = Alarm.EntityID\r\nWHERE \r\n    $__timeFilter(Alarm.DateInserted)\r\n    AND AlarmName.[AlarmRuleGroup] != 'LogRhythm Diagnostics' -- Exclusion des alarmes diagnostics\r\nGROUP BY \r\n    Entity.Name\r\nORDER BY \r\n    Total_Alarms DESC;\r\n"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 9, "w": 19, "x": 5, "y": 3 },
   "targets": [
    {
     "dataset": "LogRhythm_Alarms",
     "rawSql": "SELECT\r\n    e.Name AS Entity_Name,                                   -- Nom de l'entité\r\n    COUNT(c.CaseNumber) AS Total_Cases,                     -- Nombre total de cases par entité\r\n    COUNT(CASE WHEN c.Priority = 3 THEN 1 END) AS Total_Priority_3, -- Nombre de cases avec priorité 3\r\n    COUNT(CASE WHEN c.Priority = 2 THEN 1 END) AS Total_Priority_2, -- Nombre de cases avec priorité 2\r\n    ISNULL(AVG(DATEDIFF(MINUTE, c.DateEarliestEvidence, c.DateCreated)), 0) AS Avg_TTD, -- Temps moyen avant détection\r\n    ISNULL(AVG(DATEDIFF(MINUTE, c.DateCreated, c.DateClosed)), 0) AS Avg_TTR -- Temps moyen avant clôture\r\nFROM \r\n    LogRhythm_CMDB.dbo.[Case] AS c WITH (NOLOCK)\r\nLEFT JOIN \r\n    LogRhythmEMDB.dbo.[Entity] AS e ON c.EntityID = e.EntityID -- Joindre la table Entity pour obtenir le nom de l'entité\r\nWHERE  \r\n    $__timeFilter(c.[DateCreated])                            -- Filtre temporel pour les incidents créés dans une certaine période\r\nGROUP BY \r\n    e.Name                                                   -- Groupement par nom de l'entité\r\nORDER BY \r\n    Total_Cases DESC;                                        -- Tri par nombre total de cases en décroissant\r\n"
    }
   ]
  },
  {
   "title": "Vecteurs d'attaque par Filiale",
   "type": "table",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 12 },
   "targets": [
    {
     "dataset": "LogRhythm_Alarms",
     "rawSql": "SELECT \r\n    e.Name AS Entity,                                             -- Nom de l'entité\r\n    SUM(CASE WHEN t.Tag = 'Vecteur-WAN' THEN 1 ELSE 0 END) AS [Vecteur-WAN],  -- Compte pour Vecteur-WAN\r\n    SUM(CASE WHEN t.Tag = 'Vecteur-Mail' THEN 1 ELSE 0 END) AS [Vecteur-Mail], -- Compte pour Vecteur-Mail\r\n    SUM(CASE WHEN t.Tag = 'Vecteur-Navigation' THEN 1 ELSE 0 END) AS [Vecteur-Navigation], -- Compte pour Vecteur-Navigation\r\n    SUM(CASE WHEN t.Tag = 'Vecteur-LAN' THEN 1 ELSE 0 END) AS [Vecteur-LAN], -- Compte pour Vecteur-LAN\r\n    SUM(CASE WHEN t.Tag = 'Vecteur-Local' THEN 1 ELSE 0 END) AS [Vecteur-Local], -- Compte pour Vecteur-Local\r\n    SUM(CASE WHEN t.Tag = 'Vecteur-VPN' THEN 1 ELSE 0 END) AS [Vecteur-VPN],  -- Compte pour Vecteur-VPN\r\n    SUM(CASE WHEN t.Tag = 'Vecteur-USB' THEN 1 ELSE 0 END) AS [Vecteur-USB]  -- Compte pour Vecteur-USB\r\n    \r\nFROM \r\n    [LogRhythm_CMDB].[dbo].[CaseToTag] AS ct\r\nJOIN  \r\n    [LogRhythm_CMDB].[dbo].[Tag] AS t ON ct.TagID = t.TagID        -- Association entre tags et cases\r\nJOIN \r\n    [LogRhythm_CMDB].[dbo].[Case] AS c ON c.CaseID = ct.CaseID     -- Association entre cases et leurs tags\r\nLEFT JOIN \r\n    [LogRhythmEMDB].[dbo].[Entity] AS e ON c.EntityID = e.EntityID -- Association des entités\r\nWHERE \r\n    $__timeFilter(c.[DateCreated])                                -- Filtrage temporel\r\n    AND t.Tag LIKE 'Vecteur-%'                                    -- Filtrer uniquement les tags qui commencent par \"Vecteur-\"\r\nGROUP BY \r\n    e.Name                                                       -- Groupement par entité\r\nORDER BY \r\n    e.Name;                                                      -- Tri par nom de l'entité\r\n"
    }
   ]
  },
  {
   "title": "Vecteurs d'attaque",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  Tag, \r\n  COUNT(ct.CaseID) AS Count \r\nFROM \r\n  [LogRhythm_CMDB].[dbo].[CaseToTag] AS ct\r\nJOIN  \r\n  [LogRhythm_CMDB].[dbo].[Tag] AS t ON ct.TagID = t.TagID\r\nJOIN \r\n  [LogRhythm_CMDB].[dbo].[Case] AS c ON c.CaseID = ct.CaseID\r\nWHERE \r\n  $__timeFilter(c.[DateCreated])\r\n  AND t.Tag LIKE 'vecteur%'   -- Filtrer uniquement les tags qui commencent par \"vecteur\"\r\nGROUP BY \r\n  Tag;\r\n"
    }
   ]
  },
  {
   "title": "Direction d'attaque",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  Tag, \r\n  COUNT(ct.CaseID) AS Count \r\nFROM \r\n  [LogRhythm_CMDB].[dbo].[CaseToTag] AS ct\r\nJOIN  \r\n  [LogRhythm_CMDB].[dbo].[Tag] AS t ON ct.TagID = t.TagID\r\nJOIN \r\n  [LogRhythm_CMDB].[dbo].[Case] AS c ON c.CaseID = ct.CaseID\r\nWHERE \r\n  $__timeFilter(c.[DateCreated])\r\n  AND t.Tag LIKE 'Direction%'   -- Filtrer uniquement les tags qui commencent par \"vecteur\"\r\nGROUP BY \r\n  Tag;\r\n"
    }
   ]
  },
  {
   "title": "Direction d'attaque par Filiale",
   "type": "table",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 20 },
   "targets": [
    {
     "dataset": "LogRhythm_Alarms",
     "rawSql": "SELECT \r\n    e.Name AS Entity,                                             -- Nom de l'entité\r\n    SUM(CASE WHEN t.Tag = 'Direction-Inbound' THEN 1 ELSE 0 END) AS [Direction-Inbound],  -- Compte pour VDirection-Inbound\r\n    SUM(CASE WHEN t.Tag = 'Direction-Outbound' THEN 1 ELSE 0 END) AS [Direction-Outbound], -- Compte pour Direction-Outbound\r\n    SUM(CASE WHEN t.Tag = 'Direction-Internal' THEN 1 ELSE 0 END) AS [Direction-Internal]   -- Compte pour Direction-Internal\r\n    \r\nFROM \r\n    [LogRhythm_CMDB].[dbo].[CaseToTag] AS ct\r\nJOIN  \r\n    [LogRhythm_CMDB].[dbo].[Tag] AS t ON ct.TagID = t.TagID        -- Association entre tags et cases\r\nJOIN \r\n    [LogRhythm_CMDB].[dbo].[Case] AS c ON c.CaseID = ct.CaseID     -- Association entre cases et leurs tags\r\nLEFT JOIN \r\n    [LogRhythmEMDB].[dbo].[Entity] AS e ON c.EntityID = e.EntityID -- Association des entités\r\nWHERE \r\n    $__timeFilter(c.[DateCreated])                                -- Filtrage temporel\r\n    AND t.Tag LIKE 'Direction-%'                                    -- Filtrer uniquement les tags qui commencent par \"Vecteur-\"\r\nGROUP BY \r\n    e.Name                                                       -- Groupement par entité\r\nORDER BY \r\n    e.Name;                                                      -- Tri par nom de l'entité\r\n"
    }
   ]
  }
 ]
}